#!/usr/bin/env zsh

setopt SH_WORD_SPLIT NO_NOMATCH

# Cygwin alias (for Windows)
# setopt ALIASES
alias cat="/usr/bin/cat"
alias clear="/usr/bin/clear"
alias cut="/usr/bin/cut"
alias date="/usr/bin/date"
alias echo="/usr/bin/echo"
alias expr="/usr/bin/expr"
alias ffmpeg="/usr/bin/ffmpeg"
alias ffplay="/usr/bin/ffplay"
alias ffprobe="/usr/bin/ffprobe"
alias file="/usr/bin/file"
alias find="/usr/bin/find"
alias ftp="/usr/bin/ftp"
alias grep="/usr/bin/grep"
alias head="/usr/bin/head"
alias ldd="/usr/bin/ldd"
alias ls="/usr/bin/ls"
alias md5sum="/usr/bin/md5sum"
alias mintty="/usr/bin/mintty"
alias mkdir="/usr/bin/mkdir"
alias mv="/usr/bin/mv"
alias pwd="/usr/bin/pwd"
alias rm="/usr/bin/rm"
alias rsync="/usr/bin/rsync"
alias scp="/usr/bin/scp"
alias sed="/usr/bin/sed"
alias sleep="/usr/bin/sleep"
alias ssh-add="/usr/bin/ssh-add"
alias ssh-agent="/usr/bin/ssh-agent"
alias ssh-keygen="/usr/bin/ssh-keygen"
alias ssh-keyscan="/usr/bin/ssh-keyscan"
alias ssh="/usr/bin/ssh"
alias sshpass="/usr/bin/sshpass"
alias expect="/usr/bin/expect"
alias tail="/usr/bin/tail"
alias touch="/usr/bin/touch"
alias tr="/usr/bin/tr"
alias wc="/usr/bin/wc"
alias x264="/usr/bin/x264"
alias zenity="/usr/bin/zenity"
alias bc="/usr/bin/bc"
alias all-commands='ls /bin | grep ".exe" | cut -d "." -f 1'

# List of alias for drives:
alias A:="/cygdrive/a"
alias B:="/cygdrive/b"
alias C:="/cygdrive/c"
alias D:="/cygdrive/d"
alias E:="/cygdrive/e"
alias F:="/cygdrive/f"
alias G:="/cygdrive/g"
alias H:="/cygdrive/h"
alias I:="/cygdrive/i"
alias J:="/cygdrive/j"
alias K:="/cygdrive/k"
alias L:="/cygdrive/l"
alias M:="/cygdrive/m"
alias N:="/cygdrive/n"
alias O:="/cygdrive/o"
alias P:="/cygdrive/p"
alias Q:="/cygdrive/q"
alias R:="/cygdrive/r"
alias S:="/cygdrive/s"
alias T:="/cygdrive/t"
alias U:="/cygdrive/u"
alias V:="/cygdrive/v"
alias W:="/cygdrive/w"
alias X:="/cygdrive/x"
alias Y:="/cygdrive/y"
alias Z:="/cygdrive/z"
