#!/usr/bin/env zsh

setopt NO_NOMATCH

###############################################################
# ks-mp4s-wrapper (ks-tools) - Wrapper for ks-mp4s            #
# Date: 25-08-2026                                            #
# Author: dmesg00                                             #
# Contact: dmesg00@duck.com                                   #
###############################################################
VERSION=("9.5")
M_DATE=("250826")

# Conversion parameters
p_ffmpeg=(ffmpeg -i)
p_ffmpeg_patched=(-max_muxing_queue_size 9999)
rel_size=("720x404")
configFolder=${HOME}/.ks-tools 
configFile=${configFolder}/ks-mp4s
source ${configFile}

# Global parameters
dirTemp=("/tmp")
listTemp=("ks-tools.list")
ksToolsTempFolder=("/tmp/ks-tools")

# Check cygwin alias (for Windows)
if [[ -f "/usr/bin/cygwin-alias.zsh" ]] ; then
  setopt ALIASES
  cygwin=("yes")
  source "/usr/bin/cygwin-alias.zsh"
else
  cygwin=("no")
fi

# Check if ffmpeg is installed
ffmpeg_test=$(ffmpeg --help 2>&1)
error_ffmpeg=$?
if (( error_ffmpeg != 0 )) ; then
  print ""
  print "* ks-mp4s-wrapper (ks-tools) v${VERSION} (${M_DATE})"
  print ""
  print "+ The 'ffmpeg' tool is not installed!"
  print ""
  exit
fi

# Check if ks-mp4s is installed
wrap_test=$(ks-mp4s &> /dev/null)
error_wrap=$?
if (( error_wrap != 0 )) ; then
  print ""
  print "* ks-mp4s-wrapper (ks-tools) v${VERSION} (${M_DATE})"
  print ""
  print "+ The 'ks-mp4s' tool is not installed!"
  print ""
  exit
fi

# Funcion to show the name of file/folder from full path
# Syntax: extractFolderOrFile <full/path/file.txt>
extractFolderOrFile() {
  pathToExtract=("${1}/")
  findFolder=0
  count=1
  nameFolder=$(print ${pathToExtract} | cut -d "/" -f ${count})
  count=$(expr $count + 1)
  while (( findFolder == 0 )) ; do
    nameFolderTemp=$(print ${pathToExtract} | cut -d "/" -f ${count})
    if [[ -z "${nameFolderTemp}" ]] ; then
      findFolder=1
    else
      nameFolder=("${nameFolderTemp}")
      count=$(expr $count + 1)
    fi
  done
  print "${nameFolder}"
}

# Function to remove extension from file
# Syntax: removeExtension "<text>"
removeExtension() {
  wordToConvert=${1}
  ksToolsSedFile=("${ksToolsTempFolder}/ks-tools-${RANDOM}.txt")
  mkdir -p ${ksToolsTempFolder} && chmod 777 -R ${ksToolsTempFolder} 2> /dev/null
  print "${wordToConvert}" > ${ksToolsSedFile}
  # Remove extensions
  sed -i 's/\.avi//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.mp4//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.mkv//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.mov//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.vob//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.mpg//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.mpeg//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.wmv//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.ogv//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.webm//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.flv//g' "${ksToolsSedFile}" &> /dev/null
  # Show file without extension
  wordToConvert=$(cat ${ksToolsSedFile})
  print ${wordToConvert}
}

# Function to show files with spaces.
# Syntax: showFileWithSpace <file number>
showFileWithSpace() {
  print "${1}" > ${dirTemp}/name.tmp
  sed -i 's/_/ /g' ${dirTemp}/name.tmp 2> /dev/null
  DisplayName=$(cat ${dirTemp}/name.tmp)
  rm -rf ${dirTemp}/name.tmp
  print ${DisplayName}
}

# Show info tracks of input video video file.
# Syntax: showInfo <video_file>
showInfo() {
  print ""
  print "* Information of ${1}:"
  print ""
  print "+ Video Tracks:"
  "${p_ffmpeg[@]}" "${1}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | cut -d "," -f 1
  print ""
  print "+ Audio Tracks:"
  "${p_ffmpeg[@]}" "${1}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | cut -d "," -f 1
  print ""
  print "+ Subtitle Tracks:"
  "${p_ffmpeg[@]}" "${1}" 2>&1 | grep Stream | tr -s " " | grep "Subtitle:" | cut -d "," -f 1
  print ""
  exit
}

# Show the video track default
# Syntax: showVideoDefault <video_file>
showVideoDefault() {
  # Check de video track by default
  video_default=$("${p_ffmpeg[@]}" "${1}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
  if [[ -z "${video_default}" ]] ; then
    video_default=("0:0")
  else
    video_default_patch=$(print ${video_default} | cut -c4)
    if [[ "${video_default_patch}" == ":" ]] ; then
      video_default=$(print ${video_default} | cut -c1-3)
    else
      video_default=("${video_default}")
    fi
  fi
  print "${video_default}"
}

# Show the audio track default
# Syntax: showAudioDefault <video_file>
showAudioDefault() {
  # Check the audio track by default
  audio_default=$("${p_ffmpeg[@]}" "${1}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | grep "(${default_lang_audio})" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
  if [[ -z "${audio_default}" ]] ; then
    audio_default=$("${p_ffmpeg[@]}" "${1}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
    if [[ -z "${audio_default}" ]] ; then
      audio_default=("0:1")
    else
      audio_default_patch=$(print ${audio_default} | cut -c4)
      if [[ "${audio_default_patch}" == ":" ]] ; then
        audio_default=$(print ${audio_default} | cut -c1-3)
      else
        audio_default=("${audio_default}")
      fi
    fi
  else
    audio_default_patch=$(print ${audio_default} | cut -c4)
    if [[ "${audio_default_patch}" == ":" ]] ; then
      audio_default=$(print ${audio_default} | cut -c1-3)
    else
      audio_default=("${audio_default}")
    fi
  fi
  print "${audio_default}"
}

# Show the subtitle track default
# Syntax: showSubtitleDefault <video_file>
showSubtitleDefault() {
  # Check the subtitle track by default
  subtitle_default=$("${p_ffmpeg[@]}" "${1}" 2>&1 | grep Stream | tr -s " " | grep "Subtitle:" | grep "(${default_lang_subt})" | grep "(forced)" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
  if [[ -z "${subtitle_default}" ]] ; then
    subtitle_default=$("${p_ffmpeg[@]}" "${1}" 2>&1 | grep Stream | tr -s " " | grep "Subtitle:" | grep "(${default_lang_subt})" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
    if [[ -z "${subtitle_default}" ]] ; then
      subtitle_default=$("${p_ffmpeg[@]}" "${1}" 2>&1 | grep Stream | tr -s " " | grep "Subtitle:" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
      if [[ -z "${subtitle_default}" ]] ; then
        subtitle_default=("0:3")
      else
        subtitle_default_patch=$(print ${subtitle_default} | cut -c4)
        if [[ "${subtitle_default_patch}" == ":" ]] ; then
          subtitle_default=$(print ${subtitle_default} | cut -c1-3)
        else
          subtitle_default=("${subtitle_default}")
        fi
      fi
    else
      subtitle_default_patch=$(print ${subtitle_default} | cut -c4)
      if [[ "${subtitle_default_patch}" == ":" ]] ; then
        subtitle_default=$(print ${subtitle_default} | cut -c1-3)
      else
        subtitle_default=("${subtitle_default}")
      fi
    fi
  else
    subtitle_default_patch=$(print ${subtitle_default} | cut -c4)
    if [[ "${subtitle_default_patch}" == ":" ]] ; then
      subtitle_default=$(print ${subtitle_default} | cut -c1-3)
    else
      subtitle_default=("${subtitle_default}")
    fi
  fi
  print "${subtitle_default}"
}

# Show default resolution
# Syntax: showResolutionDefault
showResolutionDefault() {
  print "${rel_size}"
}

# Show default year (METADATA)
# Syntax: showResolutionDefault
showYearDefault() {
  current_date=$(date +%Y)
  print "${current_date}"
}

# Show the name title default (MEDATA)
# Syntax: showNameDefault <video_file>
showNameDefault() {
  # Prepare name title by default
  FullPath=("${1}")
  name_title_default=$(extractFolderOrFile "${FullPath}")
  name_title_default=$(removeExtension "${name_title_default}")
  name_title_default=$(showFileWithSpace "${name_title_default}")
  print "${name_title_default}"
}

# Show the genre default (MEDATA)
# Syntax: showGenreDefault
showGenreDefault() {
  print "Unknown"
}

# Show help
showHelp() {
  print ""
  print "* ks-mp4s-wrapper (ks-tools) v${VERSION} (${M_DATE})"
  print ""
  print "\- Wrapper for ks-mp4s to create graphical interfaces"
  print ""
  print "+ Syntax:"
  print ""
  print " * TRACKS/CONFIG DETECT:"
  print ""
  print "  $ ks-mp4s-wrapper --show-info <video_file>"
  print "  $ ks-mp4s-wrapper --show-video-default <video_file>"
  print "  $ ks-mp4s-wrapper --show-audio-default <video_file>"
  print "  $ ks-mp4s-wrapper --show-subtitle-default <video_file>"
  print "  $ ks-mp4s-wrapper --show-resolution-default"
  print ""
  print " * METADATA DETECT:"
  print ""
  print "  $ ks-mp4s-wrapper --show-name-title-default <video_file>"
  print "  $ ks-mp4s-wrapper --show-year-default"
  print "  $ ks-mp4s-wrapper --show-genre-default"
  print ""
  print " * CONVERT:"
  print ""
  print " $ ks-mp4s-wrapper --conv </path/video_file> </path/output_prefix> <video-track> <audio-track> <resolution> \"<name-title>\" <year> \"<genre>\" [patch]"
  print " $ ks-mp4s-wrapper --conv-with-sub </path/video_file> </path/output_prefix> <video-track> <audio-track> <subs-track> <resolution> \"<name-title>\" <year> \"<genre>\" [patch]"
  print " $ ks-mp4s-wrapper --conv-widescreen </path/video_file> </path/output_prefix> <video-track> <audio-track> <subs-track> <resolution> \"<name-title>\" <year> \"<genre>\" [patch]"
  print " $ ks-mp4s-wrapper --conv-with-sub-widescreen </path/video_file> </path/output_prefix> <video-track> <audio-track> <subs-track> <resolution> \"<name-title>\" <year> \"<genre>\" [patch]"
  print ""
  print " * CONVERT WITH DEFAULT DETECTION (NOT RECOMMENDED):"
  print ""
  print " $ ks-mp4s-wrapper --conv </path/video_file> </path/output_prefix>"
  print " $ ks-mp4s-wrapper --conv-widescreen </path/video_file> </path/output_prefix>"
  print " $ ks-mp4s-wrapper --conv-with-sub </path/video_file> </path/output_prefix>"
  print " $ ks-mp4s-wrapper --conv-with-sub-widescreen </path/video_file> </path/output_prefix>"
  print ""
  print "* EXAMPLES:"
  print ""
  print " $ ks-mp4s-wrapper --conv /tmp/video.mkv /tmp/output 0:0 0:1 720x404 \"My video\" 2018 \"Comedy\""
  print " $ ks-mp4s-wrapper --conv-with-sub /tmp/video.mkv /tmp/output 0:0 0:1 0:3 720x404 \"My video\" 2018 \"Comedy\""
  print " $ ks-mp4s-wrapper --conv-widescreen /tmp/video.mkv /tmp/output 0:0 0:1 720x480 \"My video\" 2018 \"Comedy\" patch"
  print " $ ks-mp4s-wrapper --conv-with-sub-widescreen /tmp/video.mkv /tmp/output 0:0 0:1 0:3 720x480 \"My video\" 2018 \"Comedy\""
  print ""
  print "* Notes:"
  print ""
  print " + The option 'patch' apply the '-thread_queue_size 2048' patch to ffmpeg."
  print " + If you specify a path or file with spaces, you must use quotes."
  if [[ "${cygwin}" == "yes" ]] ; then
    print " + In Cygwin, you should always use relative paths with this tool."
  fi
  print ""
  exit
}

# Run the parameters
if [[ -z "${1}" ]] ; then
  showHelp
elif [[ "${1}" == "--show-info" ]] ; then
  # Check if file exist
  if [[ -f "${2}" ]] ; then
    showInfo "${2}"
  else
    print ""
    print "* The file '${2}' does not exist!'"
    print ""
    exit
  fi
elif [[ "${1}" == "--show-video-default" ]] ; then
  # Check if file exist
  if [[ -f "${2}" ]] ; then
    showVideoDefault "${2}"
  else
    print ""
    print "* The file '${2}' does not exist!'"
    print ""
    exit
  fi
elif [[ "${1}" == "--show-audio-default" ]] ; then
  # Check if file exist
  if [[ -f "${2}" ]] ; then
    showAudioDefault "${2}"
  else
    print ""
    print "* The file '${2}' does not exist!'"
    print ""
    exit
  fi
elif [[ "${1}" == "--show-subtitle-default" ]] ; then
  # Check if file exist
  if [[ -f "${2}" ]] ; then
    showSubtitleDefault "${2}"
  else
    print ""
    print "* The file '${2}' does not exist!'"
    print ""
    exit
  fi
elif [[ "${1}" == "--show-resolution-default" ]] ; then
  showResolutionDefault
elif [[ "${1}" == "--show-name-title-default" ]] ; then
  # Check if file exist
  if [[ -f "${2}" ]] ; then
    showNameDefault "${2}"
  else
    print ""
    print "* The file '${2}' does not exist!'"
    print ""
    exit
  fi
elif [[ "${1}" == "--show-year-default" ]] ; then
  showYearDefault
elif [[ "${1}" == "--show-genre-default" ]] ; then
  showGenreDefault
elif [[ "${1}" == "--conv" ]] ; then
  # Check if file exist
  if [[ -f "${2}" ]] ; then
    if [[ "${10}" == "patch" ]] ; then
      print "${4}\n${5}\nn\nn\n${6}\ny\n${7}\n${8}\n${9}\ny\n" | ks-mp4s "${2}" "${3}"
    else
      print "${4}\n${5}\nn\nn\n${6}\nn\n${7}\n${8}\n${9}\ny\n" | ks-mp4s "${2}" "${3}"
    fi
  else
    print ""
    print "* The file '${2}' does not exist!'"
    print ""
    exit
  fi
elif [[ "${1}" == "--conv-widescreen" ]] ; then
  # Check if file exist
  if [[ -f "${2}" ]] ; then
    if [[ "${10}" == "patch" ]] ; then
      print "${4}\n${5}\nn\ny\n${6}\ny\n${7}\n${8}\n${9}\ny\n" | ks-mp4s "${2}" "${3}"
    else
      print "${4}\n${5}\nn\ny\n${6}\nn\n${7}\n${8}\n${9}\ny\n" | ks-mp4s "${2}" "${3}"
    fi
  else
    print ""
    print "* The file '${2}' does not exist!'"
    print ""
    exit
  fi
elif [[ "${1}" == "--conv-with-sub" ]] ; then
  # Check if file exist
  if [[ -f "${2}" ]] ; then
    if [[ "${11}" == "patch" ]] ; then
      print "${4}\n${5}\ny\n${6}\nn\n${7}\ny\n${8}\n${9}\n${10}\ny\n" | ks-mp4s "${2}" "${3}"
    else
      print "${4}\n${5}\ny\n${6}\nn\n${7}\nn\n${8}\n${9}\n${10}\ny\n" | ks-mp4s "${2}" "${3}"
    fi
  else
    print ""
    print "* The file '${2}' does not exist!'"
    print ""
    exit
  fi
elif [[ "${1}" == "--conv-with-sub-widescreen" ]] ; then
  # Check if file exist
  if [[ -f "${2}" ]] ; then
    if [[ "${11}" == "patch" ]] ; then
      print "${4}\n${5}\ny\n${6}\ny\n${7}\ny\n${8}\n${9}\n${10}\ny\n" | ks-mp4s "${2}" "${3}"
    else
      print "${4}\n${5}\ny\n${6}\ny\n${7}\nn\n${8}\n${9}\n${10}\ny\n" | ks-mp4s "${2}" "${3}"
    fi
  else
    print ""
    print "* The file '${2}' does not exist!'"
    print ""
    exit
  fi
else
  showHelp
fi
