#!/usr/bin/env zsh

setopt NO_NOMATCH

#######################################################################
# ks-conf (ks-tools) - Tool for create and modify configuration files #
# Date: 25-08-2026                                                    #
# Author: dmesg00                                                     #
# Contact: dmesg00@duck.com                                           #
#######################################################################
VERSION=("9.5")
M_DATE=("250826")

# Check cygwin alias (for Windows)
if [[ -f "/usr/bin/cygwin-alias.zsh" ]] ; then
  setopt ALIASES
  source "/usr/bin/cygwin-alias.zsh"
fi

# Check and create configuration file for ks-mp4
check_create_conf_ks_mp4() {
  configFolder=${HOME}/.ks-tools 
  configFile=${configFolder}/ks-mp4
  rel_size=("1280x534")
  vcodec=("libx264")
  b_vcodec=("2200k")
  v_preset=("slow")
  acodec=("aac")
  b_acodec=("192k")
  default_lang_audio=("spa")
  default_lang_subt=("spa")
  v_ext=("mp4")
  mkdir -p ${configFolder}
  if [[ -f ${configFile} ]] ; then
    exist_rel_size=$(cat ${configFile} | grep "rel_size=")
    exist_vcodec=$(cat ${configFile} | grep "vcodec=" | cut -c2 | cut -d "_" -f 1)
    exist_b_vcodec=$(cat ${configFile} | grep "b_vcodec=") 
    exist_v_preset=$(cat ${configFile} | grep "v_preset=") 
    exist_acodec=$(cat ${configFile} | grep "acodec" | cut -c2 | cut -d "_" -f 1) 
    exist_b_acodec=$(cat ${configFile} | grep "b_acodec=") 
    exist_default_lang_audio=$(cat ${configFile} | grep "default_lang_audio=") 
    exist_default_lang_subt=$(cat ${configFile} | grep "default_lang_subt=") 
    exist_v_ext=$(cat ${configFile} | grep "v_ext=")
    if [[ -z ${exist_rel_size} ]] ; then
      print "rel_size=${rel_size}" >> ${configFile}
    fi
    if [[ -z ${exist_vcodec} ]] ; then
      print "vcodec=${vcodec}" >> ${configFile}
    fi 
    if [[ -z ${exist_b_vcodec} ]] ; then
      print "b_vcodec=${b_vcodec}" >> ${configFile}
    fi
    if [[ -z ${exist_v_preset} ]] ; then
      print "v_preset=${v_preset}" >> ${configFile}
    fi
    if [[ -z ${exist_acodec} ]] ; then
      print "acodec=${acodec}" >> ${configFile}
    fi
    if [[ -z ${exist_b_acodec} ]] ; then
      print "b_acodec=${b_acodec}" >> ${configFile}
    fi
    if [[ -z ${exist_default_lang_audio} ]] ; then
      print "default_lang_audio=${default_lang_audio}" >> ${configFile}
    fi
    if [[ -z ${exist_default_lang_subt} ]] ; then
      print "default_lang_subt=${default_lang_subt}" >> ${configFile}
    fi
    if [[ -z ${exist_v_ext} ]] ; then
      print "v_ext=${v_ext}" >> ${configFile}
    fi
    source ${configFile}
  else
    print "#!/usr/bin/env zsh" > ${configFile}
    print "" >> ${configFile}
    print "rel_size=${rel_size}" >> ${configFile}
    print "vcodec=${vcodec}" >> ${configFile}
    print "b_vcodec=${b_vcodec}" >> ${configFile}
    print "v_preset=${v_preset}" >> ${configFile}
    print "acodec=${acodec}" >> ${configFile}
    print "b_acodec=${b_acodec}" >> ${configFile}
    print "default_lang_audio=${default_lang_audio}" >> ${configFile}
    print "default_lang_subt=${default_lang_subt}" >> ${configFile}
    print "v_ext=${v_ext}" >> ${configFile}
    source ${configFile}
  fi
}

# Check and create configuration file for ks-mp4s
check_create_conf_ks_mp4s() {
  configFolder=${HOME}/.ks-tools 
  configFile=${configFolder}/ks-mp4s
  rel_size=("720x480")
  vcodec=("libx264")
  b_vcodec=("950k")
  v_preset=("slow")
  acodec=("aac")
  b_acodec=("128k")
  default_lang_audio=("spa")
  default_lang_subt=("spa")
  v_ext=("mp4")
  mkdir -p ${configFolder}
  if [[ -f ${configFile} ]] ; then
    exist_rel_size=$(cat ${configFile} | grep "rel_size=")
    exist_vcodec=$(cat ${configFile} | grep "vcodec=" | cut -c2 | cut -d "_" -f 1)
    exist_b_vcodec=$(cat ${configFile} | grep "b_vcodec=") 
    exist_v_preset=$(cat ${configFile} | grep "v_preset=") 
    exist_acodec=$(cat ${configFile} | grep "acodec" | cut -c2 | cut -d "_" -f 1) 
    exist_b_acodec=$(cat ${configFile} | grep "b_acodec=") 
    exist_default_lang_audio=$(cat ${configFile} | grep "default_lang_audio=") 
    exist_default_lang_subt=$(cat ${configFile} | grep "default_lang_subt=") 
    exist_v_ext=$(cat ${configFile} | grep "v_ext=")
    if [[ -z ${exist_rel_size} ]] ; then
      print "rel_size=${rel_size}" >> ${configFile}
    fi
    if [[ -z ${exist_vcodec} ]] ; then
      print "vcodec=${vcodec}" >> ${configFile}
    fi 
    if [[ -z ${exist_b_vcodec} ]] ; then
      print "b_vcodec=${b_vcodec}" >> ${configFile}
    fi
    if [[ -z ${exist_v_preset} ]] ; then
      print "v_preset=${v_preset}" >> ${configFile}
    fi
    if [[ -z ${exist_acodec} ]] ; then
      print "acodec=${acodec}" >> ${configFile}
    fi
    if [[ -z ${exist_b_acodec} ]] ; then
      print "b_acodec=${b_acodec}" >> ${configFile}
    fi
    if [[ -z ${exist_default_lang_audio} ]] ; then
      print "default_lang_audio=${default_lang_audio}" >> ${configFile}
    fi
    if [[ -z ${exist_default_lang_subt} ]] ; then
      print "default_lang_subt=${default_lang_subt}" >> ${configFile}
    fi
    if [[ -z ${exist_v_ext} ]] ; then
      print "v_ext=${v_ext}" >> ${configFile}
    fi
    source ${configFile}
  else
    print "#!/usr/bin/env zsh" > ${configFile}
    print "" >> ${configFile}
    print "rel_size=${rel_size}" >> ${configFile}
    print "vcodec=${vcodec}" >> ${configFile}
    print "b_vcodec=${b_vcodec}" >> ${configFile}
    print "v_preset=${v_preset}" >> ${configFile}
    print "acodec=${acodec}" >> ${configFile}
    print "b_acodec=${b_acodec}" >> ${configFile}
    print "default_lang_audio=${default_lang_audio}" >> ${configFile}
    print "default_lang_subt=${default_lang_subt}" >> ${configFile}
    print "v_ext=${v_ext}" >> ${configFile}
    source ${configFile}
  fi
}

# Check and create configuration file for ks-mp4k
check_create_conf_ks_mp4k() {
  configFolder=${HOME}/.ks-tools 
  configFile=${configFolder}/ks-mp4k
  rel_size=("3840x2160")
  vcodec=("libx264")
  b_vcodec=("6000k")
  v_preset=("medium")
  acodec=("aac")
  b_acodec=("320k")
  default_lang_audio=("spa")
  default_lang_subt=("spa")
  v_ext=("mp4")
  mkdir -p ${configFolder}
  if [[ -f ${configFile} ]] ; then
    exist_rel_size=$(cat ${configFile} | grep "rel_size=")
    exist_vcodec=$(cat ${configFile} | grep "vcodec=" | cut -c2 | cut -d "_" -f 1)
    exist_b_vcodec=$(cat ${configFile} | grep "b_vcodec=") 
    exist_v_preset=$(cat ${configFile} | grep "v_preset=") 
    exist_acodec=$(cat ${configFile} | grep "acodec" | cut -c2 | cut -d "_" -f 1) 
    exist_b_acodec=$(cat ${configFile} | grep "b_acodec=") 
    exist_default_lang_audio=$(cat ${configFile} | grep "default_lang_audio=") 
    exist_default_lang_subt=$(cat ${configFile} | grep "default_lang_subt=") 
    exist_v_ext=$(cat ${configFile} | grep "v_ext=")
    if [[ -z ${exist_rel_size} ]] ; then
      print "rel_size=${rel_size}" >> ${configFile}
    fi
    if [[ -z ${exist_vcodec} ]] ; then
      print "vcodec=${vcodec}" >> ${configFile}
    fi 
    if [[ -z ${exist_b_vcodec} ]] ; then
      print "b_vcodec=${b_vcodec}" >> ${configFile}
    fi
    if [[ -z ${exist_v_preset} ]] ; then
      print "v_preset=${v_preset}" >> ${configFile}
    fi
    if [[ -z ${exist_acodec} ]] ; then
      print "acodec=${acodec}" >> ${configFile}
    fi
    if [[ -z ${exist_b_acodec} ]] ; then
      print "b_acodec=${b_acodec}" >> ${configFile}
    fi
    if [[ -z ${exist_default_lang_audio} ]] ; then
      print "default_lang_audio=${default_lang_audio}" >> ${configFile}
    fi
    if [[ -z ${exist_default_lang_subt} ]] ; then
      print "default_lang_subt=${default_lang_subt}" >> ${configFile}
    fi
    if [[ -z ${exist_v_ext} ]] ; then
      print "v_ext=${v_ext}" >> ${configFile}
    fi
    source ${configFile}
  else
    print "#!/usr/bin/env zsh" > ${configFile}
    print "" >> ${configFile}
    print "rel_size=${rel_size}" >> ${configFile}
    print "vcodec=${vcodec}" >> ${configFile}
    print "b_vcodec=${b_vcodec}" >> ${configFile}
    print "v_preset=${v_preset}" >> ${configFile}
    print "acodec=${acodec}" >> ${configFile}
    print "b_acodec=${b_acodec}" >> ${configFile}
    print "default_lang_audio=${default_lang_audio}" >> ${configFile}
    print "default_lang_subt=${default_lang_subt}" >> ${configFile}
    print "v_ext=${v_ext}" >> ${configFile}
    source ${configFile}
  fi
}

# Check and create configuration file for ks-avi
check_create_conf_ks_avi() {
  configFolder=${HOME}/.ks-tools 
  configFile=${configFolder}/ks-avi
  rel_size=("720x480")
  vcodec=("libxvid")
  b_vcodec=("3000k")
  v_preset=("slow")
  acodec=("libmp3lame")
  b_acodec=("192k")
  default_lang_audio=("spa")
  default_lang_subt=("spa")
  v_ext=("avi")
  mkdir -p ${configFolder}
  if [[ -f ${configFile} ]] ; then
    exist_rel_size=$(cat ${configFile} | grep "rel_size=")
    exist_vcodec=$(cat ${configFile} | grep "vcodec=" | cut -c2 | cut -d "_" -f 1)
    exist_b_vcodec=$(cat ${configFile} | grep "b_vcodec=") 
    exist_v_preset=$(cat ${configFile} | grep "v_preset=") 
    exist_acodec=$(cat ${configFile} | grep "acodec" | cut -c2 | cut -d "_" -f 1) 
    exist_b_acodec=$(cat ${configFile} | grep "b_acodec=") 
    exist_default_lang_audio=$(cat ${configFile} | grep "default_lang_audio=") 
    exist_default_lang_subt=$(cat ${configFile} | grep "default_lang_subt=") 
    exist_v_ext=$(cat ${configFile} | grep "v_ext=")
    if [[ -z ${exist_rel_size} ]] ; then
      print "rel_size=${rel_size}" >> ${configFile}
    fi
    if [[ -z ${exist_vcodec} ]] ; then
      print "vcodec=${vcodec}" >> ${configFile}
    fi 
    if [[ -z ${exist_b_vcodec} ]] ; then
      print "b_vcodec=${b_vcodec}" >> ${configFile}
    fi
    if [[ -z ${exist_v_preset} ]] ; then
      print "v_preset=${v_preset}" >> ${configFile}
    fi
    if [[ -z ${exist_acodec} ]] ; then
      print "acodec=${acodec}" >> ${configFile}
    fi
    if [[ -z ${exist_b_acodec} ]] ; then
      print "b_acodec=${b_acodec}" >> ${configFile}
    fi
    if [[ -z ${exist_default_lang_audio} ]] ; then
      print "default_lang_audio=${default_lang_audio}" >> ${configFile}
    fi
    if [[ -z ${exist_default_lang_subt} ]] ; then
      print "default_lang_subt=${default_lang_subt}" >> ${configFile}
    fi
    if [[ -z ${exist_v_ext} ]] ; then
      print "v_ext=${v_ext}" >> ${configFile}
    fi
    source ${configFile}
  else
    print "#!/usr/bin/env zsh" > ${configFile}
    print "" >> ${configFile}
    print "rel_size=${rel_size}" >> ${configFile}
    print "vcodec=${vcodec}" >> ${configFile}
    print "b_vcodec=${b_vcodec}" >> ${configFile}
    print "v_preset=${v_preset}" >> ${configFile}
    print "acodec=${acodec}" >> ${configFile}
    print "b_acodec=${b_acodec}" >> ${configFile}
    print "default_lang_audio=${default_lang_audio}" >> ${configFile}
    print "default_lang_subt=${default_lang_subt}" >> ${configFile}
    print "v_ext=${v_ext}" >> ${configFile}
    source ${configFile}
  fi
}

# Check and create configuration file for ks-av1
check_create_conf_ks_av1() {
  configFolder=${HOME}/.ks-tools 
  configFile=${configFolder}/ks-av1
  rel_size=("1280x534")
  vcodec=("libsvtav1")
  b_vcodec=("2000k")
  v_preset=("disabled")
  acodec=("libvorbis")
  b_acodec=("160k")
  default_lang_audio=("spa")
  default_lang_subt=("spa")
  v_ext=("webm")
  mkdir -p ${configFolder}
  if [[ -f ${configFile} ]] ; then
    exist_rel_size=$(cat ${configFile} | grep "rel_size=")
    exist_vcodec=$(cat ${configFile} | grep "vcodec=" | cut -c2 | cut -d "_" -f 1)
    exist_b_vcodec=$(cat ${configFile} | grep "b_vcodec=") 
    exist_v_preset=$(cat ${configFile} | grep "v_preset=") 
    exist_acodec=$(cat ${configFile} | grep "acodec" | cut -c2 | cut -d "_" -f 1) 
    exist_b_acodec=$(cat ${configFile} | grep "b_acodec=") 
    exist_default_lang_audio=$(cat ${configFile} | grep "default_lang_audio=") 
    exist_default_lang_subt=$(cat ${configFile} | grep "default_lang_subt=") 
    exist_v_ext=$(cat ${configFile} | grep "v_ext=")
    if [[ -z ${exist_rel_size} ]] ; then
      print "rel_size=${rel_size}" >> ${configFile}
    fi
    if [[ -z ${exist_vcodec} ]] ; then
      print "vcodec=${vcodec}" >> ${configFile}
    fi 
    if [[ -z ${exist_b_vcodec} ]] ; then
      print "b_vcodec=${b_vcodec}" >> ${configFile}
    fi
    if [[ -z ${exist_v_preset} ]] ; then
      print "v_preset=${v_preset}" >> ${configFile}
    fi
    if [[ -z ${exist_acodec} ]] ; then
      print "acodec=${acodec}" >> ${configFile}
    fi
    if [[ -z ${exist_b_acodec} ]] ; then
      print "b_acodec=${b_acodec}" >> ${configFile}
    fi
    if [[ -z ${exist_default_lang_audio} ]] ; then
      print "default_lang_audio=${default_lang_audio}" >> ${configFile}
    fi
    if [[ -z ${exist_default_lang_subt} ]] ; then
      print "default_lang_subt=${default_lang_subt}" >> ${configFile}
    fi
    if [[ -z ${exist_v_ext} ]] ; then
      print "v_ext=${v_ext}" >> ${configFile}
    fi
    source ${configFile}
  else
    print "#!/usr/bin/env zsh" > ${configFile}
    print "" >> ${configFile}
    print "rel_size=${rel_size}" >> ${configFile}
    print "vcodec=${vcodec}" >> ${configFile}
    print "b_vcodec=${b_vcodec}" >> ${configFile}
    print "v_preset=${v_preset}" >> ${configFile}
    print "acodec=${acodec}" >> ${configFile}
    print "b_acodec=${b_acodec}" >> ${configFile}
    print "default_lang_audio=${default_lang_audio}" >> ${configFile}
    print "default_lang_subt=${default_lang_subt}" >> ${configFile}
    print "v_ext=${v_ext}" >> ${configFile}
    source ${configFile}
  fi
}

# Check and create configuration file for ks-av1s
check_create_conf_ks_av1s() {
  configFolder=${HOME}/.ks-tools 
  configFile=${configFolder}/ks-av1s
  rel_size=("720x480")
  vcodec=("libsvtav1")
  b_vcodec=("850k")
  v_preset=("disabled")
  acodec=("libvorbis")
  b_acodec=("128k")
  default_lang_audio=("spa")
  default_lang_subt=("spa")
  v_ext=("webm")
  mkdir -p ${configFolder}
  if [[ -f ${configFile} ]] ; then
    exist_rel_size=$(cat ${configFile} | grep "rel_size=")
    exist_vcodec=$(cat ${configFile} | grep "vcodec=" | cut -c2 | cut -d "_" -f 1)
    exist_b_vcodec=$(cat ${configFile} | grep "b_vcodec=") 
    exist_v_preset=$(cat ${configFile} | grep "v_preset=") 
    exist_acodec=$(cat ${configFile} | grep "acodec" | cut -c2 | cut -d "_" -f 1) 
    exist_b_acodec=$(cat ${configFile} | grep "b_acodec=") 
    exist_default_lang_audio=$(cat ${configFile} | grep "default_lang_audio=") 
    exist_default_lang_subt=$(cat ${configFile} | grep "default_lang_subt=") 
    exist_v_ext=$(cat ${configFile} | grep "v_ext=")
    if [[ -z ${exist_rel_size} ]] ; then
      print "rel_size=${rel_size}" >> ${configFile}
    fi
    if [[ -z ${exist_vcodec} ]] ; then
      print "vcodec=${vcodec}" >> ${configFile}
    fi 
    if [[ -z ${exist_b_vcodec} ]] ; then
      print "b_vcodec=${b_vcodec}" >> ${configFile}
    fi
    if [[ -z ${exist_v_preset} ]] ; then
      print "v_preset=${v_preset}" >> ${configFile}
    fi
    if [[ -z ${exist_acodec} ]] ; then
      print "acodec=${acodec}" >> ${configFile}
    fi
    if [[ -z ${exist_b_acodec} ]] ; then
      print "b_acodec=${b_acodec}" >> ${configFile}
    fi
    if [[ -z ${exist_default_lang_audio} ]] ; then
      print "default_lang_audio=${default_lang_audio}" >> ${configFile}
    fi
    if [[ -z ${exist_default_lang_subt} ]] ; then
      print "default_lang_subt=${default_lang_subt}" >> ${configFile}
    fi
    if [[ -z ${exist_v_ext} ]] ; then
      print "v_ext=${v_ext}" >> ${configFile}
    fi
    source ${configFile}
  else
    print "#!/usr/bin/env zsh" > ${configFile}
    print "" >> ${configFile}
    print "rel_size=${rel_size}" >> ${configFile}
    print "vcodec=${vcodec}" >> ${configFile}
    print "b_vcodec=${b_vcodec}" >> ${configFile}
    print "v_preset=${v_preset}" >> ${configFile}
    print "acodec=${acodec}" >> ${configFile}
    print "b_acodec=${b_acodec}" >> ${configFile}
    print "default_lang_audio=${default_lang_audio}" >> ${configFile}
    print "default_lang_subt=${default_lang_subt}" >> ${configFile}
    print "v_ext=${v_ext}" >> ${configFile}
    source ${configFile}
  fi
}

# Check and create configuration file for ks-mp3/ks-mp3-album
check_create_conf_ks_mp3() {
  configFolder=${HOME}/.ks-tools 
  configFile=${configFolder}/ks-mp3
  acodec=("libmp3lame")
  b_acodec=("128k")
  v_ext=("mp3")
  default_lang_audio=("spa")
  mkdir -p ${configFolder}
  if [[ -f ${configFile} ]] ; then
    exist_acodec=$(cat ${configFile} | grep "acodec" | cut -c2 | cut -d "_" -f 1) 
    exist_b_acodec=$(cat ${configFile} | grep "b_acodec=") 
    exist_default_lang_audio=$(cat ${configFile} | grep "default_lang_audio=") 
    exist_v_ext=$(cat ${configFile} | grep "v_ext=")
    if [[ -z ${exist_acodec} ]] ; then
      print "acodec=${acodec}" >> ${configFile}
    fi
    if [[ -z ${exist_b_acodec} ]] ; then
      print "b_acodec=${b_acodec}" >> ${configFile}
    fi
    if [[ -z ${exist_default_lang_audio} ]] ; then
      print "default_lang_audio=${default_lang_audio}" >> ${configFile}
    fi
    if [[ -z ${exist_v_ext} ]] ; then
      print "v_ext=${v_ext}" >> ${configFile}
    fi
    source ${configFile}
  else
    print "#!/usr/bin/env zsh" > ${configFile}
    print "" >> ${configFile}
    print "acodec=${acodec}" >> ${configFile}
    print "b_acodec=${b_acodec}" >> ${configFile}
    print "default_lang_audio=${default_lang_audio}" >> ${configFile}
    print "v_ext=${v_ext}" >> ${configFile}
    source ${configFile}
  fi
}

# Check and create configuration file for ks-oga/ks-oga-album
check_create_conf_ks_oga() {
  configFolder=${HOME}/.ks-tools 
  configFile=${configFolder}/ks-oga
  acodec=("libvorbis")
  b_acodec=("130k")
  v_ext=("oga")
  default_lang_audio=("spa")
  mkdir -p ${configFolder}
  if [[ -f ${configFile} ]] ; then
    exist_acodec=$(cat ${configFile} | grep "acodec" | cut -c2 | cut -d "_" -f 1) 
    exist_b_acodec=$(cat ${configFile} | grep "b_acodec=") 
    exist_default_lang_audio=$(cat ${configFile} | grep "default_lang_audio=") 
    exist_v_ext=$(cat ${configFile} | grep "v_ext=")
    if [[ -z ${exist_acodec} ]] ; then
      print "acodec=${acodec}" >> ${configFile}
    fi
    if [[ -z ${exist_b_acodec} ]] ; then
      print "b_acodec=${b_acodec}" >> ${configFile}
    fi
    if [[ -z ${exist_default_lang_audio} ]] ; then
      print "default_lang_audio=${default_lang_audio}" >> ${configFile}
    fi
    if [[ -z ${exist_v_ext} ]] ; then
      print "v_ext=${v_ext}" >> ${configFile}
    fi
    source ${configFile}
  else
    print "#!/usr/bin/env zsh" > ${configFile}
    print "" >> ${configFile}
    print "acodec=${acodec}" >> ${configFile}
    print "b_acodec=${b_acodec}" >> ${configFile}
    print "default_lang_audio=${default_lang_audio}" >> ${configFile}
    print "v_ext=${v_ext}" >> ${configFile}
    source ${configFile}
  fi
}

# Function to reset config files
# Sintaxis: remove_video_audio_config <name config file>
remove_video_audio_config() {
  name_file=${1}
  print "#!/usr/bin/env zsh" > ${HOME}/.ks-tools/${name_file}
  print "" >> ${HOME}/.ks-tools/${name_file} 
}

# Function to video configuration
# Sintaxis: edit_video_config <name config file>
edit_video_config() {
  check_create_conf_ks_mp4
  check_create_conf_ks_mp4s
  check_create_conf_ks_mp4k
  check_create_conf_ks_avi
  check_create_conf_ks_av1
  check_create_conf_ks_av1s
  name_file=${1}
  editing=0
  while (( editing == 0 )) ; do
    source ${HOME}/.ks-tools/${name_file}
    clear
    print ""
    print -P "* %Bks-conf%b (ks-tools) %Bv${VERSION}%b (${M_DATE})" 
    print ""
    print -P "* Editing %U${HOME}/.ks-tools/${name_file}%u"
    print ""
    print -P " r - Edit resolution (%B${rel_size}%b)"
    print -P " v - Edit video codec (%B${vcodec}%b)"
    print -P " b - Edit video bitrate (%B${b_vcodec}%b)"
    print -P " p - Edit video preset (%B${v_preset}%b)"
    print -P " a - Edit audio codec (%B${acodec}%b)"
    print -P " i - Edit audio bitrate (%B${b_acodec}%b)"
    print -P " l - Edit preferred language (%B${default_lang_audio}%b)"
    print -P " s - Edit preferred subtitles (%B${default_lang_subt}%b)"
    print ""
    print " c - Reset configuration file"
    print " q - Exit to main menu"
    print ""
    print -n "* Choose an option (r/v/b/p/a/i/l/s/c/q): " ; read option
    if [[ "${option}" == "r" ]] ; then
      # Set resolution
      print ""
      print -P "* %URecommended%u: 720x480 / 1280x534 / 1280x720 / 1920x1080 / 3840x2160"
      print ""
      print -P -n "* [Current: %B${rel_size}%b] Type the resolution: " ; read resolution
      if [[ -z ${resolution} ]] ; then
        print > /dev/null
      else
        remove_video_audio_config ${name_file}
        print "rel_size=${resolution}" >> ${HOME}/.ks-tools/${name_file}
        print "vcodec=${vcodec}" >> ${HOME}/.ks-tools/${name_file}
        print "b_vcodec=${b_vcodec}" >> ${HOME}/.ks-tools/${name_file}
        print "v_preset=${v_preset}" >> ${HOME}/.ks-tools/${name_file}
        print "acodec=${acodec}" >> ${HOME}/.ks-tools/${name_file}
        print "b_acodec=${b_acodec}" >> ${HOME}/.ks-tools/${name_file}
        print "default_lang_audio=${default_lang_audio}" >> ${HOME}/.ks-tools/${name_file}
        print "default_lang_subt=${default_lang_subt}" >> ${HOME}/.ks-tools/${name_file}
        print "v_ext=${v_ext}" >> ${HOME}/.ks-tools/${name_file}
        source ${HOME}/.ks-tools/${name_file}
      fi
    elif [[ "${option}" == "v" ]] ; then
      # Set video codec
      if [[ "$v_ext" == "mp4" ]] ; then
       print ""
       print -P "* %URecommended%u: mpeg4 / libxvid / libx264 / libx265 / libaom-av1"
      fi
      if [[ "$v_ext" == "avi" ]] ; then
       print ""
       print -P "* %URecommended%u: mpeg4 / libxvid"
      fi
      if [[ "$v_ext" == "webm" ]] ; then
       print ""
       print -P "* %URecommended%u: libvpx-vp9 / libsvtav1 / libaom-av1"
      fi
      if [[ "$v_ext" == "mkv" ]] ; then
       print ""
       print -P "* %URecommended%u: libx264 / libx265 / libsvtav1 / libaom-av1"
      fi
      print ""
      print -P -n "* [Current: %B${vcodec}%b] Type the video codec: " ; read videocodec
      if [[ -z ${videocodec} ]] ; then
        print > /dev/null
      else
        remove_video_audio_config ${name_file}
        print "rel_size=${rel_size}" >> ${HOME}/.ks-tools/${name_file}
        print "vcodec=${videocodec}" >> ${HOME}/.ks-tools/${name_file}
        print "b_vcodec=${b_vcodec}" >> ${HOME}/.ks-tools/${name_file}
        print "v_preset=${v_preset}" >> ${HOME}/.ks-tools/${name_file}
        print "acodec=${acodec}" >> ${HOME}/.ks-tools/${name_file}
        print "b_acodec=${b_acodec}" >> ${HOME}/.ks-tools/${name_file}
        print "default_lang_audio=${default_lang_audio}" >> ${HOME}/.ks-tools/${name_file}
        print "default_lang_subt=${default_lang_subt}" >> ${HOME}/.ks-tools/${name_file}
        print "v_ext=${v_ext}" >> ${HOME}/.ks-tools/${name_file}
        source ${HOME}/.ks-tools/${name_file}
      fi
    elif [[ "${option}" == "b" ]] ; then
      # Set bitrate for video
      print ""
      print -P "* %URecommended%u: 850k / 950k / 2000k / 2200k / 3000k / 6000k / 10000k"
      print ""
      print -P -n "* [Current: %B${b_vcodec}%b] Type bitrate for video: " ; read videobitrate
      if [[ -z ${videobitrate} ]] ; then
        print > /dev/null
      else
        remove_video_audio_config ${name_file}
        print "rel_size=${rel_size}" >> ${HOME}/.ks-tools/${name_file}
        print "vcodec=${vcodec}" >> ${HOME}/.ks-tools/${name_file}
        print "b_vcodec=${videobitrate}" >> ${HOME}/.ks-tools/${name_file}
        print "v_preset=${v_preset}" >> ${HOME}/.ks-tools/${name_file}
        print "acodec=${acodec}" >> ${HOME}/.ks-tools/${name_file}
        print "b_acodec=${b_acodec}" >> ${HOME}/.ks-tools/${name_file}
        print "default_lang_audio=${default_lang_audio}" >> ${HOME}/.ks-tools/${name_file}
        print "default_lang_subt=${default_lang_subt}" >> ${HOME}/.ks-tools/${name_file}
        print "v_ext=${v_ext}" >> ${HOME}/.ks-tools/${name_file}
        source ${HOME}/.ks-tools/${name_file}
      fi
    elif [[ "${option}" == "p" ]] ; then
      # Set video preset
      print ""
      print -P "* %UPresets%u: ultrafast / superfast / veryfast / faster / fast"
      print "           medium / slow / slower / veryslow"
      print ""
      print -P -n "* [Current: %B${v_preset}%b] Type the preset: " ; read videopreset
      if [[ -z ${videopreset} ]] ; then
        print > /dev/null
      else
        remove_video_audio_config ${name_file}
        print "rel_size=${rel_size}" >> ${HOME}/.ks-tools/${name_file}
        print "vcodec=${vcodec}" >> ${HOME}/.ks-tools/${name_file}
        print "b_vcodec=${b_vcodec}" >> ${HOME}/.ks-tools/${name_file}
        print "v_preset=${videopreset}" >> ${HOME}/.ks-tools/${name_file}
        print "acodec=${acodec}" >> ${HOME}/.ks-tools/${name_file}
        print "b_acodec=${b_acodec}" >> ${HOME}/.ks-tools/${name_file}
        print "default_lang_audio=${default_lang_audio}" >> ${HOME}/.ks-tools/${name_file}
        print "default_lang_subt=${default_lang_subt}" >> ${HOME}/.ks-tools/${name_file}
        print "v_ext=${v_ext}" >> ${HOME}/.ks-tools/${name_file}
        source ${HOME}/.ks-tools/${name_file}
      fi
    elif [[ "${option}" == "a" ]] ; then
      # Set audio codec
      if [[ "$v_ext" == "mp4" ]] ; then
       print ""
       print -P "* %URecommended%u: aac / libmp3lame / ac3 / libopus / mp2"
      fi
      if [[ "$v_ext" == "avi" ]] ; then
       print ""
       print -P "* %URecommended%u: ac3 / libmp3lame / mp2"
      fi
      if [[ "$v_ext" == "webm" ]] ; then
       print ""
       print -P "* %URecommended%u: libvorbis / libopus"
      fi
      if [[ "$v_ext" == "mkv" ]] ; then
       print ""
       print -P "* %URecommended%u: aac / libvorbis / libopus / ac3 / libmp3lame"
      fi
      print ""
      print -P -n "* [Current: %B${acodec}%b] Type the audio codec: " ; read audiocodec
      if [[ -z ${audiocodec} ]] ; then
        print > /dev/null
      else
        remove_video_audio_config ${name_file}
        print "rel_size=${rel_size}" >> ${HOME}/.ks-tools/${name_file}
        print "vcodec=${vcodec}" >> ${HOME}/.ks-tools/${name_file}
        print "b_vcodec=${b_vcodec}" >> ${HOME}/.ks-tools/${name_file}
        print "v_preset=${v_preset}" >> ${HOME}/.ks-tools/${name_file}
        print "acodec=${audiocodec}" >> ${HOME}/.ks-tools/${name_file}
        print "b_acodec=${b_acodec}" >> ${HOME}/.ks-tools/${name_file}
        print "default_lang_audio=${default_lang_audio}" >> ${HOME}/.ks-tools/${name_file}
        print "default_lang_subt=${default_lang_subt}" >> ${HOME}/.ks-tools/${name_file}
        print "v_ext=${v_ext}" >> ${HOME}/.ks-tools/${name_file}
        source ${HOME}/.ks-tools/${name_file}
      fi
    elif [[ "${option}" == "i" ]] ; then
      # Set bitrate for audio
      print ""
      print -P "* %URecommended%u: 92k / 128k / 160k / 192k / 256k / 320k / 640k"
      print ""
      print -P -n "* [Current: %B${b_acodec}%b] Type bitrate for audio: " ; read audiobitrate
      if [[ -z ${audiobitrate} ]] ; then
        print > /dev/null
      else
        remove_video_audio_config ${name_file}
        print "rel_size=${rel_size}" >> ${HOME}/.ks-tools/${name_file}
        print "vcodec=${vcodec}" >> ${HOME}/.ks-tools/${name_file}
        print "b_vcodec=${b_vcodec}" >> ${HOME}/.ks-tools/${name_file}
        print "v_preset=${v_preset}" >> ${HOME}/.ks-tools/${name_file}
        print "acodec=${acodec}" >> ${HOME}/.ks-tools/${name_file}
        print "b_acodec=${audiobitrate}" >> ${HOME}/.ks-tools/${name_file}
        print "default_lang_audio=${default_lang_audio}" >> ${HOME}/.ks-tools/${name_file}
        print "default_lang_subt=${default_lang_subt}" >> ${HOME}/.ks-tools/${name_file}
        print "v_ext=${v_ext}" >> ${HOME}/.ks-tools/${name_file}
        source ${HOME}/.ks-tools/${name_file}
      fi
    elif [[ "${option}" == "l" ]] ; then
      # Set default audio language
      print ""
      print -P "* %UExamples%u: "
      print "   English --> eng"
      print "   Spanish --> spa"
      print "   Italian --> ita"
      print "   French  --> fra"
      print ""
      print "* Complete 639-2 codes: https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes"
      print ""
      print -P -n "* [Current: %B${default_lang_audio}%b] Type the preferred audio language: " ; read audiolanguage
      if [[ -z ${audiolanguage} ]] ; then
        print > /dev/null
      else
        remove_video_audio_config ${name_file}
        print "rel_size=${rel_size}" >> ${HOME}/.ks-tools/${name_file}
        print "vcodec=${vcodec}" >> ${HOME}/.ks-tools/${name_file}
        print "b_vcodec=${b_vcodec}" >> ${HOME}/.ks-tools/${name_file}
        print "v_preset=${v_preset}" >> ${HOME}/.ks-tools/${name_file}
        print "acodec=${acodec}" >> ${HOME}/.ks-tools/${name_file}
        print "b_acodec=${b_acodec}" >> ${HOME}/.ks-tools/${name_file}
        print "default_lang_audio=${audiolanguage}" >> ${HOME}/.ks-tools/${name_file}
        print "default_lang_subt=${default_lang_subt}" >> ${HOME}/.ks-tools/${name_file}
        print "v_ext=${v_ext}" >> ${HOME}/.ks-tools/${name_file}
        source ${HOME}/.ks-tools/${name_file}
      fi
    elif [[ "${option}" == "s" ]] ; then
      # Set default audio language
      print ""
      print -P "* %UExamples%u: "
      print "   English --> eng"
      print "   Spanish --> spa"
      print "   Italian --> ita"
      print "   French  --> fra"
      print ""
      print "* Complete 639-2 codes: https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes"
      print ""
      print -P -n "* [Current: %B${default_lang_subt}%b] Type the preferred subtitles language: " ; read subtitlelanguage
      if [[ -z ${subtitlelanguage} ]] ; then
        print > /dev/null
      else
        remove_video_audio_config ${name_file}
        print "rel_size=${rel_size}" >> ${HOME}/.ks-tools/${name_file}
        print "vcodec=${vcodec}" >> ${HOME}/.ks-tools/${name_file}
        print "b_vcodec=${b_vcodec}" >> ${HOME}/.ks-tools/${name_file}
        print "v_preset=${v_preset}" >> ${HOME}/.ks-tools/${name_file}
        print "acodec=${acodec}" >> ${HOME}/.ks-tools/${name_file}
        print "b_acodec=${b_acodec}" >> ${HOME}/.ks-tools/${name_file}
        print "default_lang_audio=${default_lang_audio}" >> ${HOME}/.ks-tools/${name_file}
        print "default_lang_subt=${subtitlelanguage}" >> ${HOME}/.ks-tools/${name_file}
        print "v_ext=${v_ext}" >> ${HOME}/.ks-tools/${name_file}
        source ${HOME}/.ks-tools/${name_file}
      fi
    elif [[ "${option}" == "c" ]] ; then
      rm -rf ${HOME}/.ks-tools/${name_file}
      check_create_conf_ks_mp4
      check_create_conf_ks_mp4s
      check_create_conf_ks_mp4k
      check_create_conf_ks_avi
      check_create_conf_ks_av1
      check_create_conf_ks_av1s
    elif [[ "${option}" == "q" ]] ; then
      editing=1
    else
      print ""
      print "+ Invalid option"
      print -P -n "* Press %UENTER%u to return menu " ; read return
    fi
  done
}

# Function to audio configuration
# Sintaxis: edit_audio_config <name config file>
edit_audio_config() {
  check_create_conf_ks_mp3
  check_create_conf_ks_oga
  name_file=${1}
  editing=0
  while (( editing == 0 )) ; do
    source ${HOME}/.ks-tools/${name_file}
    clear
    print ""
    print -P "* %Bks-conf%b (ks-tools) %Bv${VERSION}%b (${M_DATE})" 
    print ""
    print -P "* Editing %U${HOME}/.ks-tools/${name_file}%u"
    print ""
    print -P " a - Edit audio bitrate (%B${b_acodec}%b)"
    print -P " l - Edit preferred language (%B${default_lang_audio}%b)"
    print ""
    print " c - Reset configuration file"
    print " q - Exit to main menu"
    print ""
    print -n "* Choose an option (a/l/c/q): " ; read option
    if [[ "${option}" == "a" ]] ; then
    # Set bitrate for audio
      if [[ "$v_ext" == "mp3" ]] ; then
       print ""
       print -P "* %URecommended%u: 92k / 128k / 192k / 256k / 320k / 640k"
      fi
      if [[ "$v_ext" == "oga" ]] ; then
       print ""
       print -P "* %URecommended%u: 96k / 112k / 130k / 160k / 224k / 256k / 320k"
      fi
      print ""
      print -P -n "* [Current: %B${b_acodec}%b] Type bitrate for audio: " ; read audiobitrate
      if [[ -z ${audiobitrate} ]] ; then
        print > /dev/null
      else
        remove_video_audio_config ${name_file}
        print "acodec=${acodec}" >> ${HOME}/.ks-tools/${name_file}
        print "b_acodec=${audiobitrate}" >> ${HOME}/.ks-tools/${name_file}
        print "default_lang_audio=${default_lang_audio}" >> ${HOME}/.ks-tools/${name_file}
        print "v_ext=${v_ext}" >>  ${HOME}/.ks-tools/${name_file} 
        source ${HOME}/.ks-tools/${name_file}
      fi
    elif [[ "${option}" == "l" ]] ; then
      # Set default audio language
      print ""
      print -P "* %UExamples%u: "
      print "   English --> eng"
      print "   Spanish --> spa"
      print "   Italian --> ita"
      print "   French  --> fra"
      print ""
      print "* Complete 639-2 codes: https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes"
      print ""
      print -P -n "* [Current: %B${default_lang_audio}%b] Type the preferred audio language: " ; read audiolanguage
      if [[ -z ${audiolanguage} ]] ; then
        print > /dev/null
      else
        remove_video_audio_config ${name_file}
        print "acodec=${acodec}" >> ${HOME}/.ks-tools/${name_file}
        print "b_acodec=${b_acodec}" >> ${HOME}/.ks-tools/${name_file}
        print "default_lang_audio=${audiolanguage}" >> ${HOME}/.ks-tools/${name_file}
        print "v_ext=${v_ext}" >>  ${HOME}/.ks-tools/${name_file} 
        source ${HOME}/.ks-tools/${name_file}
      fi
    elif [[ "${option}" == "c" ]] ; then
      rm -rf ${HOME}/.ks-tools/${name_file}
      check_create_conf_ks_mp3
      check_create_conf_ks_oga
    elif [[ "${option}" == "q" ]] ; then
      editing=1
    else
      print ""
      print "+ Invalid option"
      print -P -n "* Press %UENTER%u to return menu " ; read return
    fi
  done
}

# Run all functions for check configuration files
check_create_conf_ks_mp4
check_create_conf_ks_mp4s
check_create_conf_ks_mp4k
check_create_conf_ks_avi
check_create_conf_ks_av1
check_create_conf_ks_av1s
check_create_conf_ks_mp3
check_create_conf_ks_oga

# Load all configurations and show main menu
show_menu=0
while (( show_menu == 0 )) ; do
  clear
  print ""
  print -P "* %Bks-conf%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
  print ""
  print "\- Tool for create and modify all configuration files"
  print ""
  source ${HOME}/.ks-tools/ks-mp4
  print -P " m - Edit %Uks-mp4%u config (%B${rel_size}/${vcodec}/${b_vcodec}/${acodec}/${b_acodec}/${default_lang_audio}%b)"
  source ${HOME}/.ks-tools/ks-mp4k
  print -P " k - Edit %Uks-mp4k%u config (%B${rel_size}/${vcodec}/${b_vcodec}/${acodec}/${b_acodec}/${default_lang_audio}%b)"
  source ${HOME}/.ks-tools/ks-mp4s
  print -P " s - Edit %Uks-mp4s%u config (%B${rel_size}/${vcodec}/${b_vcodec}/${acodec}/${b_acodec}/${default_lang_audio}%b)"
  source ${HOME}/.ks-tools/ks-avi
  print -P " a - Edit %Uks-avi%u config (%B${rel_size}/${vcodec}/${b_vcodec}/${acodec}/${b_acodec}/${default_lang_audio}%b)"
  source ${HOME}/.ks-tools/ks-av1
  print -P " v - Edit %Uks-av1%u config (%B${rel_size}/${vcodec}/${b_vcodec}/${acodec}/${b_acodec}/${default_lang_audio}%b)"
  source ${HOME}/.ks-tools/ks-av1s
  print -P " c - Edit %Uks-av1s%u config (%B${rel_size}/${vcodec}/${b_vcodec}/${acodec}/${b_acodec}/${default_lang_audio}%b)"
  print ""
  source ${HOME}/.ks-tools/ks-mp3
  print -P " p - Edit %Uks-mp3/ks-mp3-album%u config (%B${acodec}/${b_acodec}/${default_lang_audio}%b)"
  source ${HOME}/.ks-tools/ks-oga
  print -P " o - Edit %Uks-oga/ks-oga-album%u config (%B${acodec}/${b_acodec}/${default_lang_audio}%b)"
  print ""
  user_config=$(cat ${HOME}/.ks-tools/ks-upload-user 2> /dev/null)
  server_config=$(cat ${HOME}/.ks-tools/ks-upload-server 2> /dev/null)
  tool_config=$(cat ${HOME}/.ks-tools/ks-upload-tool 2> /dev/null)
  print -P " u - Edit %Uks-upv/ks-upa/ks-upf/ks-upr%u config (%B${user_config}/${server_config}/${tool_config}%b)"
  print ""
  print " q - Exit"
  print ""
  print -n "* Choose an option (m/k/s/a/p/o/u/q): " ; read option
  if [[ "${option}" == "m" ]] ; then
    edit_video_config ks-mp4
  elif [[ "${option}" == "k" ]] ; then
    edit_video_config ks-mp4k
  elif [[ "${option}" == "s" ]] ; then
    edit_video_config ks-mp4s
  elif [[ "${option}" == "a" ]] ; then
    edit_video_config ks-avi
  elif [[ "${option}" == "v" ]] ; then
    edit_video_config ks-av1
  elif [[ "${option}" == "c" ]] ; then
    edit_video_config ks-av1s
  elif [[ "${option}" == "p" ]] ; then
    edit_audio_config ks-mp3
  elif [[ "${option}" == "o" ]] ; then
    edit_audio_config ks-oga 
  elif [[ "${option}" == "u" ]] ; then
    ks-upv -e
  elif [[ "${option}" == "q" ]] ; then
    show_menu=1
    exit
  else
    print ""
    print "+ Invalid option"
    print -P -n "* Press %UENTER%u to return menu " ; read return
  fi
done
