#!/usr/bin/env zsh

setopt SH_WORD_SPLIT NO_NOMATCH

#################################################################################
# ks-mp4s-folder (ks-tools) - Convert videos from folder to MP4 format (Series) #
# Date: 24-09-2025                                                              #
# Author: dmesg00                                                               #
# Contact: dmesg00@duck.com                                                     #
#################################################################################
VERSION="9.5"
M_DATE="240925"

# Variables
tempFile="/tmp/ks-mp4s-folder.txt"
tempFileTest="/tmp/ks-mp4s-folder-test.txt"
formatFiles="mp4 avi mpg mpeg mov wmv mkv ogv webm rm flv vob ts"

# Check cygwin alias (for Windows)
if [[ -f "/usr/bin/cygwin-alias.zsh" ]] ; then
  setopt ALIASES
  source "/usr/bin/cygwin-alias.zsh"
fi

# Function for check dependencies
check_dependencies() {
  which_dependence=$(which ${1})
  error_dependence=$?
  if [[ -z "${which_dependence}" ]] || (( ${error_dependence} > 0 )); then
    print ""
    print "* ks-mp4s-folder (ks-tools) v${VERSION} (${M_DATE})"
    print ""
    print "* Dependency not found: ${1}"
    print ""
    exit 1
  fi 
}

# Check dependencies
dependencies="ffmpeg grep find grep cut head tail cat ks-utfs"
for scan_dependency in ${dependencies} ; do
  check_dependencies "${scan_dependency}"
done

# Show help when folder is empty
if [[ -z "${1}" ]] ; then
  print ""
  print "* ks-mp4s-folder (ks-tools) v${VERSION} (${M_DATE})"
  print ""
  print "\- Convert videos from folder to MP4 format (Series)"
  print ""
  print "+ Syntax: "
  print ""
  print "  $ ks-mp4s-folder </path/folder> [subs/widescreen/subs-widescreen]"
  print ""
  print " + Examples: "
  print "     $ ks-mp4s-folder /data/Westworld"
  print "     $ ks-mp4s-folder /data/Daredevil subs"
  print "     $ ks-mp4s-folder /data/Daredevil widescreen"
  print "     $ ks-mp4s-folder /data/Daredevil subs-widescreen"
  print ""
  print "* Notes:"
  print ""
  print " + The option 'subs' apply detection & rendering the forced subtitles."
  print " + You must not use spaces in folders and video files."
  print ""
  exit
fi

# Check if folder exist
if [[ -d "${1}" ]] ; then
  print null > /dev/null
else
  print ""
  print "* ks-mp4s-folder (ks-tools) v${VERSION} (${M_DATE})"
  print ""
  print "+ The folder '${1}' does not exist!"
  print ""
  exit
fi

# Scan videos files format
clear
print ""
print "* ks-mp4s-folder (ks-tools) v${VERSION} (${M_DATE})"
print ""
print "\- Convert videos from folder to MP4 format (Series)"
print ""
print -n "* Scanning ${1} "
print ""
rm -rf ${tempFile} && touch ${tempFile}
for format in ${formatFiles} ; do
  find "${1}"/*.${format} &> ${tempFileTest}
  if (( $? != 0 )) ; then
    print "null" > /dev/null
  else
    print "+ Video file(s) in .${format} found!"
    cd "${1}" && ls -1 *.${format} &> /tmp/tempFile.txt
    cat /tmp/tempFile.txt >> ${tempFile}
    rm -rf /tmp/tempFile.txt 2> /dev/null
    fail=0
  fi
done

# Init the conversion files
num_files=$(cat ${tempFile} | wc -l)
if (( num_files == 0 )) ; then
  print ""
  print "+ No video file(s) found in folder '${1}'"
  print ""
  exit
else
  print ""
  print "* Files to convert (${1}):"
  convert_files=1
  if [[ "${2}" == "subs" ]] ; then
    widescreen_enabled=0
    subtitles_enabled=1
    subtitles_show="with subtitles"
  elif [[ "${2}" == "widescreen" ]] ; then
    widescreen_enabled=1
    subtitles_enabled=0
    subtitles_show="without subtitles but forcing widescreen"
  elif [[ "${2}" == "subs-widescreen" ]] ; then
    widescreen_enabled=1
    subtitles_enabled=1
    subtitles_show="with subtitles and forcing widescreen"
  else
    widescreen_enabled=0
    subtitles_enabled=0
    subtitles_show="without subtitles"
  fi
  while (( convert_files <= num_files )) ; do
    show_file=$(cat ${tempFile} | head -${convert_files} | tail -1)
    print "  + ${show_file} (${subtitles_show})"
    convert_files=$(expr ${convert_files} + 1)
  done
  print ""
  print "* The output folder will be '${1}/to-mp4'"
  # Execute commands for conversion
  print ""
  print -n "* (Default: y) Do you want run the conversion? (y/n): " ; read run_commands_ffmpeg
  if [[ "${run_commands_ffmpeg}" == "n" ]] ; then
    exit
  else
    convert_files=1
    cd "${1}" && mkdir -p to-mp4 && rm -rf to-mp4/*
    while (( convert_files <= num_files )) ; do
      show_file=$(cat ${tempFile} | head -${convert_files} | tail -1)
      if (( subtitles_enabled == 1 )) ; then
        if (( widescreen_enabled == 1 )) ; then
          fname=$(print "${show_file}" | cut -d "." -f 1)
          ks-mp4s-wrapper --conv-with-sub-widescreen "${show_file}" "to-mp4/${fname}"
        else
          fname=$(print "${show_file}" | cut -d "." -f 1)
          ks-mp4s-wrapper --conv-with-sub "${show_file}" "to-mp4/${fname}"
        fi
      else
        if (( widescreen_enabled == 1 )) ; then
          fname=$(print "${show_file}" | cut -d "." -f 1)
          ks-mp4s-wrapper --conv-widescreen "${show_file}" "to-mp4/${fname}"
        else
          fname=$(print "${show_file}" | cut -d "." -f 1)
          ks-mp4s-wrapper --conv "${show_file}" "to-mp4/${fname}"
        fi
      fi
      convert_files=$(expr ${convert_files} + 1)
    done
  fi
fi
