#!/usr/bin/env zsh

setopt NO_NOMATCH

#################################################################################
# ks-mp4s-folder (ks-tools) - Convert videos from folder to MP4 format (Series) #
# Date: 24-09-2025                                                              #
# Author: dmesg00                                                               #
# Contact: dmesg00@duck.com                                                     #
#################################################################################
VERSION=("9.5")
M_DATE=("240925")

# Variables
tempFile=("/tmp/ks-mp4s-folder.txt")
tempFileTest=("/tmp/ks-mp4s-folder-test.txt")
formatFiles=(mp4 avi mpg mpeg mov wmv mkv ogv webm rm flv vob ts)

# Check cygwin alias (for Windows)
if [[ -f "/usr/bin/cygwin-alias.zsh" ]] ; then
  setopt ALIASES
  source "/usr/bin/cygwin-alias.zsh"
fi

# Function for check dependencies
check_dependencies() {
  which_dependence=$(which ${1})
  error_dependence=$?
  if [[ -z "${which_dependence}" ]] || (( ${error_dependence} > 0 )); then
    print ""
    print -P "* %Bks-mp4s-folder%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
    print ""
    print -P "* %BDependency not found%b: %U${1}%u"
    print ""
    exit 1
  fi 
}

# Check dependencies
dependencies=(ffmpeg grep find grep cut head tail cat ks-utfs ks-mp4s-wrapper)
for scan_dependency in "${dependencies[@]}" ; do
  check_dependencies "${scan_dependency}"
done

# Show help when folder is empty
if [[ -z "${1}" ]] ; then
  print ""
  print -P "* %Bks-mp4s-folder%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
  print ""
  print "\- Convert videos from folder to MP4 format (Series)"
  print ""
  print -P "+ %USyntax%u: "
  print ""
  print -P "  $ %Bks-mp4s-folder%b </path/folder> [subs/widescreen/subs-widescreen]"
  print ""
  print -P " + %UExamples%u: "
  print -P "     $ %Bks-mp4s-folder%b /data/Westworld"
  print -P "     $ %Bks-mp4s-folder%b /data/Daredevil subs"
  print -P "     $ %Bks-mp4s-folder%b /data/Daredevil widescreen"
  print -P "     $ %Bks-mp4s-folder%b /data/Daredevil subs-widescreen"
  print ""
  print -P "* %UNotes%u:"
  print ""
  print " + The option 'subs' apply detection & rendering the forced subtitles."
  print " + You must not use spaces in folders and video files."
  print ""
  exit
fi

# Check if folder exist
if [[ -d "${1}" ]] ; then
  print null > /dev/null
else
  print ""
  print -P "* %Bks-mp4s-folder%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
  print ""
  print -P "* The folder %U${1}%u does not exist!"
  print ""
  exit
fi

# Scan videos files format
clear
print ""
print -P "* %Bks-mp4s-folder%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
print ""
print "\- Convert videos from folder to MP4 format (Series)"
print ""
print -P -n "* Scanning %U${1}%u "
print ""
rm -rf ${tempFile} && touch ${tempFile}
for format in "${formatFiles[@]}" ; do
  find "${1}"/*.${format} &> ${tempFileTest}
  if (( $? != 0 )) ; then
    print "null" > /dev/null
  else
    print "+ Video file(s) in .${format} found!"
    cd "${1}" && ls -1 *.${format} &> /tmp/tempFile.txt
    cat /tmp/tempFile.txt >> ${tempFile}
    rm -rf /tmp/tempFile.txt 2> /dev/null
    fail=0
  fi
done

# Init the conversion files
num_files=$(cat ${tempFile} | wc -l)
if (( num_files == 0 )) ; then
  print ""
  print -P "+ No video file(s) found in folder %U${1}%u"
  print ""
  exit
else
  print ""
  print -P "* Files to convert:"
  convert_files=1
  if [[ "${2}" == "subs" ]] ; then
    widescreen_enabled=0
    subtitles_enabled=1
    subtitles_show=("with subtitles")
  elif [[ "${2}" == "widescreen" ]] ; then
    widescreen_enabled=1
    subtitles_enabled=0
    subtitles_show=("without subtitles but forcing widescreen")
  elif [[ "${2}" == "subs-widescreen" ]] ; then
    widescreen_enabled=1
    subtitles_enabled=1
    subtitles_show=("with subtitles and forcing widescreen")
  else
    widescreen_enabled=0
    subtitles_enabled=0
    subtitles_show=("without subtitles")
  fi
  while (( convert_files <= num_files )) ; do
    show_file=$(cat ${tempFile} | head -${convert_files} | tail -1)
    print -P "  + ${show_file} (%B${subtitles_show}%b)"
    convert_files=$(expr ${convert_files} + 1)
  done
  print ""
  print -P "* The output folder will be %U${1}/to-mp4%u"
  # Execute commands for conversion
  print ""
  print -P -n "* (Default: %By%b) Do you want run the conversion? (y/n): " ; read run_commands_ffmpeg
  if [[ "${run_commands_ffmpeg}" == "n" ]] ; then
    exit
  else
    convert_files=1
    cd "${1}" && mkdir -p to-mp4 && rm -rf to-mp4/*
    while (( convert_files <= num_files )) ; do
      show_file=$(cat ${tempFile} | head -${convert_files} | tail -1)
      if (( subtitles_enabled == 1 )) ; then
        if (( widescreen_enabled == 1 )) ; then
          fname=$(print "${show_file}" | cut -d "." -f 1)
          ks-mp4s-wrapper --conv-with-sub-widescreen "${show_file}" "to-mp4/${fname}"
        else
          fname=$(print "${show_file}" | cut -d "." -f 1)
          ks-mp4s-wrapper --conv-with-sub "${show_file}" "to-mp4/${fname}"
        fi
      else
        if (( widescreen_enabled == 1 )) ; then
          fname=$(print "${show_file}" | cut -d "." -f 1)
          ks-mp4s-wrapper --conv-widescreen "${show_file}" "to-mp4/${fname}"
        else
          fname=$(print "${show_file}" | cut -d "." -f 1)
          ks-mp4s-wrapper --conv "${show_file}" "to-mp4/${fname}"
        fi
      fi
      convert_files=$(expr ${convert_files} + 1)
    done
  fi
fi
