#!/usr/bin/env zsh

setopt NO_NOMATCH

#####################################################################
# ks-mix (ks-tools) - Extract video/audio and mix video/audio files #
# Date: 25-08-2026                                                  #
# Author: dmesg00                                                   #
# Contact: dmesg00@duck.com                                         #
#####################################################################
VERSION=("9.5")
M_DATE=("250826")

# Detect version ffmpeg for old releases
ffmpeg_version=$(ffmpeg -version 2>&1 | grep version | head -1 | cut -d " " -f 3 | cut -d "." -f 1)
ffmpeg_version=${ffmpeg_version//[^0-9]/}
ffmpeg_version=$(print ${ffmpeg_version} | cut -c 1-3)
if [[ -z "${ffmpeg_version}" ]] ; then
  video_sync=("fps_mode")
else
  if (( ${ffmpeg_version} < 5 )) 2> /dev/null ; then
    video_sync=("vsync")
  else
    video_sync=("fps_mode")
  fi
fi

# File(s) detection
current_dir=("$(pwd)")
video_file_dir=("${current_dir}/video.mkv")
audio_file_dir=("${current_dir}/audio.mka")
subs_file_dir=("${current_dir}/subs.srt")
output_file_dir=("${current_dir}/output.mkv")

# Language config
default_lang_audio=("spa")
default_lang_subt=("spa")

# Check cygwin alias (for Windows)
if [[ -f "/usr/bin/cygwin-alias.zsh" ]] ; then
  setopt ALIASES
  source "/usr/bin/cygwin-alias.zsh"
fi

# Function for check dependencies
check_dependencies() {
  which_dependence=$(which ${1})
  error_dependence=$?
  if [[ -z "${which_dependence}" ]] || (( ${error_dependence} > 0 )); then
    print ""
    print -P "* %Bks-mix%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
    print ""
    print -P "* %BDependency not found%b: %U${1}%u"
    print ""
    exit 1
  fi 
}

# Check dependencies
dependencies=(ffmpeg grep sed cut head tail tr ks-utfs)
for scan_dependency in "${dependencies[@]}" ; do
  check_dependencies "${scan_dependency}"
done

# Detect if video file exist
if [[ -f "${video_file_dir}" ]] ; then
  video_found=("FOUND")
else
  video_found=("NOT FOUND")
fi
# Detect if audio file exist
if [[ -f "${audio_file_dir}" ]] ; then
  audio_found=("FOUND")
else
  audio_found=("NOT FOUND")
fi
# Detect if audio file exist
if [[ -f "${subs_file_dir}" ]] ; then
  subs_found=("FOUND")
else
  subs_found=("NOT FOUND")
fi

# Function to show zero before numbers
zero_number() {
  if (( ${1} <= 9 )) ; then
    numberwithZero=$(print "0${1}")
  else
    numberwithZero=$(print "${1}")
  fi
  print "${numberwithZero}" | cut -c 1-2
}

# Function to show menu again when Syntax is wrong
show_menu() {
  print ""
  print -P "* %Bks-mix%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
  print ""
  print "\- Extract video/audio and mix video/audio files"
  print ""
  print -P " + %BCurrent dir%b: ${current_dir}"
  print -P " + %BVideo file%b: ${video_file_dir} %B(${video_found})%b"
  print -P " + %BAudio file%b: ${audio_file_dir} %B(${audio_found})%b"
  print -P " + %BSubs file%b: ${subs_file_dir} %B(${subs_found})%b"
  print ""
  print -P "+ %USyntax%u: "
  print ""
  print -P "  $ %Bks-mix%b -evid <video-file>  --> Extract video track"
  print -P "  $ %Bks-mix%b -ev25 <video-file>  --> Extract video track to 25 fps (H264/5 & MPEG4)"
  print -P "  $ %Bks-mix%b -evpf <video-file>  --> Extract video track & set fps (H264/5 & MPEG4)"
  print -P "  $ %Bks-mix%b -eaud <video-file>  --> Extract audio track"
  print -P "  $ %Bks-mix%b -esub <video-file>  --> Extract subtitle track (only for subrip/srt)"
  print -P "  $ %Bks-mix%b -evti <video-file>  --> Extract video from a specific hour/minute/second"
  print -P "  $ %Bks-mix%b -eati <video-file>  --> Extract audio from a specific hour/minute/second"
  print -P "  $ %Bks-mix%b -evat <video-file>  --> Extract video + audio from specific time"
  print -P "  $ %Bks-mix%b -frag <video-file>  --> Extract video + audio in specific time fragments"
  print -P "  $ %Bks-mix%b -chec <video-file>  --> Analyze tracks of video file"
  print -P "  $ %Bks-mix%b -mixf               --> Mix video and audio file"
  print -P "  $ %Bks-mix%b -mixs               --> Mix video, audio and subtitle file"
  print ""
  print -P " + %UExamples%u: "
  print -P "    %Bks-mix%b -evid /data/movies/Example.mkv"
  print -P "    %Bks-mix%b -eaud /data/movies/Example.avi"
  print ""
  exit
}

# Show menu and Syntax
if [[ -z "${1}" ]] ; then
  show_menu
elif [[ "${1}" == "-evid" ]] ; then
  # Run commands for -evid parameter
  if [[ -z "${2}" ]] ; then
    show_menu
  elif [[ -f "${2}" ]] ; then
    print ""
    print -P "+ %BVideo Tracks:%b"
    ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | cut -d "," -f 1
    print ""
    # Check de video track by default
    video_default=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
    if [[ -z "${video_default}" ]] ; then
      video_default=("0:0")
    else
      video_default_patch=$(print ${video_default} | cut -c4)
      if [[ "${video_default_patch}" == ":" ]] ; then
        video_default=$(print ${video_default} | cut -c1-3)
      else
        video_default=("${video_default}")
      fi
    fi
    # Ask for video
    print -P -n "* (Default: %B${video_default}%b) Type the number of video track: " ; read video_track
    if [[ -z "${video_track}" ]] ; then
      video_track=("${video_default}")
    else
      video_track=("${video_track}")
    fi
    print ""
    print -P -n "* Starting extract video track (%B${2}%b) "
    sleep 3
    ffmpeg -y -i "${2}" -map ${video_track} -c:v copy "${current_dir}/seeing.mp4"
    ffmpeg -y -i "${current_dir}/seeing.mp4" -map 0:0 -${video_sync} cfr -c:v copy "${video_file_dir}"
    print ""
    print -P -n "* Extracted video into %U${video_file_dir}%u"
    sleep 2
    rm -rf "${current_dir}/seeing.mp4"
    print "" && print ""
    exit
  else
    print ""
    print -P "* The file %U${2}%u does not exist"
    print ""
    exit
  fi
elif [[ "${1}" == "-ev25" ]] ; then
  # Run commands for -ev25 parameter
  if [[ -z "${2}" ]] ; then
    show_menu
  elif [[ -f "${2}" ]] ; then
    print ""
    print -P "+ %BVideo Tracks:%b"
    ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | cut -d "," -f 1
    print ""
    # Check de video track by default
    video_default=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
    if [[ -z "${video_default}" ]] ; then
      video_default=("0:0")
    else
      video_default_patch=$(print ${video_default} | cut -c4)
      if [[ "${video_default_patch}" == ":" ]] ; then
        video_default=$(print ${video_default} | cut -c1-3)
      else
        video_default=("${video_default}")
      fi
    fi
    # Ask for video
    print -P -n "* (Default: %B${video_default}%b) Type the number of video track: " ; read video_track
    if [[ -z "${video_track}" ]] ; then
      video_track=("${video_default}")
    else
      video_track=("${video_track}")
    fi
    print ""
    print -P -n "* Starting extract video track and change to 25 fps (%B${2}%b) "
    sleep 3
    print "" && print ""
    # Check if video input uses H265 (HEVC)
    codec_h265=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | grep "h265")
    codec_hevc=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | grep "hevc")
    yuv420p10le=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | grep "yuv420p10le")
    hevc_main10=$("${p_ffmpeg[@]}" "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | grep "Main 10")
    codec_h265_hevc=("${codec_h265}${codec_hevc}${yuv420p10le}")
    hevc_hdr_bt=$("${p_ffmpeg[@]}" "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | grep "bt2020")
    hevc_hdr_smp=$("${p_ffmpeg[@]}" "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | grep "smpte2084")
    hevc_hdr=("${hevc_hdr_bt}${hevc_hdr_smp}")
    # Check if video input uses MPEG4/XVID
    codec_mpeg4=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | grep "mpeg4")
    codec_xvid=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | grep "xvid")
    codec_mpeg4_xvid=("${codec_mpeg4}${codec_xvid}")
    if [[ -z "${codec_h265_hevc}" ]] ; then
      if [[ -z "${codec_mpeg4_xvid}" ]] ; then
        codec_encoded=("h264_encoded")
      else
        codec_encoded=("mpeg4_encoded")
      fi
    else
      if [[ -z "${hevc_hdr}" ]] ; then
        codec_encoded=("h265_encoded")
      else
        codec_encoded=("h265_encoded_hdr")
      fi
    fi
    # Extract video with diferent codecs
    if [[ "${codec_encoded}" == "h264_encoded" ]] ; then
      ffmpeg -y -i "${2}" -map ${video_track} -c copy -f h264 "${current_dir}/seeing_noaudio.h264"
      ffmpeg -y -r 25 -i "${current_dir}/seeing_noaudio.h264" -c copy "${current_dir}/seeing.mp4"
      ffmpeg -y -i "${current_dir}/seeing.mp4" -map 0:0 -${video_sync} cfr -c:v copy "${video_file_dir}"
      print ""
      print -P -n "* Extracted video into %U${video_file_dir}%u (25 fps)"
      sleep 2
      rm -rf "${current_dir}/seeing_noaudio.h264"
      rm -rf "${current_dir}/seeing.mp4"
      print "" && print ""
      exit
    elif [[ "${codec_encoded}" == "h265_encoded" ]] ; then
      ffmpeg -y -i "${2}" -map ${video_track} -c:v libx264 -profile:v high -pix_fmt yuv420p -b:v 3500k -preset medium "${current_dir}/temp-h265.mkv"
      ffmpeg -y -i "${current_dir}/temp-h265.mkv" -c copy -f h264 "${current_dir}/seeing_noaudio.h264"
      rm -rf "${current_dir}/temp-h265.mkv"
      ffmpeg -y -r 25 -i "${current_dir}/seeing_noaudio.h264" -c copy "${current_dir}/seeing.mp4"
      ffmpeg -y -i "${current_dir}/seeing.mp4" -map 0:0 -${video_sync} cfr -c:v copy "${video_file_dir}"
      print ""
      print -P -n "* Extracted video into %U${video_file_dir}%u (25 fps)"
      sleep 2
      rm -rf "${current_dir}/seeing_noaudio.h264"
      rm -rf "${current_dir}/seeing.mp4"
      print "" && print ""
      exit
    elif [[ "${codec_encoded}" == "h265_encoded_hdr" ]] ; then
      ffmpeg -y -i "${2}" -map ${video_track} -c:v libx264 -vf zscale=t=linear:npl=100,format=gbrpf32le,zscale=p=bt709,tonemap=tonemap=hable:desat=0,zscale=t=bt709:m=bt709:r=tv -profile:v high -pix_fmt yuv420p -b:v 3500k -preset medium "${current_dir}/temp-h265.mkv"
      ffmpeg -y -i "${current_dir}/temp-h265.mkv" -c copy -f h264 "${current_dir}/seeing_noaudio.h264"
      rm -rf "${current_dir}/temp-h265.mkv"
      ffmpeg -y -r 25 -i "${current_dir}/seeing_noaudio.h264" -c copy "${current_dir}/seeing.mp4"
      ffmpeg -y -i "${current_dir}/seeing.mp4" -map 0:0 -${video_sync} cfr -c:v copy "${video_file_dir}"
      print ""
      print -P -n "* Extracted video into %U${video_file_dir}%u (25 fps)"
      sleep 2
      rm -rf "${current_dir}/seeing_noaudio.h264"
      rm -rf "${current_dir}/seeing.mp4"
      print "" && print ""
      exit
    elif [[ "${codec_encoded}" == "mpeg4_encoded" ]] ; then
      ffmpeg -y -i "${2}" -map ${video_track} -c:v libx264 -profile:v high -b:v 4000k -preset medium "${current_dir}/temp-mpeg4.mkv"
      ffmpeg -y -i "${current_dir}/temp-mpeg4.mkv" -c copy -f h264 "${current_dir}/seeing_noaudio.h264"
      rm -rf "${current_dir}/temp-mpeg4.mkv"
      ffmpeg -y -r 25 -i "${current_dir}/seeing_noaudio.h264" -c copy "${current_dir}/seeing.mp4"
      ffmpeg -y -i "${current_dir}/seeing.mp4" -map 0:0 -${video_sync} cfr -c:v copy "${video_file_dir}"
      print ""
      print -P -n "* Extracted video into %U${video_file_dir}%u (25 fps)"
      sleep 2
      rm -rf "${current_dir}/seeing_noaudio.h264"
      rm -rf "${current_dir}/seeing.mp4"
      print "" && print ""
      exit
    fi
  else
    print ""
    print -P "* The file %U${2}%u does not exist"
    print ""
    exit
  fi
elif [[ "${1}" == "-evpf" ]] ; then
  # Run commands for -evpf parameter
  if [[ -z "${2}" ]] ; then
    show_menu
  elif [[ -f "${2}" ]] ; then
    print ""
    print -P "+ %BVideo Tracks:%b"
    ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | cut -d "," -f 1
    print ""
    # Check de video track by default
    video_default=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
    if [[ -z "${video_default}" ]] ; then
      video_default=("0:0")
    else
      video_default_patch=$(print ${video_default} | cut -c4)
      if [[ "${video_default_patch}" == ":" ]] ; then
        video_default=$(print ${video_default} | cut -c1-3)
      else
        video_default=("${video_default}")
      fi
    fi
    # Ask for video
    print -P -n "* (Default: %B${video_default}%b) Type the number of video track: " ; read video_track
    if [[ -z "${video_track}" ]] ; then
      video_track=("${video_default}")
    else
      video_track=("${video_track}")
    fi
    frames_default=("25")
    print -P -n "* (Default: %B${frames_default}%b) Set fps to change: " ; read frames_change
    if [[ -z "${frames_change}" ]] ; then
      frames_default=${frames_default}
    else
      frames_default=${frames_change}
    fi
    print ""
    print -P -n "* Starting extract video track and change to ${frames_default} fps (%B${2}%b) "
    sleep 3
    print "" && print ""
    # Check if video input uses H265 (HEVC)
    codec_h265=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | grep "h265")
    codec_hevc=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | grep "hevc")
    yuv420p10le=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | grep "yuv420p10le")
    hevc_main10=$("${p_ffmpeg[@]}" "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | grep "Main 10")
    hevc_profile_10bit=("${yuv420p10le}${hevc_main10}")
    codec_h265_hevc=("${codec_h265}${codec_hevc}${yuv420p10le}")
    hevc_hdr_bt=$("${p_ffmpeg[@]}" "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | grep "bt2020")
    hevc_hdr_smp=$("${p_ffmpeg[@]}" "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | grep "smpte2084")
    hevc_hdr=("${hevc_hdr_bt}${hevc_hdr_smp}")
    # Check if video input uses MPEG4/XVID
    codec_mpeg4=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | grep "mpeg4")
    codec_xvid=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | grep "xvid")
    codec_mpeg4_xvid=("${codec_mpeg4}${codec_xvid}")
    if [[ -z "${codec_h265_hevc}" ]] ; then
      if [[ -z "${codec_mpeg4_xvid}" ]] ; then
        codec_encoded=("h264_encoded")
      else
        codec_encoded=("mpeg4_encoded")
      fi
    else
      if [[ -z "${hevc_hdr}" ]] ; then
        codec_encoded=("h265_encoded")
      else
        codec_encoded=("h265_encoded_hdr")
      fi
    fi
    # Extract video with diferent codecs
    if [[ "${codec_encoded}" == "h264_encoded" ]] ; then
      ffmpeg -y -i "${2}" -map ${video_track} -c copy -f h264 "${current_dir}/seeing_noaudio.h264"
      ffmpeg -y -r ${frames_default} -i "${current_dir}/seeing_noaudio.h264" -c copy "${current_dir}/seeing.mp4"
      ffmpeg -y -i "${current_dir}/seeing.mp4" -map 0:0 -${video_sync} cfr -c:v copy "${video_file_dir}"
      print ""
      print -P -n "* Extracted video into %U${video_file_dir}%u (25 fps)"
      sleep 2
      rm -rf "${current_dir}/seeing_noaudio.h264"
      rm -rf "${current_dir}/seeing.mp4"
      print "" && print ""
      exit
    elif [[ "${codec_encoded}" == "h265_encoded" ]] ; then
      ffmpeg -y -i "${2}" -map ${video_track} -c:v libx264 -profile:v high -pix_fmt yuv420p -b:v 3500k -preset medium "${current_dir}/temp-h265.mkv"
      ffmpeg -y -i "${current_dir}/temp-h265.mkv" -c copy -f h264 "${current_dir}/seeing_noaudio.h264"
      rm -rf "${current_dir}/temp-h265.mkv"
      ffmpeg -y -r ${frames_default} -i "${current_dir}/seeing_noaudio.h264" -c copy "${current_dir}/seeing.mp4"
      ffmpeg -y -i "${current_dir}/seeing.mp4" -map 0:0 -${video_sync} cfr -c:v copy "${video_file_dir}"
      print ""
      print -P -n "* Extracted video into %U${video_file_dir}%u (25 fps)"
      sleep 2
      rm -rf "${current_dir}/seeing_noaudio.h264"
      rm -rf "${current_dir}/seeing.mp4"
      print "" && print ""
      exit
    elif [[ "${codec_encoded}" == "h265_encoded_hdr" ]] ; then
      ffmpeg -y -i "${2}" -map ${video_track} -c:v libx264 vf zscale=t=linear:npl=100,format=gbrpf32le,zscale=p=bt709,tonemap=tonemap=hable:desat=0,zscale=t=bt709:m=bt709:r=tv -profile:v high -pix_fmt yuv420p -b:v 3500k -preset medium "${current_dir}/temp-h265.mkv"
      ffmpeg -y -i "${current_dir}/temp-h265.mkv" -c copy -f h264 "${current_dir}/seeing_noaudio.h264"
      rm -rf "${current_dir}/temp-h265.mkv"
      ffmpeg -y -r 25 -i "${current_dir}/seeing_noaudio.h264" -c copy "${current_dir}/seeing.mp4"
      ffmpeg -y -i "${current_dir}/seeing.mp4" -map 0:0 -${video_sync} cfr -c:v copy "${video_file_dir}"
      print ""
      print -P -n "* Extracted video into %U${video_file_dir}%u (25 fps)"
      sleep 2
      rm -rf "${current_dir}/seeing_noaudio.h264"
      rm -rf "${current_dir}/seeing.mp4"
      print "" && print ""
      exit
    elif [[ "${codec_encoded}" == "mpeg4_encoded" ]] ; then
      ffmpeg -y -i "${2}" -map ${video_track} -c:v libx264 -profile:v high -b:v 4000k -preset medium "${current_dir}/temp-mpeg4.mkv"
      ffmpeg -y -i "${current_dir}/temp-mpeg4.mkv" -c copy -f h264 "${current_dir}/seeing_noaudio.h264"
      rm -rf "${current_dir}/temp-mpeg4.mkv"
      ffmpeg -y -r ${frames_default} -i "${current_dir}/seeing_noaudio.h264" -c copy "${current_dir}/seeing.mp4"
      ffmpeg -y -i "${current_dir}/seeing.mp4" -map 0:0 -${video_sync} cfr -c:v copy "${video_file_dir}"
      print ""
      print -P -n "* Extracted video into %U${video_file_dir}%u (25 fps)"
      sleep 2
      rm -rf "${current_dir}/seeing_noaudio.h264"
      rm -rf "${current_dir}/seeing.mp4"
      print "" && print ""
      exit
    fi
  else
    print ""
    print -P "* The file %U${2}%u does not exist"
    print ""
    exit
  fi
elif [[ "${1}" == "-eaud" ]] ; then
  # Run commands for -eaud parameter
  if [[ -z "${2}" ]] ; then
    show_menu
  elif [[ -f "${2}" ]] ; then
    print ""
    print -P "+ %BAudio Tracks:%b"
    ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | cut -d "," -f 1
    print ""
    # Check the audio track by default
    audio_default=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | grep "(${default_lang_audio})" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
    if [[ -z "${audio_default}" ]] ; then
      audio_default=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
      if [[ -z "${audio_default}" ]] ; then
        audio_default=("0:1")
      else
        audio_default_patch=$(print ${audio_default} | cut -c4)
        if [[ "${audio_default_patch}" == ":" ]] ; then
          audio_default=$(print ${audio_default} | cut -c1-3)
        else
          audio_default=("${audio_default}")
        fi
      fi
    else
      audio_default_patch=$(print ${audio_default} | cut -c4)
      if [[ "${audio_default_patch}" == ":" ]] ; then
        audio_default=$(print ${audio_default} | cut -c1-3)
      else
        audio_default=("${audio_default}")
      fi
    fi
    # Ask for audio
    print -P -n "* (Default: %B${audio_default}%b) Type the number of audio track: " ; read audio_track
    if [[ -z "${audio_track}" ]] ; then
      audio_track=("${audio_default}")
    else
      audio_track=("${audio_track}")
    fi
    print ""
    print -P -n "* Starting extract audio track (%B${2}%b) "
    sleep 3
    ffmpeg -y -i "${2}" -map ${audio_track} -c:a copy "${audio_file_dir}"
    print ""
    print -P -n "* Extracted audio into %U${audio_file_dir}%u"
    sleep 2
    print "" && print ""
    exit
  else
    print ""
    print -P "* The file %U${2}%u does not exist"
    print ""
    exit
  fi
elif [[ "${1}" == "-esub" ]] ; then
  # Run commands for -esub parameter
  if [[ -z "${2}" ]] ; then
    show_menu
  elif [[ -f "${2}" ]] ; then
    print ""
    print -P "+ %BSubtitle Tracks:%b"
    ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Subtitle:" | cut -d "," -f 1
    print ""
    # Check the subtitle track by default
    subtitle_default=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Subtitle:" | grep "(${default_lang_subt})" | grep "(forced)" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
    if [[ -z "${subtitle_default}" ]] ; then
      subtitle_default=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Subtitle:" | grep "(${default_lang_subt})" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
      if [[ -z "${subtitle_default}" ]] ; then
        subtitle_default=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Subtitle:" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
        if [[ -z "${subtitle_default}" ]] ; then
          subtitle_default=("0:3")
        else
          subtitle_default_patch=$(print ${subtitle_default} | cut -c4)
          if [[ "${subtitle_default_patch}" == ":" ]] ; then
            subtitle_default=$(print ${subtitle_default} | cut -c1-3)
          else
            subtitle_default=("${subtitle_default}")
          fi
        fi
      else
        subtitle_default_patch=$(print ${subtitle_default} | cut -c4)
        if [[ "${subtitle_default_patch}" == ":" ]] ; then
          subtitle_default=$(print ${subtitle_default} | cut -c1-3)
        else
          subtitle_default=("${subtitle_default}")
        fi
      fi
    else
      subtitle_default_patch=$(print ${subtitle_default} | cut -c4)
      if [[ "${subtitle_default_patch}" == ":" ]] ; then
        subtitle_default=$(print ${subtitle_default} | cut -c1-3)
      else
        subtitle_default=("${subtitle_default}")
      fi
    fi
    # Ask for subtitle
    print -P -n "* (Default: %B${subtitle_default}%b) Type the number of subtitle track: " ; read subtitle_track
    if [[ -z "${subtitle_track}" ]] ; then
      subtitle_track=("${subtitle_default}")
    else
      subtitle_track=("${subtitle_track}")
    fi
    print ""
    print -P -n "* Starting extract subtitles track (%B${2}%b) "
    sleep 3
    ffmpeg -y -i "${2}" -map ${subtitle_track} -c:s copy "${subs_file_dir}"
    ks-utfs "${subs_file_dir}"
    print ""
    print -P -n "* Extracted subtitles into %U${subs_file_dir}%u"
    sleep 2
    print "" && print ""
    exit
  else
    print ""
    print -P "* The file %U${2}%u does not exist"
    print ""
    exit
  fi
elif [[ "${1}" == "-evti" ]] ; then
  # Run commands for -evti parameter
  if [[ -z "${2}" ]] ; then
    show_menu
  elif [[ -f "${2}" ]] ; then
    hourCut=0
    minuteCut=1
    secondCut=0
    print ""
    print -P "+ %BVideo Tracks:%b"
    ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | cut -d "," -f 1
    print ""
    print "+ Video time:"
    ffmpeg -i "${2}" 2>&1 | grep "Duration" | cut -d "," -f 1 | tr -s " "
    print ""
    # Check de video track by default
    video_default=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
    if [[ -z "${video_default}" ]] ; then
      video_default=("0:0")
    else
      video_default_patch=$(print ${video_default} | cut -c4)
      if [[ "${video_default_patch}" == ":" ]] ; then
        video_default=$(print ${video_default} | cut -c1-3)
      else
        video_default=("${video_default}")
      fi
    fi
    # Ask for video
    print -P -n "* (Default: %B${video_default}%b) Type the number of video track: " ; read video_track
    if [[ -z "${video_track}" ]] ; then
      video_track=("${video_default}")
    else
      video_track=("${video_track}")
    fi
    # Ask for hour to cut
    valid_time=0
    while (( valid_time == 0 )) ; do
      print -P -n "* (Default: %B${hourCut}%b) Type the hour (0-99): " ; read hour_cut
      expr 1 + ${hour_cut} &> /dev/null
      error_time=$?
      if [[ -z "${hour_cut}" ]] ; then
        hourZero=$(zero_number "${hourCut}")
        hourCut=("${hourZero}")
        valid_time=1
      else
        if (( error_time == 0 )) ; then
          if (( hour_cut <= 99 )) ; then
            hourZero=$(zero_number "${hour_cut}")
            hourCut=("${hourZero}")
            valid_time=1
          else
            print "+ Only numbers from 0 to 99 are allowed"
          fi
        else
          print "+ Only numbers are allowed (0-99)"
        fi
      fi
    done
    # Ask for minute to cut
    valid_time=0
    while (( valid_time == 0 )) ; do
      print -P -n "* (Default: %B${minuteCut}%b) Type the minute (0-59): " ; read minute_cut
      expr 1 + ${minute_cut} &> /dev/null
      error_time=$?
      if [[ -z "${minute_cut}" ]] ; then
        minuteZero=$(zero_number "${minuteCut}")
        minuteCut=("${minuteZero}")
        valid_time=1
      else
        if (( error_time == 0 )) ; then
          if (( minute_cut <= 59 )) ; then
            minuteZero=$(zero_number "${minute_cut}")
            minuteCut=("${minuteZero}")
            valid_time=1
          else
            print "+ Only numbers from 0 to 59 are allowed"
          fi
        else
          print "+ Only numbers are allowed (0-59)"
        fi
      fi
    done
    # Ask for second to cut
    valid_time=0
    while (( valid_time == 0 )) ; do
      print -P -n "* (Default: %B${secondCut}%b) Type the second (0-59): " ; read second_cut
      expr 1 + ${second_cut} &> /dev/null
      error_time=$?
      if [[ -z "${second_cut}" ]] ; then
        secondZero=$(zero_number "${secondCut}")
        secondCut=("${secondZero}")
        valid_time=1
      else
        if (( error_time == 0 )) ; then
          if (( second_cut <= 59 )) ; then
            secondZero=$(zero_number "${second_cut}")
            secondCut=("${secondZero}")
            valid_time=1
          else
            print "+ Only numbers from 0 to 59 are allowed"
          fi
        else
          print "+ Only numbers are allowed (0-59)"
        fi
      fi
    done
    print -P -n "* (Default: %Bn%b) Extract video from ${hourCut}:${minuteCut}:${secondCut} to end? (y/n): " ; read accept_extraction
    if [[ "${accept_extraction}" == "y" ]] ; then
      print ""
      print -P -n "* Starting extract video track (%B${2}%b) "
      sleep 3
      ffmpeg -y -i "${2}" -map ${video_track} -c:v copy -ss ${hourCut}:${minuteCut}:${secondCut} "${current_dir}/seeing.mp4"
      ffmpeg -y -i "${current_dir}/seeing.mp4" -map 0:0 -${video_sync} cfr -c:v copy "${video_file_dir}"
      print ""
      print -P -n "* Extracted video into %U${video_file_dir}%u"
      sleep 2
      rm -rf "${current_dir}/seeing.mp4"
      print "" && print ""
      exit
    else
      hourCutAfter=0
      minuteCutAfter=10
      secondCutAfter=0
      # Ask for hour to cut
      print ""
      valid_time=0
      while (( valid_time == 0 )) ; do
        print -P -n "* (Default: %B${hourCutAfter}%b) Type how many hours from ${hourCut}:${minuteCut}:${secondCut} (0-99): " ; read hour_cutAfter
        expr 1 + ${hour_cutAfter} &> /dev/null
        error_time=$?
        if [[ -z "${hour_cutAfter}" ]] ; then
          hourZeroAfter=$(zero_number "${hourCutAfter}")
          hourCutAfter=("${hourZeroAfter}")
          valid_time=1
        else
          if (( error_time == 0 )) ; then
            if (( hour_cutAfter <= 99 )) ; then
              hourZeroAfter=$(zero_number "${hour_cutAfter}")
              hourCutAfter=("${hourZeroAfter}")
              valid_time=1
            else
              print "+ Only numbers from 0 to 99 are allowed"
            fi
          else
            print "+ Only numbers are allowed (0-99)"
          fi
        fi
      done
      # Ask for minute to cut
      valid_time=0
      while (( valid_time == 0 )) ; do
        print -P -n "* (Default: %B${minuteCutAfter}%b) Type how many minutes from ${hourCut}:${minuteCut}:${secondCut} (0-59): " ; read minute_cutAfter
        expr 1 + ${minute_cutAfter} &> /dev/null
        error_time=$?
        if [[ -z "${minute_cutAfter}" ]] ; then
          minuteZeroAfter=$(zero_number "${minuteCutAfter}")
          minuteCutAfter=("${minuteZeroAfter}")
          valid_time=1
        else
          if (( error_time == 0 )) ; then
            if (( minute_cutAfter <= 59 )) ; then
              minuteZeroAfter=$(zero_number "${minute_cutAfter}")
              minuteCutAfter=("${minuteZeroAfter}")
              valid_time=1
            else
              print "+ Only numbers from 0 to 59 are allowed"
            fi
          else
            print "+ Only numbers are allowed (0-59)"
          fi
        fi
      done
      # Ask for second to cut
      valid_time=0
      while (( valid_time == 0 )) ; do
        print -P -n "* (Default: %B${secondCutAfter}%b) Type how many seconds from ${hourCut}:${minuteCut}:${secondCut} (0-59): " ; read second_cutAfter
        expr 1 + ${second_cutAfter} &> /dev/null
        error_time=$?
        if [[ -z "${second_cutAfter}" ]] ; then
          secondZeroAfter=$(zero_number "${secondCutAfter}")
          secondCutAfter=("${secondZeroAfter}")
          valid_time=1
        else
          if (( error_time == 0 )) ; then
            if (( second_cutAfter <= 59 )) ; then
              secondZeroAfter=$(zero_number "${second_cutAfter}")
              secondCutAfter=("${secondZeroAfter}")
              valid_time=1
            else
              print "+ Only numbers from 0 to 59 are allowed"
            fi
          else
            print "+ Only numbers are allowed (0-59)"
          fi
        fi
      done
      hourPlusRaw=$(expr ${hourCut} + ${hourCutAfter})
      minutePlusRaw=$(expr ${minuteCut} + ${minuteCutAfter})
      secondPlusRaw=$(expr ${secondCut} + ${secondCutAfter})
      # Adjust time to display correctly
      if (( secondPlusRaw >= 60 )) ; then
        newSecondPlusRaw=$(expr ${secondPlusRaw} - 60)
        secondPlusRaw=${newSecondPlusRaw}
        minutePlusRaw=$(expr ${minutePlusRaw} + 1)
      fi
      if (( minutePlusRaw >= 60 )) ; then
        newMinutePlusRaw=$(expr ${minutePlusRaw} - 60)
        minutePlusRaw=${newMinutePlusRaw}
        hourPlusRaw=$(expr ${hourPlusRaw} + 1)
      fi
      # Convert time total
      hourPlus=$(zero_number "${hourPlusRaw}")
      minutePlus=$(zero_number "${minutePlusRaw}")
      secondPlus=$(zero_number "${secondPlusRaw}")
      print -P -n "* (Default: %By%b) Extract video from ${hourCut}:${minuteCut}:${secondCut} to ${hourPlus}:${minutePlus}:${secondPlus}? (y/n): " ; read accept_extraction_advanced
      if [[ "${accept_extraction_advanced}" == "n" ]] ; then
        exit
      else
        print ""
        print -P -n "* Starting extract video track (%B${2}%b) "
        sleep 3
        ffmpeg -y -i "${2}" -map ${video_track} -c:v copy -ss ${hourCut}:${minuteCut}:${secondCut} -t ${hourCutAfter}:${minuteCutAfter}:${secondCutAfter} "${current_dir}/seeing.mp4"
        ffmpeg -y -i "${current_dir}/seeing.mp4" -map 0:0 -${video_sync} cfr -c:v copy "${video_file_dir}"
        print ""
        print -P -n "* Extracted video into %U${video_file_dir}%u"
        sleep 2
        rm -rf "${current_dir}/seeing.mp4"
        print "" && print ""
        exit
      fi
    fi
  else
    print ""
    print -P "* The file %U${2}%u does not exist"
    print ""
    exit
  fi
elif [[ "${1}" == "-eati" ]] ; then
  # Run commands for -eati parameter
  if [[ -z "${2}" ]] ; then
    show_menu
  elif [[ -f "${2}" ]] ; then
    hourCut=0
    minuteCut=1
    secondCut=0
    print ""
    print -P "+ %BAudio Tracks:%b"
    ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | cut -d "," -f 1
    print ""
    print "+ Audio time:"
    ffmpeg -i "${2}" 2>&1 | grep "Duration" | cut -d "," -f 1 | tr -s " "
    print ""
    # Check the audio track by default
    audio_default=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | grep "(${default_lang_audio})" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
    if [[ -z "${audio_default}" ]] ; then
      audio_default=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
      if [[ -z "${audio_default}" ]] ; then
        audio_default=("0:1")
      else
        audio_default_patch=$(print ${audio_default} | cut -c4)
        if [[ "${audio_default_patch}" == ":" ]] ; then
          audio_default=$(print ${audio_default} | cut -c1-3)
        else
          audio_default=("${audio_default}")
        fi
      fi
    else
      audio_default_patch=$(print ${audio_default} | cut -c4)
      if [[ "${audio_default_patch}" == ":" ]] ; then
        audio_default=$(print ${audio_default} | cut -c1-3)
      else
        audio_default=("${audio_default}")
      fi
    fi
    # Ask for audio
    print -P -n "* (Default: %B${audio_default}%b) Type the number of audio track: " ; read audio_track
    if [[ -z "${audio_track}" ]] ; then
      audio_track=("${audio_default}")
    else
      audio_track=("${audio_track}")
    fi
    # Ask for hour to cut
    valid_time=0
    while (( valid_time == 0 )) ; do
      print -P -n "* (Default: %B${hourCut}%b) Type the hour (0-99): " ; read hour_cut
      expr 1 + ${hour_cut} &> /dev/null
      error_time=$?
      if [[ -z "${hour_cut}" ]] ; then
        hourZero=$(zero_number "${hourCut}")
        hourCut=("${hourZero}")
        valid_time=1
      else
        if (( error_time == 0 )) ; then
          if (( hour_cut <= 99 )) ; then
            hourZero=$(zero_number "${hour_cut}")
            hourCut=("${hourZero}")
            valid_time=1
          else
            print "+ Only numbers from 0 to 99 are allowed"
          fi
        else
          print "+ Only numbers are allowed (0-99)"
        fi
      fi
    done
    # Ask for minute to cut
    valid_time=0
    while (( valid_time == 0 )) ; do
      print -P -n "* (Default: %B${minuteCut}%b) Type the minute (0-59): " ; read minute_cut
      expr 1 + ${minute_cut} &> /dev/null
      error_time=$?
      if [[ -z "${minute_cut}" ]] ; then
        minuteZero=$(zero_number "${minuteCut}")
        minuteCut=("${minuteZero}")
        valid_time=1
      else
        if (( error_time == 0 )) ; then
          if (( minute_cut <= 59 )) ; then
            minuteZero=$(zero_number "${minute_cut}")
            minuteCut=("${minuteZero}")
            valid_time=1
          else
            print "+ Only numbers from 0 to 59 are allowed"
          fi
        else
          print "+ Only numbers are allowed (0-59)"
        fi
      fi
    done
    # Ask for second to cut
    valid_time=0
    while (( valid_time == 0 )) ; do
      print -P -n "* (Default: %B${secondCut}%b) Type the second (0-59): " ; read second_cut
      expr 1 + ${second_cut} &> /dev/null
      error_time=$?
      if [[ -z "${second_cut}" ]] ; then
        secondZero=$(zero_number "${secondCut}")
        secondCut=("${secondZero}")
        valid_time=1
      else
        if (( error_time == 0 )) ; then
          if (( second_cut <= 59 )) ; then
            secondZero=$(zero_number "${second_cut}")
            secondCut=("${secondZero}")
            valid_time=1
          else
            print "+ Only numbers from 0 to 59 are allowed"
          fi
        else
          print "+ Only numbers are allowed (0-59)"
        fi
      fi
    done
    print -P -n "* (Default: %Bn%b) Extract audio from ${hourCut}:${minuteCut}:${secondCut} to end? (y/n): " ; read accept_extraction
    if [[ "${accept_extraction}" == "y" ]] ; then
      print ""
      print -P -n "* Starting extract audio track (%B${2}%b) "
      sleep 3
      ffmpeg -y -i "${2}" -map ${audio_track} -c:a copy -ss ${hourCut}:${minuteCut}:${secondCut} "${audio_file_dir}"
      print ""
      print -P -n "* Extracted audio into %U${audio_file_dir}%u"
      sleep 2
      print "" && print ""
      exit
    else
      hourCutAfter=0
      minuteCutAfter=10
      secondCutAfter=0
      # Ask for hour to cut
      print ""
      valid_time=0
      while (( valid_time == 0 )) ; do
        print -P -n "* (Default: %B${hourCutAfter}%b) Type how many hours from ${hourCut}:${minuteCut}:${secondCut} (0-99): " ; read hour_cutAfter
        expr 1 + ${hour_cutAfter} &> /dev/null
        error_time=$?
        if [[ -z "${hour_cutAfter}" ]] ; then
          hourZeroAfter=$(zero_number "${hourCutAfter}")
          hourCutAfter=("${hourZeroAfter}")
          valid_time=1
        else
          if (( error_time == 0 )) ; then
            if (( hour_cutAfter <= 99 )) ; then
              hourZeroAfter=$(zero_number "${hour_cutAfter}")
              hourCutAfter=("${hourZeroAfter}")
              valid_time=1
            else
              print "+ Only numbers from 0 to 99 are allowed"
            fi
          else
            print "+ Only numbers are allowed (0-99)"
          fi
        fi
      done
      # Ask for minute to cut
      valid_time=0
      while (( valid_time == 0 )) ; do
        print -P -n "* (Default: %B${minuteCutAfter}%b) Type how many minutes from ${hourCut}:${minuteCut}:${secondCut} (0-59): " ; read minute_cutAfter
        expr 1 + ${minute_cutAfter} &> /dev/null
        error_time=$?
        if [[ -z "${minute_cutAfter}" ]] ; then
          minuteZeroAfter=$(zero_number "${minuteCutAfter}")
          minuteCutAfter=("${minuteZeroAfter}")
          valid_time=1
        else
          if (( error_time == 0 )) ; then
            if (( minute_cutAfter <= 59 )) ; then
              minuteZeroAfter=$(zero_number "${minute_cutAfter}")
              minuteCutAfter=("${minuteZeroAfter}")
              valid_time=1
            else
              print "+ Only numbers from 0 to 59 are allowed"
            fi
          else
            print "+ Only numbers are allowed (0-59)"
          fi
        fi
      done
      # Ask for second to cut
      valid_time=0
      while (( valid_time == 0 )) ; do
        print -P -n "* (Default: %B${secondCutAfter}%b) Type how many seconds from ${hourCut}:${minuteCut}:${secondCut} (0-59): " ; read second_cutAfter
        expr 1 + ${second_cutAfter} &> /dev/null
        error_time=$?
        if [[ -z "${second_cutAfter}" ]] ; then
          secondZeroAfter=$(zero_number "${secondCutAfter}")
          secondCutAfter=("${secondZeroAfter}")
          valid_time=1
        else
          if (( error_time == 0 )) ; then
            if (( second_cutAfter <= 59 )) ; then
              secondZeroAfter=$(zero_number "${second_cutAfter}")
              secondCutAfter=("${secondZeroAfter}")
              valid_time=1
            else
              print "+ Only numbers from 0 to 59 are allowed"
            fi
          else
            print "+ Only numbers are allowed (0-59)"
          fi
        fi
      done
      hourPlusRaw=$(expr ${hourCut} + ${hourCutAfter})
      minutePlusRaw=$(expr ${minuteCut} + ${minuteCutAfter})
      secondPlusRaw=$(expr ${secondCut} + ${secondCutAfter})
      # Adjust time to display correctly
      if (( secondPlusRaw >= 60 )) ; then
        newSecondPlusRaw=$(expr ${secondPlusRaw} - 60)
        secondPlusRaw=${newSecondPlusRaw}
        minutePlusRaw=$(expr ${minutePlusRaw} + 1)
      fi
      if (( minutePlusRaw >= 60 )) ; then
        newMinutePlusRaw=$(expr ${minutePlusRaw} - 60)
        minutePlusRaw=${newMinutePlusRaw}
        hourPlusRaw=$(expr ${hourPlusRaw} + 1)
      fi
      # Convert time total
      hourPlus=$(zero_number "${hourPlusRaw}")
      minutePlus=$(zero_number "${minutePlusRaw}")
      secondPlus=$(zero_number "${secondPlusRaw}")
      print -P -n "* (Default: %By%b) Extract audio from ${hourCut}:${minuteCut}:${secondCut} to ${hourPlus}:${minutePlus}:${secondPlus}? (y/n): " ; read accept_extraction_advanced
      if [[ "${accept_extraction_advanced}" == "n" ]] ; then
        exit
      else
        print ""
        print -P -n "* Starting extract audio track (%B${2}%b) "
        sleep 3
        ffmpeg -y -i "${2}" -map ${audio_track} -c:a copy -ss ${hourCut}:${minuteCut}:${secondCut} -t ${hourCutAfter}:${minuteCutAfter}:${secondCutAfter} "${audio_file_dir}"
        print ""
        print -P -n "* Extracted audio into %U${audio_file_dir}%u"
        sleep 2
        print "" && print ""
        exit
      fi
    fi
  else
    print ""
    print -P "* The file %U${2}%u does not exist"
    print ""
    exit
  fi
elif [[ "${1}" == "-evat" ]] ; then
  # Run commands for -evat parameter
  if [[ -z "${2}" ]] ; then
    show_menu
  elif [[ -f "${2}" ]] ; then
    hourCut=0
    minuteCut=1
    secondCut=0
    print ""
    print -P "+ %BVideo Tracks:%b"
    ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | cut -d "," -f 1
    print ""
    print -P "+ %BAudio Tracks:%b"
    ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | cut -d "," -f 1
    print ""
    print "+ Video time:"
    ffmpeg -i "${2}" 2>&1 | grep "Duration" | cut -d "," -f 1 | tr -s " "
    print ""
    # Check de video track by default
    video_default=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
    if [[ -z "${video_default}" ]] ; then
      video_default=("0:0")
    else
      video_default_patch=$(print ${video_default} | cut -c4)
      if [[ "${video_default_patch}" == ":" ]] ; then
        video_default=$(print ${video_default} | cut -c1-3)
      else
        video_default=("${video_default}")
      fi
    fi
    # Ask for video
    print -P -n "* (Default: %B${video_default}%b) Type the number of video track: " ; read video_track
    if [[ -z "${video_track}" ]] ; then
      video_track=("${video_default}")
    else
      video_track=("${video_track}")
    fi
    # Check the audio track by default
    audio_default=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | grep "(${default_lang_audio})" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
    if [[ -z "${audio_default}" ]] ; then
      audio_default=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
      if [[ -z "${audio_default}" ]] ; then
        audio_default=("0:1")
      else
        audio_default_patch=$(print ${audio_default} | cut -c4)
        if [[ "${audio_default_patch}" == ":" ]] ; then
          audio_default=$(print ${audio_default} | cut -c1-3)
        else
          audio_default=("${audio_default}")
        fi
      fi
    else
      audio_default_patch=$(print ${audio_default} | cut -c4)
      if [[ "${audio_default_patch}" == ":" ]] ; then
        audio_default=$(print ${audio_default} | cut -c1-3)
      else
        audio_default=("${audio_default}")
      fi
    fi
    # Ask for audio
    print -P -n "* (Default: %B${audio_default}%b) Type the number of audio track: " ; read audio_track
    if [[ -z "${audio_track}" ]] ; then
      audio_track=("${audio_default}")
    else
      audio_track=("${audio_track}")
    fi
    # Ask for hour to cut
    valid_time=0
    while (( valid_time == 0 )) ; do
      print -P -n "* (Default: %B${hourCut}%b) Type the hour (0-99): " ; read hour_cut
      expr 1 + ${hour_cut} &> /dev/null
      error_time=$?
      if [[ -z "${hour_cut}" ]] ; then
        hourZero=$(zero_number "${hourCut}")
        hourCut=("${hourZero}")
        valid_time=1
      else
        if (( error_time == 0 )) ; then
          if (( hour_cut <= 99 )) ; then
            hourZero=$(zero_number "${hour_cut}")
            hourCut=("${hourZero}")
            valid_time=1
          else
            print "+ Only numbers from 0 to 99 are allowed"
          fi
        else
          print "+ Only numbers are allowed (0-99)"
        fi
      fi
    done
    # Ask for minute to cut
    valid_time=0
    while (( valid_time == 0 )) ; do
      print -P -n "* (Default: %B${minuteCut}%b) Type the minute (0-59): " ; read minute_cut
      expr 1 + ${minute_cut} &> /dev/null
      error_time=$?
      if [[ -z "${minute_cut}" ]] ; then
        minuteZero=$(zero_number "${minuteCut}")
        minuteCut=("${minuteZero}")
        valid_time=1
      else
        if (( error_time == 0 )) ; then
          if (( minute_cut <= 59 )) ; then
            minuteZero=$(zero_number "${minute_cut}")
            minuteCut=("${minuteZero}")
            valid_time=1
          else
            print "+ Only numbers from 0 to 59 are allowed"
          fi
        else
          print "+ Only numbers are allowed (0-59)"
        fi
      fi
    done
    # Ask for second to cut
    valid_time=0
    while (( valid_time == 0 )) ; do
      print -P -n "* (Default: %B${secondCut}%b) Type the second (0-59): " ; read second_cut
      expr 1 + ${second_cut} &> /dev/null
      error_time=$?
      if [[ -z "${second_cut}" ]] ; then
        secondZero=$(zero_number "${secondCut}")
        secondCut=("${secondZero}")
        valid_time=1
      else
        if (( error_time == 0 )) ; then
          if (( second_cut <= 59 )) ; then
            secondZero=$(zero_number "${second_cut}")
            secondCut=("${secondZero}")
            valid_time=1
          else
            print "+ Only numbers from 0 to 59 are allowed"
          fi
        else
          print "+ Only numbers are allowed (0-59)"
        fi
      fi
    done
    print -P -n "* (Default: %Bn%b) Extract audio from ${hourCut}:${minuteCut}:${secondCut} to end? (y/n): " ; read accept_extraction
    if [[ "${accept_extraction}" == "y" ]] ; then
      print ""
      print -P -n "* Starting extract video and audio tracks (%B${2}%b) "
      sleep 3
      ffmpeg -y -i "${2}" -map ${video_track} -map ${audio_track} -c:v copy -c:a copy -ss ${hourCut}:${minuteCut}:${secondCut} -reset_timestamps 1 "${output_file_dir}"
      print ""
      print -n "* Extracted video and audio into ${output_file_dir}"
      sleep 2
      print "" && print ""
      exit
    else
      hourCutAfter=0
      minuteCutAfter=10
      secondCutAfter=0
      # Ask for hour to cut
      print ""
      valid_time=0
      while (( valid_time == 0 )) ; do
        print -P -n "* (Default: %B${hourCutAfter}%b) Type how many hours from ${hourCut}:${minuteCut}:${secondCut} (0-99): " ; read hour_cutAfter
        expr 1 + ${hour_cutAfter} &> /dev/null
        error_time=$?
        if [[ -z "${hour_cutAfter}" ]] ; then
          hourZeroAfter=$(zero_number "${hourCutAfter}")
          hourCutAfter=("${hourZeroAfter}")
          valid_time=1
        else
          if (( error_time == 0 )) ; then
            if (( hour_cutAfter <= 99 )) ; then
              hourZeroAfter=$(zero_number "${hour_cutAfter}")
              hourCutAfter=("${hourZeroAfter}")
              valid_time=1
            else
              print "+ Only numbers from 0 to 99 are allowed"
            fi
          else
            print "+ Only numbers are allowed (0-99)"
          fi
        fi
      done
      # Ask for minute to cut
      valid_time=0
      while (( valid_time == 0 )) ; do
        print -P -n "* (Default: %B${minuteCutAfter}%b) Type how many minutes from ${hourCut}:${minuteCut}:${secondCut} (0-59): " ; read minute_cutAfter
        expr 1 + ${minute_cutAfter} &> /dev/null
        error_time=$?
        if [[ -z "${minute_cutAfter}" ]] ; then
          minuteZeroAfter=$(zero_number "${minuteCutAfter}")
          minuteCutAfter=("${minuteZeroAfter}")
          valid_time=1
        else
          if (( error_time == 0 )) ; then
            if (( minute_cutAfter <= 59 )) ; then
              minuteZeroAfter=$(zero_number "${minute_cutAfter}")
              minuteCutAfter=("${minuteZeroAfter}")
              valid_time=1
            else
              print "+ Only numbers from 0 to 59 are allowed"
            fi
          else
            print "+ Only numbers are allowed (0-59)"
          fi
        fi
      done
      # Ask for second to cut
      valid_time=0
      while (( valid_time == 0 )) ; do
        print -P -n "* (Default: %B${secondCutAfter}%b) Type how many seconds from ${hourCut}:${minuteCut}:${secondCut} (0-59): " ; read second_cutAfter
        expr 1 + ${second_cutAfter} &> /dev/null
        error_time=$?
        if [[ -z "${second_cutAfter}" ]] ; then
          secondZeroAfter=$(zero_number "${secondCutAfter}")
          secondCutAfter=("${secondZeroAfter}")
          valid_time=1
        else
          if (( error_time == 0 )) ; then
            if (( second_cutAfter <= 59 )) ; then
              secondZeroAfter=$(zero_number "${second_cutAfter}")
              secondCutAfter=("${secondZeroAfter}")
              valid_time=1
            else
              print "+ Only numbers from 0 to 59 are allowed"
            fi
          else
            print "+ Only numbers are allowed (0-59)"
          fi
        fi
      done
      hourPlusRaw=$(expr ${hourCut} + ${hourCutAfter})
      minutePlusRaw=$(expr ${minuteCut} + ${minuteCutAfter})
      secondPlusRaw=$(expr ${secondCut} + ${secondCutAfter})
      # Adjust time to display correctly
      if (( secondPlusRaw >= 60 )) ; then
        newSecondPlusRaw=$(expr ${secondPlusRaw} - 60)
        secondPlusRaw=${newSecondPlusRaw}
        minutePlusRaw=$(expr ${minutePlusRaw} + 1)
      fi
      if (( minutePlusRaw >= 60 )) ; then
        newMinutePlusRaw=$(expr ${minutePlusRaw} - 60)
        minutePlusRaw=${newMinutePlusRaw}
        hourPlusRaw=$(expr ${hourPlusRaw} + 1)
      fi
      # Convert time total
      hourPlus=$(zero_number "${hourPlusRaw}")
      minutePlus=$(zero_number "${minutePlusRaw}")
      secondPlus=$(zero_number "${secondPlusRaw}")
      print -P -n "* (Default: %By%b) Extract video + audio from ${hourCut}:${minuteCut}:${secondCut} to ${hourPlus}:${minutePlus}:${secondPlus}? (y/n): " ; read accept_extraction_advanced
      if [[ "${accept_extraction_advanced}" == "n" ]] ; then
        exit
      else
        print ""
        print -P -n "* Starting extract video and audio tracks (%B${2}%b) "
        sleep 3
        ffmpeg -y -i "${2}" -map ${video_track} -map ${audio_track} -c:v copy -c:a copy -ss ${hourCut}:${minuteCut}:${secondCut} -t ${hourCutAfter}:${minuteCutAfter}:${secondCutAfter} -reset_timestamps 1 "${output_file_dir}"
        print ""
        print -n "* Extracted video and audio into ${output_file_dir}"
        sleep 2
        print "" && print ""
        exit
      fi
    fi
  else
    print ""
    print -P "* The file %U${2}%u does not exist"
    print ""
    exit
  fi
elif [[ "${1}" == "-frag" ]] ; then
  # Run commands for -frag parameter
  if [[ -z "${2}" ]] ; then
    show_menu
  elif [[ -f "${2}" ]] ; then
    fragment_default=("55")
    print ""
    print -P "+ %BVideo Tracks:%b"
    ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | cut -d "," -f 1
    print ""
    print -P "+ %BAudio Tracks:%b"
    ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | cut -d "," -f 1
    print ""
    print "+ Video time:"
    ffmpeg -i "${2}" 2>&1 | grep "Duration" | cut -d "," -f 1 | tr -s " "
    print ""
    # Check de video track by default
    video_default=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
    if [[ -z "${video_default}" ]] ; then
      video_default=("0:0")
    else
      video_default_patch=$(print ${video_default} | cut -c4)
      if [[ "${video_default_patch}" == ":" ]] ; then
        video_default=$(print ${video_default} | cut -c1-3)
      else
        video_default=("${video_default}")
      fi
    fi
    # Ask for video
    print -P -n "* (Default: %B${video_default}%b) Type the number of video track: " ; read video_track
    if [[ -z "${video_track}" ]] ; then
      video_track=("${video_default}")
    else
      video_track=("${video_track}")
    fi
    # Check the audio track by default
    audio_default=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | grep "(${default_lang_audio})" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
    if [[ -z "${audio_default}" ]] ; then
      audio_default=$(ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
      if [[ -z "${audio_default}" ]] ; then
        audio_default=("0:1")
      else
        audio_default_patch=$(print ${audio_default} | cut -c4)
        if [[ "${audio_default_patch}" == ":" ]] ; then
          audio_default=$(print ${audio_default} | cut -c1-3)
        else
          audio_default=("${audio_default}")
        fi
      fi
    else
      audio_default_patch=$(print ${audio_default} | cut -c4)
      if [[ "${audio_default_patch}" == ":" ]] ; then
        audio_default=$(print ${audio_default} | cut -c1-3)
      else
        audio_default=("${audio_default}")
      fi
    fi
    # Ask for audio
    print -P -n "* (Default: %B${audio_default}%b) Type the number of audio track: " ; read audio_track
    if [[ -z "${audio_track}" ]] ; then
      audio_track=("${audio_default}")
    else
      audio_track=("${audio_track}")
    fi
    # Ask for secons of fragments
    print -P -n "* (Default: %B${fragment_default}%b) Type the number of seconds for each fragment: " ; read seconds_fragments
    if [[ -z "${seconds_fragments}" ]] ; then
      seconds_fragments=("${fragment_default}")
    else
      seconds_fragments=("${seconds_fragments}")
    fi
    filename_frag=$(basename "${2}")
    filename_cut=$(basename "${2}" | cut -d "." -f 1)
    dirname_frag=$(dirname "${2}")
    cd ${dirname_frag}
    mkdir -p fragments
    print ""
    print -P -n "* Starting extract video and audio in fragments (%B${2}%b) "
    sleep 3
    ffmpeg -y -i "${filename_frag}" -map ${video_track} -map ${audio_track} -c:v copy -c:a copy -f segment -segment_time ${seconds_fragments} -reset_timestamps 1 "fragments/${filename_cut}-%03d.mp4"
    print ""
    print -n "* Extracted fragments into ${dirname_frag}/fragments "
    sleep 3
    print ""
    exit
  else
    print ""
    print -P "* The file %U${2}%u does not exist"
    print ""
    exit
  fi
elif [[ "${1}" == "-chec" ]] ; then
  # Run commands for -chec parameter
  if [[ -z "${2}" ]] ; then
    show_menu
  elif [[ -f "${2}" ]] ; then
    print ""
    print "* Information of ${2}:"
    print ""
    print -P "+ %BVideo Tracks:%b"
    ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Video:"
    print ""
    print -P "+ %BAudio Tracks:%b"
    ffmpeg -i "${2}" 2>&1 | grep Stream | tr -s " " | grep "Audio:"
    print ""
    print -P "+ %BSubtitle Tracks:%b"
    ffmpeg -i "${1}" 2>&1 | grep Stream | tr -s " " | grep "Subtitle:"
    print ""
  else
    print ""
    print -P "* The file %U${2}%u does not exist"
    print ""
    exit
  fi
elif [[ "${1}" == "-mixf" ]] ; then
  # Run commands for -mixf parameter
  if [[ "${video_found}" == "FOUND" ]] ; then
    print null > /dev/null
  else
    print ""
    print "* File '${video_file_dir}' not found!"
    print ""
    print "* Aborted mix"
    print ""
    exit
  fi
  if [[ "${audio_found}" == "FOUND" ]] ; then
    print null > /dev/null
  else
    print ""
    print "* File '${audio_file_dir}' not found!"
    print ""
    print "* Aborted mix"
    print ""
    exit
  fi
  cut_video=0
  cut_audio=0
  # Set the secons to cut on video/audio
  print ""
  print -P -n "* (Default: %B${cut_video}%b) Set the seconds to cut in the video (0-59): " ; read seconds_video
  if [[ -z "${seconds_video}" ]] ; then
    seconds_video=${cut_video}
  else
    seconds_video=${seconds_video}
  fi
  print -P -n "* (Default: %B${cut_audio}%b) Set the seconds to cut in the audio (0-59): " ; read seconds_audio
  if [[ -z "${seconds_audio}" ]] ; then
    seconds_audio=${cut_audio}
  else
    seconds_audio=${seconds_audio}
  fi
  # Set if you want -shortest mode
  print -P -n "* (Default: %Bn%b) Finish the mix when one of the two (video or audio) finishes first? (y/n): " ; read finish_mix
  if [[ -z "${finish_mix}" ]] ; then
    finish_mix=n
  elif [[ "${finish_mix}" == "y" ]] ; then
    finish_mix=y
  else
    finish_mix=n
  fi
  # Cut video
  if (( seconds_video == 0 )) ; then
    video_input_stream=${video_file_dir}
    remove_video_input=${current_dir}/video-cut.mkv
  else
    if (( seconds_video <= 9 )) ; then
      ffmpeg -y -i ${video_file_dir} -ss 00:00:0${seconds_video} -c:v copy ${current_dir}/video-cut.mkv
      video_input_stream=${current_dir}/video-cut.mkv
      remove_video_input=${current_dir}/video-cut.mkv
    else
      ffmpeg -y -i ${video_file_dir} -ss 00:00:${seconds_video} -c:v copy ${current_dir}/video-cut.mkv
      video_input_stream=${current_dir}/video-cut.mkv
      remove_video_input=${current_dir}/video-cut.mkv
    fi
  fi
  # Cut audio
  if (( seconds_audio == 0 )) ; then
    audio_input_stream=${audio_file_dir}
    remove_audio_input=${current_dir}/audio-cut.mka
  else
    if (( seconds_audio <= 9 )) ; then
      ffmpeg -y -i ${audio_file_dir} -ss 00:00:0${seconds_audio} -c:a copy ${current_dir}/audio-cut.mka
      audio_input_stream=${current_dir}/audio-cut.mka
      remove_audio_input=${current_dir}/audio-cut.mka
    else
      ffmpeg -y -i ${audio_file_dir} -ss 00:00:${seconds_audio} -c:a copy ${current_dir}/audio-cut.mka
      audio_input_stream=${current_dir}/audio-cut.mka
      remove_audio_input=${current_dir}/audio-cut.mka
    fi
  fi
  print ""
  print "* Starting mix of:"
  print "  - Video: ${video_file_dir}"
  print "  - Audio: ${audio_file_dir}"
  print ""
  print -n "  Output file: ${output_file_dir} "
  sleep 3
  print "" && print ""
  if [[ "${finish_mix}" == "y" ]] ; then
    ffmpeg -y -i "${video_input_stream}" -i "${audio_input_stream}" -c:v copy -c:a copy -shortest "${output_file_dir}"
  else
    ffmpeg -y -i "${video_input_stream}" -i "${audio_input_stream}" -c:v copy -c:a copy "${output_file_dir}"
  fi
  print ""
  print -n "* Mixed video/audio into ${output_file_dir}"
  rm -rf ${remove_video_input}
  rm -rf ${remove_audio_input}
  sleep 2
  print "" && print ""
  exit
elif [[ "${1}" == "-mixs" ]] ; then
  # Run commands for -mixs parameter
  if [[ "${video_found}" == "FOUND" ]] ; then
    print null > /dev/null
  else
    print ""
    print "* File '${video_file_dir}' not found!"
    print ""
    print "* Aborted mix"
    print ""
    exit
  fi
  if [[ "${audio_found}" == "FOUND" ]] ; then
    print null > /dev/null
  else
    print ""
    print "* File '${audio_file_dir}' not found!"
    print ""
    print "* Aborted mix"
    print ""
    exit
  fi
  if [[ "${subs_found}" == "FOUND" ]] ; then
    print null > /dev/null
  else
    print ""
    print "* File '${subs_file_dir}' not found!"
    print ""
    print "* Aborted mix"
    print ""
    exit
  fi
  cut_video=0
  cut_audio=0
  # Set the secons to cut on video/audio
  print ""
  print -P -n "* (Default: %B${cut_video}%b) Set the seconds to cut in the video (0-59): " ; read seconds_video
  if [[ -z "${seconds_video}" ]] ; then
    seconds_video=${cut_video}
  else
    seconds_video=${seconds_video}
  fi
  print -P -n "* (Default: %B${cut_audio}%b) Set the seconds to cut in the audio (0-59): " ; read seconds_audio
  if [[ -z "${seconds_audio}" ]] ; then
    seconds_audio=${cut_audio}
  else
    seconds_audio=${seconds_audio}
  fi
  # Set if you want -shortest mode
  print -P -n "* (Default: %Bn%b) Finish the mix when one of the three (video, audio or subs) finishes first? (y/n): " ; read finish_mix
  if [[ -z "${finish_mix}" ]] ; then
    finish_mix=n
  elif [[ "${finish_mix}" == "y" ]] ; then
    finish_mix=y
  else
    finish_mix=n
  fi
  # Cut video
  if (( seconds_video == 0 )) ; then
    video_input_stream=${video_file_dir}
    remove_video_input=${current_dir}/video-cut.mkv
  else
    if (( seconds_video <= 9 )) ; then
      ffmpeg -y -i ${video_file_dir} -ss 00:00:0${seconds_video} -c:v copy ${current_dir}/video-cut.mkv
      video_input_stream=${current_dir}/video-cut.mkv
      remove_video_input=${current_dir}/video-cut.mkv
    else
      ffmpeg -y -i ${video_file_dir} -ss 00:00:${seconds_video} -c:v copy ${current_dir}/video-cut.mkv
      video_input_stream=${current_dir}/video-cut.mkv
      remove_video_input=${current_dir}/video-cut.mkv
    fi
  fi
  # Cut audio
  if (( seconds_audio == 0 )) ; then
    audio_input_stream=${audio_file_dir}
    remove_audio_input=${current_dir}/audio-cut.mka
  else
    if (( seconds_audio <= 9 )) ; then
      ffmpeg -y -i ${audio_file_dir} -ss 00:00:0${seconds_audio} -c:a copy ${current_dir}/audio-cut.mka
      audio_input_stream=${current_dir}/audio-cut.mka
      remove_audio_input=${current_dir}/audio-cut.mka
    else
      ffmpeg -y -i ${audio_file_dir} -ss 00:00:${seconds_audio} -c:a copy ${current_dir}/audio-cut.mka
      audio_input_stream=${current_dir}/audio-cut.mka
      remove_audio_input=${current_dir}/audio-cut.mka
    fi
  fi
  print ""
  print "* Starting mix of:"
  print "  - Video: ${video_file_dir}"
  print "  - Audio: ${audio_file_dir}"
  print "  - Subs: ${subs_file_dir}"
  print ""
  print -n "  Output file: ${output_file_dir} "
  sleep 3
  print "" && print ""
  if [[ "${finish_mix}" == "y" ]] ; then
    ffmpeg -y -i "${video_input_stream}" -i "${audio_input_stream}" -i "${subs_file_dir}" -c:v copy -c:a copy -c:s copy -shortest "${output_file_dir}"
  else
    ffmpeg -y -i "${video_input_stream}" -i "${audio_input_stream}" -i "${subs_file_dir}" -c:v copy -c:a copy -c:s copy "${output_file_dir}"
  fi
  print ""
  print -n "* Mixed video/audio/subs into ${output_file_dir}"
  rm -rf ${remove_video_input}
  rm -rf ${remove_audio_input}
  sleep 2
  print "" && print ""
  exit
else
  show_menu
fi
