#!/usr/bin/env zsh

setopt NO_NOMATCH

######################################################################
# ks-mp3-album (ks-tools) - Convert folder album to MP3 Audio Format #
# Date: 10-11-2023                                                   #
# Author: dmesg00                                                    #
# Contact: dmesg00@duck.com                                          #
######################################################################
VERSION=("9.5")
M_DATE=("250826")

# Variables
tempFile=("/tmp/ks-mp4s-folder.txt")
tempFileTest=("/tmp/ks-mp4s-folder-test.txt")
formatFiles=(mp4 avi mpg mpeg mov wmv mkv ogv webm rm flv vob ogg oga mp3 mp2 aac ac3 flac opus wav)

# Global parameters
dirTemp=("/tmp")
listTemp=("ks-tools.list")
ksToolsTempFolder=("/tmp/ks-tools")
configFolder=${HOME}/.ks-tools 
configFile=${configFolder}/ks-mp3

# Basic parameters
acodec=("libmp3lame")
b_acodec=("128k")
v_ext=("mp3")
track_init=("1")
artist_init=("Artist")
default_lang_audio=("spa")

# Check cygwin alias (for Windows)
if [[ -f "/usr/bin/cygwin-alias.zsh" ]] ; then
  setopt ALIASES
  source "/usr/bin/cygwin-alias.zsh"
fi

# Create inicial config file
mkdir -p ${configFolder}
if [[ -f ${configFile} ]] ; then
  exist_acodec=$(cat ${configFile} | grep "acodec" | cut -c2 | cut -d "_" -f 1) 
  exist_b_acodec=$(cat ${configFile} | grep "b_acodec=") 
  exist_default_lang_audio=$(cat ${configFile} | grep "default_lang_audio=") 
  exist_v_ext=$(cat ${configFile} | grep "v_ext=")
  if [[ -z ${exist_acodec} ]] ; then
    print "acodec=${acodec}" >> ${configFile}
  fi
  if [[ -z ${exist_b_acodec} ]] ; then
    print "b_acodec=${b_acodec}" >> ${configFile}
  fi
  if [[ -z ${exist_default_lang_audio} ]] ; then
    print "default_lang_audio=${default_lang_audio}" >> ${configFile}
  fi
  if [[ -z ${exist_v_ext} ]] ; then
    print "v_ext=${v_ext}" >> ${configFile}
  fi
  source ${configFile}
else
  print "#!/usr/bin/env zsh" > ${configFile}
  print "" >> ${configFile}
  print "acodec=${acodec}" >> ${configFile}
  print "b_acodec=${b_acodec}" >> ${configFile}
  print "default_lang_audio=${default_lang_audio}" >> ${configFile}
  print "v_ext=${v_ext}" >> ${configFile}
  source ${configFile}
fi

# Function for check dependencies
check_dependencies() {
  which_dependence=$(which ${1})
  error_dependence=$?
  if [[ -z "${which_dependence}" ]] || (( ${error_dependence} > 0 )); then
    print ""
    print -P "* %Bks-mp3-album%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
    print ""
    print -P "* %BDependency not found%b: %U${1}%u"
    print ""
    exit 1
  fi 
}

# Check dependencies
dependencies=(ffmpeg grep sed grep cut head tail tr cat)
for scan_dependency in "${dependencies[@]}" ; do
  check_dependencies "${scan_dependency}"
done

# Funcion to show the name of file/folder from full path
# Syntax: extractFolderOrFile <full/path/file.txt>
extractFolderOrFile() {
  pathToExtract=("${1}/")
  findFolder=0
  count=1
  nameFolder=$(print ${pathToExtract} | cut -d "/" -f ${count})
  count=$(expr $count + 1)
  while (( findFolder == 0 )) ; do
    nameFolderTemp=$(print ${pathToExtract} | cut -d "/" -f ${count})
    if [[ -z "${nameFolderTemp}" ]] ; then
      findFolder=1
    else
      nameFolder=("${nameFolderTemp}")
      count=$(expr $count + 1)
    fi
  done
  print "${nameFolder}"
}

# Function to show files with spaces.
# Syntax: showFileWithSpace <file number>
showFileWithSpace() {
  print "${1}" > ${dirTemp}/name.tmp
  sed -i 's/_/ /g' ${dirTemp}/name.tmp 2> /dev/null
  DisplayName=$(cat ${dirTemp}/name.tmp)
  rm -rf ${dirTemp}/name.tmp
  cutDisplayName=$(print ${DisplayName} | cut -c1)
  if [[ "${cutDisplayName}" == "-" ]] ; then
    DisplayName=$(print ${DisplayName} | cut -c2-100)
  else
    cutDisplayName=$(print ${DisplayName} | cut -c2)
    if [[ "${cutDisplayName}" == "-" ]] ; then
      DisplayName=$(print ${DisplayName} | cut -c3-100)
    else
      cutDisplayName=$(print ${DisplayName} | cut -c3)
      if [[ "${cutDisplayName}" == "-" ]] ; then
        DisplayName=$(print ${DisplayName} | cut -c4-100)
      fi
    fi
  fi
  print ${DisplayName}
}

# Function to remove extension from file
# Syntax: removeExtension "<text>"
removeExtension() {
  wordToConvert=${1}
  ksToolsSedFile=("${ksToolsTempFolder}/ks-tools-${RANDOM}.txt")
  mkdir -p ${ksToolsTempFolder} && chmod 777 -R ${ksToolsTempFolder} 2> /dev/null
  print "${wordToConvert}" > ${ksToolsSedFile}
  # Remove extensions
  sed -i 's/\.avi//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.mp4//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.mkv//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.mov//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.vob//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.mpg//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.mpeg//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.wmv//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.ogv//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.webm//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.flv//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.mp3//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.mp2//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.oga//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.ogg//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.ac3//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.aac//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.flac//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.wav//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.opus//g' "${ksToolsSedFile}" &> /dev/null
  # Show file without extension
  wordToConvert=$(cat ${ksToolsSedFile})
  print ${wordToConvert}
}

# Syntax: ks-mp3-album </absolute/path/album/
if [[ -z "${1}" ]] ; then
  print ""
  print -P "* %Bks-mp3-album%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
  print ""
  print "\- Convert folder album to MP3 Audio Format"
  print ""
  print -P "+ %UConfig%u: %B${configFile}%b"
  print ""
  print -P " - Audio codec: %B${acodec}%b"
  print -P " - Bitrate audio: %B${b_acodec}%b"
  print -P " - Container: %B${v_ext}%b"
  print ""
  print -P "+ %USyntax%u: "
  print ""
  print -P "  $ %Bks-mp3-album%b </absolute/path/album>"
  print ""
  print -P " + %UExample%u: %Bks-mp3-album%b /data/albums/matrix-soundtrack"
  print ""
  exit
fi

# Check if folder exist
if [[ -d "${1}" ]] ; then
  print null > /dev/null
else
  print ""
  print -P "* %Bks-mp3-album%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
  print ""
  print -P "* The folder %U${1}%u does not exist!"
  print ""
  exit
fi

# Scan videos/audio files format
clear
print ""
print -P "* %Bks-mp3-album%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
print ""
print "\- Convert folder album to MP3 Audio Format"
print ""
print -P -n "* Scanning %U${1}%u"
print ""
rm -rf ${tempFile} && touch ${tempFile}
for format in "${formatFiles[@]}" ; do
  find "${1}"/*.${format} &> ${tempFileTest}
  if (( $? != 0 )) ; then
    print "null" > /dev/null
  else
    print "+ Video file(s) in .${format} found!"
    cd "${1}" && ls -1 *.${format} &> /tmp/tempFile.txt
    cat /tmp/tempFile.txt >> ${tempFile}
    rm -rf /tmp/tempFile.txt 2> /dev/null
    fail=0
  fi
done

# Set the global metadata album
current_date=$(date +%Y)
print ""
print -P "* %UCommon METADATA configuration%u:"
print ""
print -P -n "* (Default: %BAlbum-Disc%b) Type name of album: " ; read album_file
if [[ -z "${album_file}" ]] ; then
  album_title=("Album-Disc")
else
  album_title=("${album_file}")
fi
print -P -n "* (Default: %B${current_date}%b) Type the year of album: " ; read year_file
if [[ -z "${year_file}" ]] ; then
  year_num=("${current_date}")
else
  year_num=("${year_file}")
fi
print -P -n "* (Default: %BPop%b) Type the genre of album: " ; read genre_file
if [[ -z "${genre_file}" ]] ; then
  genre_file=("Pop")
else
  genre_file=("${genre_file}")
fi

# Init the conversion files
convert_files=1
num_files=$(cat ${tempFile} | wc -l)
if (( num_files == 0 )) ; then
  print ""
  print -P "+ No video/audio file(s) found in folder %U${1}%u"
  print ""
  exit
else
  print ""
  print -P "* %UList of files%u:"
  print ""
  while (( convert_files <= num_files )) ; do
    show_file=$(cat ${tempFile} | head -${convert_files} | tail -1)
    print "  + ${show_file}"
    convert_files=$(expr ${convert_files} + 1)
  done
  print ""
  print -P "* The output folder will be %U${1}/to-mp3%u"
  # Execute commands for conversion
  print ""
  print -P -n "* (Default: %By%b) Do you want run the conversion? (y/n): " ; read run_commands_ffmpeg
  if [[ "${run_commands_ffmpeg}" == "n" ]] ; then
    exit
  else
    convert_files=1
    cd "${1}" && mkdir -p to-mp3 && rm -rf to-mp3/*
    while (( convert_files <= num_files )) ; do
      show_file=$(cat ${tempFile} | head -${convert_files} | tail -1)
      fname=$(print "${show_file}" | cut -d "." -f 1)
      name_title_default=$(removeExtension "${show_file}")
      name_title_default=$(showFileWithSpace "${name_title_default}")
      print ""
      print -P "* METADATA for %U${show_file}%u"
      print ""
      print -P " - Album: %B${album_title}%b"
      print -P " - Year: %B${year_num}%b"
      print -P " - Genre: %B${genre_file}%b"
      print -P ""
      print -P "* Information of %U${show_file}%u:"
      print ""
      print -P "+ %BAudio Tracks:%b"
      print ""
      ffmpeg -i "${show_file}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | cut -d "," -f 1
      print ""
      # Check the audio track by default
      audio_default=$(ffmpeg -i "${show_file}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | grep "(${default_lang_audio})" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
      if [[ -z "${audio_default}" ]] ; then
        audio_default=$(ffmpeg -i "${show_file}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
        if [[ -z "${audio_default}" ]] ; then
          audio_default=("0:1")
        else
          audio_default_patch=$(print ${audio_default} | cut -c4)
          if [[ "${audio_default_patch}" == ":" ]] ; then
            audio_default=$(print ${audio_default} | cut -c1-3)
          else
            audio_default=("${audio_default}")
          fi
        fi
      else
        audio_default_patch=$(print ${audio_default} | cut -c4)
        if [[ "${audio_default_patch}" == ":" ]] ; then
          audio_default=$(print ${audio_default} | cut -c1-3)
        else
          audio_default=("${audio_default}")
        fi
      fi
      # Ask for audio
      print -P -n "* (Default: %B${audio_default}%b) Type the number of audio track: " ; read audio_track
      if [[ -z "${audio_track}" ]] ; then
        audio_track=("${audio_default}")
      else
        audio_track=("${audio_track}")
      fi
      print -P -n "* (Default: %B${name_title_default}%b) Type name of title: " ; read name_title
      if [[ -z "${name_title}" ]] ; then
        name_title=("${name_title_default}")
      else
        name_title=("${name_title}")
      fi
      print -P -n "* (Default: %B${track_init}%b) Type number of track: " ; read track_file
      if [[ -z "${track_file}" ]] ; then
        track_num=("${track_init}")
      else
        track_num=("${track_file}")
      fi
      print -P -n "* (Default: %B${artist_init}%b) Type name of artist: " ; read artist_file
      if [[ -z "${artist_file}" ]] ; then
        artist_title=("${artist_init}")
      else
        artist_title=("${artist_file}")
        artist_init=("${artist_file}")
      fi
      # Check audio 5.1 or 7.1
      audio_5_7_1=$("${p_ffmpeg[@]}" "${show_file}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | grep "${audio_track}" | grep -i "5.1")
      audio_5_7_1_2=$("${p_ffmpeg[@]}" "${show_file}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | grep "${audio_track}" | grep -i "7.1")
      audio_5_7_1=("${audio_5_7_1}${audio_5_7_1_2}")
      if [[ -z "${audio_5_7_1}" ]] ; then
        stereo_params=(-ac 2)
      else
        stereo_params=(-ac 2 -clev 3dB -slev -6dB)
      fi
      ffmpeg -i "${show_file}" -map ${audio_track} -c:a ${acodec} -b:a ${b_acodec} "${stereo_params[@]}" -metadata title="${name_title}" -metadata date="${year_num}" -metadata genre="${genre_file}" -metadata album="${album_title}" -metadata artist="${artist_title}" -metadata track="${track_num}" "to-mp3/${fname}.${v_ext}"
      # Increment variables
      convert_files=$(expr ${convert_files} + 1)
      track_init=$(expr ${track_num} + 1)
    done
  fi
fi
