#!/usr/bin/env zsh

setopt NO_NOMATCH

#############################################################################
# ks-oga (ks-tools) - Convert video/audio file(s) to OGA (OGG Audio) Format #
# Date: 25-08-2026                                                          #
# Author: dmesg00                                                           #
# Contact: dmesg00@duck.com                                                 #
#############################################################################
VERSION=("9.5")
M_DATE=("250826")

# Global parameters
dirTemp=("/tmp")
listTemp=("ks-tools.list")
ksToolsTempFolder=("/tmp/ks-tools")
configFolder=${HOME}/.ks-tools 
configFile=${configFolder}/ks-oga

# Basic parameters
acodec=("libvorbis")
b_acodec=("130k")
v_ext=("oga")
default_lang_audio=("spa")

# Check cygwin alias (for Windows)
if [[ -f "/usr/bin/cygwin-alias.zsh" ]] ; then
  setopt ALIASES
  cygwin=("yes")
  source "/usr/bin/cygwin-alias.zsh"
else
  cygwin=("no")
fi

# Create inicial config file
mkdir -p ${configFolder}
if [[ -f ${configFile} ]] ; then
  exist_acodec=$(cat ${configFile} | grep "acodec" | cut -c2 | cut -d "_" -f 1) 
  exist_b_acodec=$(cat ${configFile} | grep "b_acodec=") 
  exist_default_lang_audio=$(cat ${configFile} | grep "default_lang_audio=") 
  exist_v_ext=$(cat ${configFile} | grep "v_ext=")
  if [[ -z ${exist_acodec} ]] ; then
    print "acodec=${acodec}" >> ${configFile}
  fi
  if [[ -z ${exist_b_acodec} ]] ; then
    print "b_acodec=${b_acodec}" >> ${configFile}
  fi
  if [[ -z ${exist_default_lang_audio} ]] ; then
    print "default_lang_audio=${default_lang_audio}" >> ${configFile}
  fi
  if [[ -z ${exist_v_ext} ]] ; then
    print "v_ext=${v_ext}" >> ${configFile}
  fi
  source ${configFile}
else
  print "#!/usr/bin/env zsh" > ${configFile}
  print "" >> ${configFile}
  print "acodec=${acodec}" >> ${configFile}
  print "b_acodec=${b_acodec}" >> ${configFile}
  print "default_lang_audio=${default_lang_audio}" >> ${configFile}
  print "v_ext=${v_ext}" >> ${configFile}
  source ${configFile}
fi

# Function for check dependencies
check_dependencies() {
  which_dependence=$(which ${1})
  error_dependence=$?
  if [[ -z "${which_dependence}" ]] || (( ${error_dependence} > 0 )); then
    print ""
    print -P "* %Bks-oga%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
    print ""
    print -P "* %BDependency not found%b: %U${1}%u"
    print ""
    exit 1
  fi 
}

# Check dependencies
dependencies=(ffmpeg grep sed grep cut head tail tr cat)
for scan_dependency in "${dependencies[@]}" ; do
  check_dependencies "${scan_dependency}"
done

# Funcion to show the name of file/folder from full path
# Syntax: extractFolderOrFile <full/path/file.txt>
extractFolderOrFile() {
  pathToExtract=("${1}/")
  findFolder=0
  count=1
  nameFolder=$(print ${pathToExtract} | cut -d "/" -f ${count})
  count=$(expr $count + 1)
  while (( findFolder == 0 )) ; do
    nameFolderTemp=$(print ${pathToExtract} | cut -d "/" -f ${count})
    if [[ -z "${nameFolderTemp}" ]] ; then
      findFolder=1
    else
      nameFolder=("${nameFolderTemp}")
      count=$(expr $count + 1)
    fi
  done
  print "${nameFolder}"
}

# Function to remove extension from file
# Syntax: removeExtension "<text>"
removeExtension() {
  wordToConvert=${1}
  ksToolsSedFile=("${ksToolsTempFolder}/ks-tools-${RANDOM}.txt")
  mkdir -p ${ksToolsTempFolder} && chmod 777 -R ${ksToolsTempFolder} 2> /dev/null
  print "${wordToConvert}" > ${ksToolsSedFile}
  # Remove extensions
  sed -i 's/\.avi//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.mp4//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.mkv//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.mov//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.vob//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.mpg//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.mpeg//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.wmv//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.ogv//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.webm//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.flv//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.mp3//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.mp2//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.oga//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.ogg//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.ac3//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.aac//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.flac//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.wav//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/\.opus//g' "${ksToolsSedFile}" &> /dev/null
  # Show file without extension
  wordToConvert=$(cat ${ksToolsSedFile})
  print ${wordToConvert}
}

# Function to show files with spaces.
# Syntax: showFileWithSpace <file number>
showFileWithSpace() {
  print "${1}" > ${dirTemp}/name.tmp
  sed -i 's/_/ /g' ${dirTemp}/name.tmp 2> /dev/null
  DisplayName=$(cat ${dirTemp}/name.tmp)
  rm -rf ${dirTemp}/name.tmp
  cutDisplayName=$(print ${DisplayName} | cut -c1)
  if [[ "${cutDisplayName}" == "-" ]] ; then
    DisplayName=$(print ${DisplayName} | cut -c2-100)
  else
    cutDisplayName=$(print ${DisplayName} | cut -c2)
    if [[ "${cutDisplayName}" == "-" ]] ; then
      DisplayName=$(print ${DisplayName} | cut -c3-100)
    else
      cutDisplayName=$(print ${DisplayName} | cut -c3)
      if [[ "${cutDisplayName}" == "-" ]] ; then
        DisplayName=$(print ${DisplayName} | cut -c4-100)
      fi
    fi
  fi
  print ${DisplayName}
}

# Syntax: ks-oga </absolute/path/song.mp3> </path/prefix_name>
if [[ -z "${1}" ]] ; then
  print ""
  print -P "* %Bks-oga%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
  print ""
  print "\- Convert video/audio file(s) to OGA (OGG Audio) Format"
  print ""
  print -P "+ %UConfig%u: %B${configFile}%b"
  print ""
  print -P " - Audio codec: %B${acodec}%b"
  print -P " - Bitrate audio: %B${b_acodec}%b"
  print -P " - Container: %B${v_ext}%b"
  print ""
  print -P "+ %USyntax%u: "
  print ""
  if [[ "${cygwin}" == "yes" ]] ; then
    print -P "  $ %Bks-oga%b <relative/path/song.mp3> <path/prefix_name>"
    print ""
    print -P " + Example: %Bks-oga%b songs/Example.mp3 converted/Example"
    print ""
    print -P "* %UNote%u: %BIn Cygwin, you must use relative paths with this tool%b"
    print ""
  else
    print -P "  $ %Bks-oga%b </absolute/path/song.mp3> </path/prefix_name>"
    print ""
    print -P " + Example: %Bks-oga%b /data/songs/Example.mp3 /data/converted/Example"
    print ""
  fi
  exit
fi
if [[ -f "${1}" ]] ; then
  print "detected" > /dev/null
else
  print ""
  print -P "* %Bks-oga%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
  print ""
  print -P "* The file %U${1}%u does not exist!"
  print ""
  exit
fi

# Conversion parameters
p_ffmpeg=(ffmpeg -i)

# Init conversion file
current_date=$(date +%Y)
if [[ -z "${2}" ]] ; then
  print ""
  print -P "* %Bks-oga%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
  print ""
  print "\- Convert video/audio file(s) to OGA (OGG Audio) Format"
  print ""
  print -P "+ %UConfig%u: %B${configFile}%b"
  print ""
  print -P " - Audio codec: %B${acodec}%b"
  print -P " - Bitrate audio: %B${b_acodec}%b"
  print -P " - Container: %B${v_ext}%b"
  print ""
  print -P "+ %USyntax%u: "
  print ""
  if [[ "${cygwin}" == "yes" ]] ; then
    print -P "  $ %Bks-oga%b <relative/path/song.mp3> <path/prefix_name>"
    print ""
    print -P " + Example: %Bks-oga%b songs/Example.mp3 converted/Example"
    print ""
    print -P "* %UNote%u: %BIn Cygwin, you must use relative paths with this tool%b"
    print ""
  else
    print -P "  $ %Bks-oga%b </absolute/path/song.mp3> </path/prefix_name>"
    print ""
    print -P " + Example: %Bks-oga%b /data/songs/Example.mp3 /data/converted/Example"
    print ""
  fi
  exit
else
  print ""
  print -P "* Information of %U${1}%u:"
  print ""
  print -P "+ %BAudio Tracks:%b"
  "${p_ffmpeg[@]}" "${1}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | cut -d "," -f 1
  print ""

  # Check the audio track by default
  audio_default=$("${p_ffmpeg[@]}" "${1}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | grep "(${default_lang_audio})" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
  if [[ -z "${audio_default}" ]] ; then
    audio_default=$("${p_ffmpeg[@]}" "${1}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | cut -d " " -f 3 | cut -c2-5 | cut -d "(" -f 1 | cut -d "[" -f 1 | head -1)
    if [[ -z "${audio_default}" ]] ; then
      audio_default=("0:1")
    else
      audio_default_patch=$(print ${audio_default} | cut -c4)
      if [[ "${audio_default_patch}" == ":" ]] ; then
        audio_default=$(print ${audio_default} | cut -c1-3)
      else
        audio_default=("${audio_default}")
      fi
    fi
  else
    audio_default_patch=$(print ${audio_default} | cut -c4)
    if [[ "${audio_default_patch}" == ":" ]] ; then
      audio_default=$(print ${audio_default} | cut -c1-3)
    else
      audio_default=("${audio_default}")
    fi
  fi
  # Ask for audio
  print -P -n "* (Default: %B${audio_default}%b) Type the number of audio track: " ; read audio_track
  if [[ -z "${audio_track}" ]] ; then
    audio_track=("${audio_default}")
  else
    audio_track=("${audio_track}")
  fi

  # Ask for METADATA
  print ""
  print -P "* %UMETADATA configuration%u:"
  print ""
  # Prepare name title by default
  FullPath=("${1}")
  name_title_default=$(extractFolderOrFile "${FullPath}")
  name_title_default=$(removeExtension "${name_title_default}")
  name_title_default=$(showFileWithSpace "${name_title_default}")
  # Ask name title, year and genre
  print -P -n "* (Default: %B${name_title_default}%b) Type name of title: " ; read name_title
  if [[ -z "${name_title}" ]] ; then
    name_title=("${name_title_default}")
  else
    name_title=("${name_title}")
  fi
  print -P -n "* (Default: %BAlbum-Disc%b) Type name of album: " ; read album_file
  if [[ -z "${album_file}" ]] ; then
    album_title=("Album-Disc")
  else
    album_title=("${album_file}")
  fi
  print -P -n "* (Default: %B01%b) Type number of track: " ; read track_file
  if [[ -z "${track_file}" ]] ; then
    track_num=("01")
  else
    track_num=("${track_file}")
  fi
  print -P -n "* (Default: %BArtist%b) Type name of artist: " ; read artist_file
  if [[ -z "${artist_file}" ]] ; then
    artist_title=("Artist")
  else
    artist_title=("${artist_file}")
  fi
  print -P -n "* (Default: %B${current_date}%b) Type the year: " ; read year_file
  if [[ -z "${year_file}" ]] ; then
    year_num=("${current_date}")
  else
    year_num=("${year_file}")
  fi
  print -P -n "* (Default: %BPop%b) Type the genre: " ; read genre_file
  if [[ -z "${genre_file}" ]] ; then
    genre_file=("Pop")
  else
    genre_file=("${genre_file}")
  fi

  # Check audio 5.1 or 7.1
  audio_5_7_1=$("${p_ffmpeg[@]}" "${1}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | grep "${audio_track}" | grep -i "5.1")
  audio_5_7_1_2=$("${p_ffmpeg[@]}" "${1}" 2>&1 | grep Stream | tr -s " " | grep "Audio:" | grep "${audio_track}" | grep -i "7.1")
  audio_5_7_1=("${audio_5_7_1}${audio_5_7_1_2}")
  if [[ -z "${audio_5_7_1}" ]] ; then
    stereo_params=(-ac 2)
  else
    stereo_params=(-ac 2 -clev 3dB -slev -6dB)
  fi

  # Show commands for conversion
  print ""
  print -P "* %UCOMMANDS THAT WILL BE EXECUTED%u:"
  print ""
  print "  # Convert the file '${1}' to OGG Audio"
  print "  ${p_ffmpeg[*]} \"${1}\" -map ${audio_track} -c:a ${acodec} -b:a ${b_acodec} "${stereo_params[@]}" -metadata title=\"${name_title}\" -metadata date=\"${year_num}\" -metadata genre=\"${genre_file}\" -metadata album=\"${album_title}\" -metadata artist=\"${artist_title}\" -metadata track=\"${track_num}\" \"${2}.${v_ext}\""

  # Execute commands for conversion
  print ""
  print -P -n "* (Default: %By%b) Do you want run the conversion? (y/n): " ; read run_commands_ffmpeg
  if [[ "${run_commands_ffmpeg}" == "n" ]] ; then
    exit
  else
    "${p_ffmpeg[@]}" "${1}" -map ${audio_track} -c:a ${acodec} -b:a ${b_acodec} "${stereo_params[@]}" -metadata title="${name_title}" -metadata date="${year_num}" -metadata genre="${genre_file}" -metadata album="${album_title}" -metadata artist="${artist_title}" -metadata track="${track_num}" "${2}.${v_ext}"
  fi
fi
