#!/usr/bin/env zsh

setopt NO_NOMATCH

#########################################################################
# ks-upv (ks-tools) - Upload videos file(s) to server with scp or rsync #
# Date: 25-08-2026                                                      #
# Author: dmesg00                                                       #
# Contact: dmesg00@duck.com                                             #
#########################################################################
VERSION=("9.5")
M_DATE=("250826")

# Global parameters.
dirTemp=("/tmp")
listCompTemp=("ks-tools.list-full")
listCompTempTest=("ks-tools.list-full.test")
listTemp=("ks-tools.list")
dirConfig=("${HOME}/.ks-tools")
ksToolsTempFolder=("/tmp/ks-tools")

# Check cygwin alias (for Windows)
if [[ -f "/usr/bin/cygwin-alias.zsh" ]] ; then
  setopt ALIASES
  cygwin=("yes")
  source "/usr/bin/cygwin-alias.zsh"
else
  cygwin=("no")
fi

# Set the correct permissions to the pem file
if [[ -f ${dirConfig}/connect.pem ]] ; then
  chmod 600 ${dirConfig}/connect.pem
fi

# Function to remove spaces and symbols
# Syntax: convertText "<text>"
convertText() {
  wordToConvert=${1}
  ksToolsSedFile=("${ksToolsTempFolder}/ks-tools-${RANDOM}.txt")
  mkdir -p ${ksToolsTempFolder} && chmod 777 -R ${ksToolsTempFolder} 2> /dev/null
  print "${wordToConvert}" > ${ksToolsSedFile}
  # Borrar espacios
  sed -i 's/ /_/g' "${ksToolsSedFile}" &> /dev/null
  # Borrar simbolos
  symbolsList=(
  "[" "]" "@" "{" "}" "|" "\\" "/" "~" "#" "$" 
  "%" "&" "?" "¿" "=" "(" ")" "<" ">" "!" "¡"
  )
  for findSymbol in "${symbolsList[@]}" ; do
    sed -i "s/${findSymbol}//g" "${ksToolsSedFile}" &> /dev/null
  done
  # Borrar el resto de simbolos
  sed -i 's/*//g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/"//g' "${ksToolsSedFile}" &> /dev/null
  sed -i "s/^//g" "${ksToolsSedFile}" &> /dev/null
  # Cambiar algunos simbolos
  sed -i 's/+/_/g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/:/-/g' "${ksToolsSedFile}" &> /dev/null
  sed -i 's/;/-/g' "${ksToolsSedFile}" &> /dev/null
  # Mostrar texto convertido
  wordToConvert=$(cat ${ksToolsSedFile})
  print ${wordToConvert}
}

# Function to list the files of a directory.
# Syntax: listArchives <directory>
listArchives() {
  fail=1
  formatFilesMayus=()
  formatFiles=(
  MP4 AVI MPG MPEG MOV WMV MKV OGV WEBM RM FLV VOB TS
  mp4 avi mpg mpeg mov wmv mkv ogv webm rm flv vob ts
  )
  # Rename files
  cd "${1}"
  mkdir -p ${ksToolsTempFolder}
  ls -1 > ${ksToolsTempFolder}/rename-files.txt
  count=1
  sizeFile=$(cat ${ksToolsTempFolder}/rename-files.txt | wc -l)
  while (( count <= sizeFile )) ; do
    fileToRename=$(cat ${ksToolsTempFolder}/rename-files.txt | head -${count} | tail -1)
    fileRenamed=$(convertText "${fileToRename}")
    if [[ "${fileRenamed}" == "${fileToRename}" ]] ; then
      print "null" > /dev/null
    else
      mv "${fileToRename}" "${fileRenamed}"
    fi
    count=$(expr $count + 1)
  done
  # Scan video files
  rm -rf ${dirTemp}/${listTemp}
  rm -rf ${dirTemp}/${listCompTemp}
  for format in "${formatFiles[@]}" ; do
    find "${1}"/*.${format} &> ${dirTemp}/${listCompTempTest}
    if (( $? != 0 )) ; then
      print "null" > /dev/null
    else
      find "${1}"/*.${format} &> ${dirTemp}/temp.tmp
      cat ${dirTemp}/temp.tmp >> ${dirTemp}/${listCompTemp}
      print "+ Video file(s) in .${format} found!"
      cd "${1}" && ls -1 *.${format} &> ${dirTemp}/temp.tmp
      cat ${dirTemp}/temp.tmp >> ${dirTemp}/${listTemp}
      rm -rf ${dirTemp}/temp.tmp 2> /dev/null
      fail=0
    fi
  done
  if (( fail == 1 )) ; then
    print "+ No video file(s) found!"
    print ""
    exit
  else
    print ""
  fi
}

# Function to count the found files.
countArchives() {
  totalArchives=$(cat ${dirTemp}/${listCompTemp} | wc -l)
  print ${totalArchives}
}

# Function to show files with spaces.
# Syntax: showFileWithSpace <file number>
showFileWithSpace() {
  FileName=$(cat ${dirTemp}/${listTemp} | head -${1} | tail -1)
  FileNoExtension=$(print $FileName | cut -d "." -f 1)
  print $FileNoExtension > ${dirTemp}/name.tmp
  sed -i 's/_/ /g' ${dirTemp}/name.tmp 2> /dev/null
  DisplayName=$(cat ${dirTemp}/name.tmp)
  rm -rf ${dirTemp}/name.tmp
  print ${DisplayName}
}

# Function to show the name of the file.
# Syntax: showFile <file number>
showFile() {
  archive=$(cat ${dirTemp}/${listTemp} | head -${1} | tail -1)
  print ${archive}
}

# Function to show full file path.
# Syntax: showPathFile <file number>
showPathFile() {
  pathFile=$(cat ${dirTemp}/${listCompTemp} | head -${1} | tail -1)
  print ${pathFile}
}

# Function to send file to server.
# Syntax: sendFile <password> <file path> <user> <server> <server path> [file name]
sendFile() {
  correct=0
  countSend=0
  toolSelected=$(cat ${dirConfig}/ks-upload-tool)
  portSelected=$(cat ${dirConfig}/ks-upload-port)
  while (( correct == 0 )) ; do
    # Run command for upload on Windows (Cygwin)
    if [[ "${cygwin}" == "yes" ]] ; then
      if [[ "${toolSelected}" == "rsync" ]] ; then
        /usr/bin/rsync --progress -azL --rsh="/usr/bin/sshpass -p ${1} /usr/bin/ssh -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} -l ${3}" ${2} ${4}:${5} 2> /dev/null
        /usr/bin/sshpass -p ${1} /usr/bin/ssh -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} ${3}@${4} rm -rf ${5}/.${6}.* &> /dev/null
        OUTPUT=$?
      elif [[ "${toolSelected}" == "rsync-e" ]] ; then
        keyscan_host=$(cat ~/.ssh/known_hosts | grep ${4})
        if [[ -z "${keyscan_host}" ]] ; then
          /usr/bin/ssh-keyscan -p ${portSelected} ${4} >> ~/.ssh/known_hosts
        fi
        # Sync files using rsync with expect
        /usr/bin/expect <<EOF
spawn /usr/bin/rsync --progress -azL --port=${portSelected} ${2} ${3}@${4}:${5}
set timeout -1
expect "*?assword:*"
send "${1}\n"
expect eof
EOF
        # Remove temporal files
        /usr/bin/expect <<EOF
spawn /usr/bin/ssh -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} ${3}@${4} rm -rf ${5}/.${6}.*
set timeout -1
expect "*?assword:*"
send "${1}\n"
expect eof
EOF
        OUTPUT=$?
      elif [[ "${toolSelected}" == "scp-e" ]] ; then
        # Sync files using scp with expect
        /usr/bin/expect <<EOF
spawn /usr/bin/scp -o StrictHostKeyChecking=no -o CheckHostIP=no -P ${portSelected} ${2} ${3}@${4}:${5} 
set timeout -1
expect "*?assword:*"
send "${1}\n"
expect eof
EOF
        # Remove temporal files
        /usr/bin/expect <<EOF
spawn /usr/bin/ssh -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} ${3}@${4} rm -rf ${5}/.${6}.*
set timeout -1
expect "*?assword:*"
send "${1}\n"
expect eof
EOF
        OUTPUT=$?
      elif [[ "${toolSelected}" == "rsync-rsa" ]] ; then
        /usr/bin/rsync --progress -azL --rsh="/usr/bin/sshpass -p ${1} /usr/bin/ssh -o HostKeyAlgorithms=+ssh-rsa -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} -l ${3}" ${2} ${4}:${5} 2> /dev/null
        /usr/bin/sshpass -p ${1} /usr/bin/ssh -o HostKeyAlgorithms=+ssh-rsa -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} ${3}@${4} rm -rf ${5}/.${6}.* &> /dev/null
        OUTPUT=$?
      elif [[ "${toolSelected}" == "scp-rsa" ]] ; then
        /usr/bin/sshpass -p ${1} /usr/bin/scp -o HostKeyAlgorithms=+ssh-rsa -o StrictHostKeyChecking=no -o CheckHostIP=no -P ${portSelected} ${2} ${3}@${4}:${5} 2> /dev/null
        OUTPUT=$?
      elif [[ "${toolSelected}" == "rsync-pem" ]] ; then
        /usr/bin/rsync --progress -azL --rsh="/usr/bin/ssh -i ${dirConfig}/connect.pem -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} -l ${3}" ${2} ${4}:${5} 2> /dev/null
        /usr/bin/ssh -i ${dirConfig}/connect.pem -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} ${3}@${4} rm -rf ${5}/.${6}.* &> /dev/null
        OUTPUT=$?
      elif [[ "${toolSelected}" == "scp-pem" ]] ; then
        /usr/bin/scp -i ${dirConfig}/connect.pem -o StrictHostKeyChecking=no -o CheckHostIP=no -P ${portSelected} ${2} ${3}@${4}:${5} 2> /dev/null
        OUTPUT=$?
      else
        /usr/bin/sshpass -p ${1} /usr/bin/scp -o StrictHostKeyChecking=no -o CheckHostIP=no -P ${portSelected} ${2} ${3}@${4}:${5} 2> /dev/null
        OUTPUT=$?
      fi
    # Run command for upload on Unix systems
    else
      if [[ "${toolSelected}" == "rsync" ]] ; then
        rsync --progress -azL --rsh="sshpass -p ${1} ssh -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} -l ${3}" ${2} ${4}:${5} 2> /dev/null
        sshpass -p ${1} ssh -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} ${3}@${4} rm -rf ${5}/.${6}.* &> /dev/null
        OUTPUT=$?
      elif [[ "${toolSelected}" == "rsync-e" ]] ; then
        keyscan_host=$(cat ~/.ssh/known_hosts | grep ${4})
        if [[ -z "${keyscan_host}" ]] ; then
          ssh-keyscan -p ${portSelected} ${4} >> ~/.ssh/known_hosts
        fi
        # Sync files using rsync with expect
        expect <<EOF
spawn rsync --progress -azL --port=${portSelected} ${2} ${3}@${4}:${5}
set timeout -1
expect "*?assword:*"
send "${1}\n"
expect eof
EOF
        # Remove temporal files
        expect <<EOF
spawn ssh -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} ${3}@${4} rm -rf ${5}/.${6}.*
set timeout -1
expect "*?assword:*"
send "${1}\n"
expect eof
EOF
        OUTPUT=$?
      elif [[ "${toolSelected}" == "scp-e" ]] ; then
        # Sync files using scp with expect
        expect <<EOF
spawn scp -o StrictHostKeyChecking=no -o CheckHostIP=no -P ${portSelected} ${2} ${3}@${4}:${5}
set timeout -1
expect "*?assword:*"
send "${1}\n"
expect eof
EOF
        # Remove temporal files
        expect <<EOF
spawn ssh -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} ${3}@${4} rm -rf ${5}/.${6}.*
set timeout -1
expect "*?assword:*"
send "${1}\n"
expect eof
EOF
        OUTPUT=$?
      elif [[ "${toolSelected}" == "rsync-rsa" ]] ; then
        rsync --progress -azL --rsh="sshpass -p ${1} ssh -o HostKeyAlgorithms=+ssh-rsa -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} -l ${3}" ${2} ${4}:${5} 2> /dev/null
        OUTPUT=$?
        sshpass -p ${1} ssh -o HostKeyAlgorithms=+ssh-rsa -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} ${3}@${4} rm -rf ${5}/.${6}.* &> /dev/null
      elif [[ "${toolSelected}" == "scp-rsa" ]] ; then
        sshpass -p ${1} scp -o HostKeyAlgorithms=+ssh-rsa -o StrictHostKeyChecking=no -o CheckHostIP=no -P ${portSelected} ${2} ${3}@${4}:${5} 2> /dev/null
        OUTPUT=$?
      elif [[ "${toolSelected}" == "rsync-pem" ]] ; then
        rsync --progress -azL --rsh="ssh -i ${dirConfig}/connect.pem -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} -l ${3}" ${2} ${4}:${5} 2> /dev/null
        OUTPUT=$?
        ssh -i ${dirConfig}/connect.pem -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} ${3}@${4} rm -rf ${5}/.${6}.* &> /dev/null
      elif [[ "${toolSelected}" == "scp-pem" ]] ; then
        scp -i ${dirConfig}/connect.pem -o StrictHostKeyChecking=no -o CheckHostIP=no -P ${portSelected} ${2} ${3}@${4}:${5} 2> /dev/null
        OUTPUT=$?
      else
        sshpass -p ${1} scp -o StrictHostKeyChecking=no -o CheckHostIP=no -P ${portSelected} ${2} ${3}@${4}:${5} 2> /dev/null
        OUTPUT=$?
      fi
    fi
    if (( ${OUTPUT} != 0 )) ; then
      print -P "Failure to send %U${2}%u"
      print "Retrying..."
      sleep 5
      countSend=$(expr ${countSend} + 1)
      if (( countSend == 3 )) ; then
        correct=1
      fi
    else
      correct=1
    fi
  done
}

# Function to check local and server checksum.
# Syntax: checkChecksum <password> <local file path> <user> <server> <server file path>
checkChecksum() {
  correct=0
  countChecksum=0
  print -n "Checking checksum... " && sleep 4
  print ""
  toolSelected=$(cat ${dirConfig}/ks-upload-tool | grep "rsa")
  selectedTool=$(cat ${dirConfig}/ks-upload-tool)
  portSelected=$(cat ${dirConfig}/ks-upload-port)
  while (( correct == 0 )) ; do
    if [[ "${cygwin}" == "yes" ]] ; then
      if [[ -z "${toolSelected}" ]] ; then
        if [[ "${selectedTool}" == "rsync-pem" ]] ; then
          checksumLocal=$(/usr/bin/md5sum ${2})
          checksumServer=$(/usr/bin/ssh -i ${dirConfig}/connect.pem -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} ${3}@${4} md5sum ${5} 2> /dev/null)
          OUTPUT=$?
        elif [[ "${selectedTool}" == "scp-pem" ]] ; then
          checksumLocal=$(md5sum ${2})
          checksumServer=$(/usr/bin/ssh -i ${dirConfig}/connect.pem -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} ${3}@${4} md5sum ${5} 2> /dev/null)
          OUTPUT=$?
        else
          checksumLocal=$(/usr/bin/md5sum ${2})
          checksumServer=$(/usr/bin/sshpass -p ${1} /usr/bin/ssh -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} ${3}@${4} md5sum ${5} 2> /dev/null)
          OUTPUT=$?
        fi
      elif [[ "${selectedTool}" == "rsync-e" ]] ; then
        print > /dev/null
        OUTPUT=0
      elif [[ "${selectedTool}" == "scp-e" ]] ; then
        print > /dev/null
        OUTPUT=0
      else
        checksumLocal=$(/usr/bin/md5sum ${2})
        checksumServer=$(/usr/bin/sshpass -p ${1} /usr/bin/ssh -o HostKeyAlgorithms=+ssh-rsa -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} ${3}@${4} md5sum ${5} 2> /dev/null)
        OUTPUT=$?
      fi
    else
      if [[ -z "${toolSelected}" ]] ; then
        if [[ "${selectedTool}" == "rsync-pem" ]] ; then
          checksumLocal=$(md5sum ${2})
          checksumServer=$(ssh -i ${dirConfig}/connect.pem -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} ${3}@${4} md5sum ${5} 2> /dev/null)
          OUTPUT=$?
        elif [[ "${selectedTool}" == "scp-pem" ]] ; then
          checksumLocal=$(md5sum ${2})
          checksumServer=$(ssh -i ${dirConfig}/connect.pem -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} ${3}@${4} md5sum ${5} 2> /dev/null)
          OUTPUT=$?
        else
          checksumLocal=$(md5sum ${2})
          checksumServer=$(sshpass -p ${1} /usr/bin/ssh -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} ${3}@${4} md5sum ${5} 2> /dev/null)
          OUTPUT=$?
        fi
      elif [[ "${selectedTool}" == "rsync-e" ]] ; then
        print > /dev/null
        OUTPUT=0
      elif [[ "${selectedTool}" == "scp-e" ]] ; then
        print > /dev/null
        OUTPUT=0
      else
        checksumLocal=$(md5sum ${2})
        checksumServer=$(sshpass -p ${1} ssh -o HostKeyAlgorithms=+ssh-rsa -o StrictHostKeyChecking=no -o CheckHostIP=no -p ${portSelected} ${3}@${4} md5sum ${5} 2> /dev/null)
        OUTPUT=$?
      fi
    fi
    if (( OUTPUT != 0 )) ; then
      print "Failed to get checksum for ${5}"
      print "Retrying..."
      sleep 5
      countChecksum=$(expr ${countChecksum} + 1)
      if (( countChecksum == 3 )) ; then
        correct=1
      fi
    else
      if [[ "${selectedTool}" == "rsync-e" ]] ; then
        print > /dev/null
        correct=1
      elif [[ "${selectedTool}" == "scp-e" ]] ; then
        print > /dev/null
        correct=1
      else
      print "Local checksum: ${checksumLocal}"
      print "Server checksum: ${checksumServer}"
      correct=1
      fi
    fi
  done
}

# Generate random codes 
generate_codes() {
  chars=("abcdefghijklmnopqrstywxz1234567890ABCDEFHIJKLMNOPQRSTYWXZ@/")
  long_code=("${1}")
  for i in {1} ; do
    print -n "${chars:RANDOM%${#chars}:1}"
  done
}

# Function to encrypt pass on config file
# Syntax: encrypt_kstools <password>
encrypt_kstools() {
  raw_pass=("${1}")
  characters_pass_raw=$(print ${raw_pass} | wc -m)
  characters_pass=$(expr ${characters_pass_raw} - 1)
  total_characters=0
  mkdir -p ${HOME}/.ks-tools/
  rm -rf ${HOME}/.ks-tools/.seq-codes
  while (( total_characters <= characters_pass )) ; do
    num_gen=$(print -n ${RANDOM} | cut -c1)
    print -n ${num_gen} >> ${HOME}/.ks-tools/.seq-codes
    total_characters=$(expr ${total_characters} + 1)
  done
  characters_seq_raw=$(cat ${HOME}/.ks-tools/.seq-codes 2> /dev/null | wc -m)
  characters_seq=$(expr ${characters_seq_raw} - 1)
  total_characters=1
  encrypted_pass=()
  while (( total_characters <= characters_pass )) ; do
    num_seq_read=$(cat ${HOME}/.ks-tools/.seq-codes 2> /dev/null | cut -c${total_characters})
    character=$(print ${raw_pass} | cut -c${total_characters})
    repeat_seq=0
    while (( repeat_seq < num_seq_read )) ; do
      code_gen=$(generate_codes)
      encrypted_pass=("${encrypted_pass}${code_gen}")
      repeat_seq=$(expr ${repeat_seq} + 1)
    done
    encrypted_pass=("${encrypted_pass}${character}")
    total_characters=$(expr ${total_characters} + 1)
  done
  code_gen=$(generate_codes)
  encrypted_pass=("${encrypted_pass}${code_gen}")
  print ${encrypted_pass}
}

# Function to decrypt pass on config file
# Syntax: decrypt_kstools <password>
decrypt_kstools() {
  raw_pass_encrypted=("${1}")
  total_characters=1
  codes_seq=$(cat ${HOME}/.ks-tools/.seq-codes 2> /dev/null)
  num_codes_seq=$(cat ${HOME}/.ks-tools/.seq-codes 2> /dev/null | wc -m)
  pass_decrypt=()  total_characters=1
  pos_codes_pass=0
  while (( total_characters < num_codes_seq )) ; do
    pos_codes=$(print ${codes_seq} | cut -c${total_characters})
    pos_codes_pass=$(expr ${pos_codes_pass} + ${pos_codes} + 1)
    pos_pass=$(expr ${raw_pass_encrypted} | cut -c${pos_codes_pass})
    pass_decrypt=("${pass_decrypt}${pos_pass}")
    total_characters=$(expr ${total_characters} + 1)
  done
  print ${pass_decrypt}
}

# Function to generate certificate on remote machine
gen_pem_ssh() {
  userhost=("${USER}")
  name_host=("${HOSTNAME}")
  print "" && print "* Generating .pem file to connect to this machine (${userhost})."
  print "${userhost}\n\n\n" | ssh-keygen
  mv ${userhost} ${userhost}-${name_host}.pem
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  touch ~/.ssh/authorized_keys
  chmod 600  ~/.ssh/authorized_keys
  print "* Adding entry in the file ~/.ssh/authorized_keys"
  cat ${userhost}.pub >> ~/.ssh/authorized_keys
  rm -rf ${userhost}.pub
  print ""
  print "+ Copy the ${userhost}-${name_host}.pem file to your computer to connect to this machine."
  if [[ -f /usr/bin/puttygen ]] ; then
    puttygen ${userhost}-${name_host}.pem -o ${userhost}-${name_host}.ppk -O private
    print "+ Copy the ${userhost}-${name_host}.ppk file to your computer to connect to this machine."
  fi
  print "+ Connect: ssh -i ${userhost}-${name_host}.pem ${userhost}@${name_host}"
  print ""
}

# Function to show config
showConfig() {
  configAvailable=0
  print ""
  print -P "* %Bks-upv%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
  print ""
  if [[ -f ${dirConfig}/ks-upload-user ]] ; then
    showUser=$(cat ${dirConfig}/ks-upload-user)
    print "\- Server User: ${showUser}"
    configAvailable=1
  fi
  if [[ -f ${dirConfig}/ks-upload-pass ]] ; then
    readPasswordEncrypted=$(cat ${dirConfig}/ks-upload-pass)
    readPasswordDecrypted=$(decrypt_kstools "${readPasswordEncrypted}")
    readPasswordChars=$(print ${readPasswordDecrypted} | wc -m)
    totalchars=0
    showPassword=()
    while (( totalchars < readPasswordChars )) ; do
      showPassword=("${showPassword}*")
      totalchars=$(expr ${totalchars} + 1)
    done
    print "\- Server Password/PEM: ${showPassword}"
    configAvailable=1
  fi
  if [[ -f ${dirConfig}/ks-upload-server ]] ; then
    showServer=$(cat ${dirConfig}/ks-upload-server)
    print "\- URL (or IP) Server: ${showServer}"
    configAvailable=1
  fi
  if [[ -f ${dirConfig}/ks-upload-dirserver ]] ; then
    showDirServer=$(cat ${dirConfig}/ks-upload-dirserver)
    print "\- Destination Path (Server): ${showDirServer}"
    configAvailable=1
  fi
  if [[ -f ${dirConfig}/ks-upload-dirlocal ]] ; then
    showDirLocal=$(cat ${dirConfig}/ks-upload-dirlocal)
    print "\- Scan Path (Local): ${showDirLocal}"
    configAvailable=1
  fi
  if [[ -f ${dirConfig}/ks-upload-tool ]] ; then
    showUpvTool=$(cat ${dirConfig}/ks-upload-tool)
    print "\- Upload Tool: ${showUpvTool}"
    configAvailable=1
  fi
  if [[ -f ${dirConfig}/ks-upload-port ]] ; then
    showUpvPort=$(cat ${dirConfig}/ks-upload-port)
    print "\- Port Connection: ${showUpvPort}"
    configAvailable=1
  fi
  if (( configAvailable == 0 )) ; then
    print "* The configuration file does not exist!"
  fi
  print ""
  exit
}

# Function to edit the configuration file
editConfig() {
  editConfig=0
  while (( editConfig == 0 )) ; do
    clear
    editUser=$(cat ${dirConfig}/ks-upload-user 2> /dev/null)
    readPasswordEncrypted=$(cat ${dirConfig}/ks-upload-pass)
    readPasswordDecrypted=$(decrypt_kstools "${readPasswordEncrypted}")
    readPasswordChars=$(print ${readPasswordDecrypted} | wc -m)
    totalchars=0
    editPassword=()
    while (( totalchars < readPasswordChars )) ; do
      editPassword=("${editPassword}*")
      totalchars=$(expr ${totalchars} + 1)
    done
    editServer=$(cat ${dirConfig}/ks-upload-server 2> /dev/null)
    editDirServer=$(cat ${dirConfig}/ks-upload-dirserver 2> /dev/null)
    editDirLocal=$(cat ${dirConfig}/ks-upload-dirlocal 2> /dev/null)
    editUpvTool=$(cat ${dirConfig}/ks-upload-tool 2> /dev/null)
    editUpvPort=$(cat ${dirConfig}/ks-upload-port 2> /dev/null)
    print ""
    print -P "* %Bks-upv%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
    print ""
    print -P "+ %UConfig%u: %B${dirConfig}/ks-upload-*%b"
    print ""
    print -P " 1 - Edit User (%B${editUser}%b)"
    print -P " 2 - Edit Password/PEM (%B${editPassword}%b)"
    print -P " 3 - Edit Server (%B${editServer}%b)"
    print -P " 4 - Edit Dest. Path (%B${editDirServer}%b)"
    print -P " 5 - Edit Local Path (%B${editDirLocal}%b)"
    print -P " 6 - Edit Upload Tool (%B${editUpvTool}%b)"
    print -P " 7 - Edit Port Connection (%B${editUpvPort}%b)"
    print ""
    print " 8 - Exit"
    print ""
    print -n "* Choose an option: " ; read EDIT
    print ""
    if [[ "${EDIT}" == "1" ]] ; then
      print -n "* Enter the server user: " ; read USER
      user=${USER}
      print ${user} > ${dirConfig}/ks-upload-user
    elif [[ "${EDIT}" == "2" ]] ; then
      print -P -n "* Enter the server password (type %Upem%u for use pem certificate): " ; read PASS
      if [[ "${PASS}" == "pem" ]] ; then
        print -n "+ Type the absolute path to the .pem file: " ; read pem_path
      if [[ -f "${pem_path}" ]] ; then
        raw_password_enter=${PASS}
        encrypt_password_enter=$(encrypt_kstools "${raw_password_enter}")
        print ${encrypt_password_enter} > ${dirConfig}/ks-upload-pass
        cp -rf "${pem_path}" ${dirConfig}/connect.pem
        chmod 600 ${dirConfig}/connect.pem
        if [[ "${editUpvTool}" == "rsync" ]] ; then
          print "rsync-pem" > ${dirConfig}/ks-upload-tool
        elif [[ "${editUpvTool}" == "rsync-rsa" ]] ; then
          print "rsync-pem" > ${dirConfig}/ks-upload-tool
        elif [[ "${editUpvTool}" == "scp" ]] ; then
          print "scp-pem" > ${dirConfig}/ks-upload-tool
        elif [[ "${editUpvTool}" == "scp-rsa" ]] ; then
          print "scp-pem" > ${dirConfig}/ks-upload-tool
        fi
        print -P "* PEM file copied to %U${dirConfig}/connect.pem%u"
      else
        print -P "+ File %U${pem_path}%u does not exist"
        print ""
        print -P "+ Press %UENTER%u to return menu " ; read continue
      fi
      else
        raw_password_enter=${PASS}
        encrypt_password_enter=$(encrypt_kstools "${raw_password_enter}")
        print ${encrypt_password_enter} > ${dirConfig}/ks-upload-pass
        if [[ "${editUpvTool}" == "rsync-pem" ]] ; then
          print "rsync" > ${dirConfig}/ks-upload-tool
        elif [[ "${editUpvTool}" == "scp-pem" ]] ; then
          print "scp" > ${dirConfig}/ks-upload-tool
        fi
      fi
    elif [[ "${EDIT}" == "3" ]] ; then
      print -n "* Enter the server URL: " ; read SERVER
      server=${SERVER}
      print ${server} > ${dirConfig}/ks-upload-server
    elif [[ "${EDIT}" == "4" ]] ; then
      print -n "* Enter the path on the server: " ; read DIR_SERVER
      dirServer=${DIR_SERVER}
      print ${dirServer} > ${dirConfig}/ks-upload-dirserver
    elif [[ "${EDIT}" == "5" ]] ; then
      print -n "* Enter the local path to scan: " ; read DIR
      dirLocal=${DIR}
      print ${dirLocal} > ${dirConfig}/ks-upload-dirlocal
     elif [[ "${EDIT}" == "6" ]] ; then
      print ""
      print -P "* %UAvailable options%u:"
      print ""
      print "\- scp"
      print "\- rsync"
      print "\- scp-rsa (legacy RSA algorithm)"
      print "\- rsync-rsa (legacy RSA algorithm)"
      print "\- scp-e"
      print "\- rsync-e"
      print "\- scp-pem"
      print "\- rsync-pem"
      print ""
      print -P "* %UNote%u: 'scp-e' and 'rsync-e' use 'expect' instead of 'sshpass'."
      print -P "* %UNote%u: 'scp-pem' and 'rsync-pem' use ~/.ks-tools/connect.pem."
      print "" 
      print -n "* [Default: scp] Type upload tool (Example: rsync-e): " ; read TOOL
      if [[ -z "${TOOL}" ]] ; then
        upvTool=("scp")
      elif [[ "${TOOL}" == "rsync" ]] ; then
        upvTool=("rsync")
      elif [[ "${TOOL}" == "rsync-rsa" ]] ; then
        upvTool=("rsync-rsa")
      elif [[ "${TOOL}" == "scp-rsa" ]] ; then
        upvTool=("scp-rsa")
      elif [[ "${TOOL}" == "scp-e" ]] ; then
        upvTool=("scp-e")
      elif [[ "${TOOL}" == "rsync-e" ]] ; then
        upvTool=("rsync-e")
      elif [[ "${TOOL}" == "scp-pem" ]] ; then
        upvTool=("scp-pem")
      elif [[ "${TOOL}" == "rsync-pem" ]] ; then
        upvTool=("rsync-pem")
      else  
        upvTool=("scp")
      fi
      print ${upvTool} > ${dirConfig}/ks-upload-tool
    elif [[ "${EDIT}" == "7" ]] ; then
      print -n "* [Default: 22] Type port connection: " ; read PORT
      if [[ -z "${PORT}" ]] ; then
        upvPort=("22")
      else
        upvPort=("${PORT}")
      fi
      print ${upvPort} > ${dirConfig}/ks-upload-port
    elif [[ "${EDIT}" == "8" ]] ; then
      editConfig=1
    else
      print "+ Invalid option!"
      print -n "- Press ENTER to continue " ; read CONTINUE
    fi
  done
  exit
}

# Function to create initial config file.
createConfig() {
# Start script
  clear
  print ""
  print -P "* %Bks-upv%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
  print ""
  checkDependencies
  # Ask the user and if it exists, read it from the config.
  if [[ -f ${dirConfig}/ks-upload-user ]] ; then
    print -P "+ The %BUSER%b configuration already exists (Use: %Uks-upv -e%u for edit)"
  else
    print -n "* Enter the server user: " ; read USER
    user=${USER}
    print ${user} > ${dirConfig}/ks-upload-user
  fi
  # Ask the password and if it exists, read it from the config.
  if [[ -f ${dirConfig}/ks-upload-pass ]] ; then
    print -P "+ The %BPASSWORD/PEM%b configuration already exists (Use: %Uks-upv -e%u for edit)" 
  else
    print -P -n "* Enter the server password (type %Upem%u for use pem certificate): " ; read PASS
    if [[ "${PASS}" == "pem" ]] ; then
      print -n "+ Type the absolute path to the .pem file: " ; read pem_path
      if [[ -f "${pem_path}" ]] ; then
        raw_password_enter=${PASS}
        encrypt_password_enter=$(encrypt_kstools "${raw_password_enter}")
        print ${encrypt_password_enter} > ${dirConfig}/ks-upload-pass
        cp -rf "${pem_path}" ${dirConfig}/connect.pem
        chmod 600 ${dirConfig}/connect.pem
        print "scp-pem" > ${dirConfig}/ks-upload-tool
        print -P "* PEM file copied to %U${dirConfig}/connect.pem%u"
      else
        print -P "+ File %U${pem_path}%u does not exist"
        print "+ The configuration is cancelled"
        exit
      fi
    else
      raw_password_enter=${PASS}
      encrypt_password_enter=$(encrypt_kstools "${raw_password_enter}")
      print ${encrypt_password_enter} > ${dirConfig}/ks-upload-pass
    fi
  fi
  # Ask the server URL and if it exists, read it from the config.
  if [[ -f ${dirConfig}/ks-upload-server ]] ; then
    print -P "+ The %BSERVER%b configuration already exists (Use: %Uks-upv -e%u for edit)"
  else
    print -n "* Enter the server URL (or IP): " ; read SERVER
    server=${SERVER}
    print ${server} > ${dirConfig}/ks-upload-server
  fi
  # Ask the path on the server and if it exists, read it from the config.
  if [[ -f ${dirConfig}/ks-upload-dirserver ]] ; then
    print -P "+ The %BSERVER PATH%b configuration already exists (Use: %Uks-upv -e%u for edit)"
  else
    print -n "* Enter the path on the server: " ; read DIR_SERVER
    dirServer=${DIR_SERVER}
    print ${dirServer} > ${dirConfig}/ks-upload-dirserver
  fi
  # Ask the local path and if it exists, read it from the config.
  if [[ -f ${dirConfig}/ks-upload-dirlocal ]] ; then
    print -P "+ The %BLOCAL PATH%b configuration already exists (Use: %Uks-upv -e%u for edit)"
  else
    print -n "* Enter the local path to scan: " ; read DIR
    dirLocal=${DIR}
    print ${dirLocal} > ${dirConfig}/ks-upload-dirlocal
  fi
  # Configure upload tool by default
  if [[ -f ${dirConfig}/ks-upload-tool ]] ; then
    print -P "+ The %BUPLOAD TOOL%b configuration already exists (Use: %Uks-upv -e%u for edit)"
  else
    if [[ "${PASS}" == "pem" ]] ; then
      print "* Setting 'scp-pem' as the default tool"
      print "scp-pem" > ${dirConfig}/ks-upload-tool
    else
      print "* Setting 'scp' as the default tool"
      print "scp" > ${dirConfig}/ks-upload-tool
    fi
  fi
   # Configure port by default
  if [[ -f ${dirConfig}/ks-upload-port ]] ; then
    print -P "+ The %BPORT%b configuration already exists (Use: %Uks-upv -e%u for edit)"
  else
    print "* Setting port 22 as the default port"
    print "22" > ${dirConfig}/ks-upload-port
  fi
  print ""
}

# Function to show version
showVersion() {
  print ""
  print -P "* %Bks-upv%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
  print ""
  exit
}

# Function to show help
showHelp() {
  print ""
  print -P "* %Bks-upv%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
  print ""
  print "\- Upload videos file(s) to server with scp or rsync"
  print ""
  print -P "+ %UConfig%u: %B${dirConfig}/ks-upload-*%b"
  print ""
  print -P "+ %USyntax%u:"
  print ""
  print -P " $ %Bks-upv%b -i  - Start upload"
  print -P " $ %Bks-upv%b -g  - Create configuration"
  print -P " $ %Bks-upv%b -r  - Remove configuration"
  print -P " $ %Bks-upv%b -c  - Show configuration"
  print -P " $ %Bks-upv%b -e  - Edit configuration"
  print -P " $ %Bks-upv%b -p  - Generate certificate"
  print -P " $ %Bks-upv%b -v  - Show version"
  print -P " $ %Bks-upv%b -h  - Show help"
  print ""
  exit
}

# Function for check dependencies
check_dependencies() {
  which_dependence=$(which ${1})
  error_dependence=$?
  if [[ -z "${which_dependence}" ]] || (( ${error_dependence} > 0 )); then
    print ""
    print -P "* Some required tools are not installed: %U${1}%u"
    print "* The process has been stopped"
    print ""
    exit 1
  fi 
}

# Check dependencies
checkDependencies() {
  print "* Checking necessary tools... "
  dependencies=(sshpass expect rsync md5sum scp ssh find grep sed cut head tail cat ssh-keyscan ssh-keygen)
  for scan_dependency in "${dependencies[@]}" ; do
    check_dependencies "${scan_dependency}"
  done
  print "* The necessary tools are installed"
}

# Function to migrate old configuration.
if [[ -f ${dirConfig}/USER ]] ; then
  cat ${dirConfig}/USER > ${dirConfig}/ks-upload-user
  print "* Migrating ${dirConfig}/USER > ${dirConfig}/ks-upload-user"
  rm -rf ${dirConfig}/USER
  sleep 1
fi
if [[ -f ${dirConfig}/PASS ]] ; then
  print "* Migrating ${dirConfig}/PASS > ${dirConfig}/ks-upload-pass"
  current_pass=$(cat ${dirConfig}/PASS)
  encrypt_kstools "${current_pass}" > ${dirConfig}/ks-upload-pass
  rm -rf ${dirConfig}/PASS
  sleep 1
fi
if [[ -f ${dirConfig}/SERVER ]] ; then
  cat ${dirConfig}/SERVER > ${dirConfig}/ks-upload-server
  print "* Migrating ${dirConfig}/SERVER > ${dirConfig}/ks-upload-server"
  rm -rf ${dirConfig}/SERVER
  sleep 1
fi
if [[ -f ${dirConfig}/DIR_SERVER ]] ; then
  cat ${dirConfig}/DIR_SERVER > ${dirConfig}/ks-upload-dirserver
  print "* Migrating ${dirConfig}/DIR_SERVER > ${dirConfig}/ks-upload-dirserver"
  rm -rf ${dirConfig}/DIR_SERVER
  sleep 1
fi
if [[ -f ${dirConfig}/DIR ]] ; then
  cat ${dirConfig}/DIR > ${dirConfig}/ks-upload-dirlocal
  print "* Migrating ${dirConfig}/DIR > ${dirConfig}/ks-upload-dirlocal"
  rm -rf ${dirConfig}/DIR
  sleep 1
fi

# Check if the configuration directory exists.
if [[ -d ${dirConfig} ]] ; then
  print ${dirConfig} > /dev/null
else
  mkdir -p ${dirConfig}
fi

# Delete the existing configuration.
if [[ "${1}" == "-r" ]] ; then
  print ""
  print -P "* %Bks-upv%b (ks-tools) %Bv${VERSION}%b (${M_DATE})"
  print ""
  print -n "* [Default: n] Are you sure you want to delete the configuration? (y/n): " ; read confirm
  if [[ "${confirm}" == "y" ]] ; then
    print ""
    print -P "+ Removing %BUSER%b file configuration..."
    rm -rf ${dirConfig}/ks-upload-user
    print -P "+ Removing %BPASSWORD/PEM%b file configuration..."
    rm -rf ${dirConfig}/ks-upload-pass
    rm -rf ${dirConfig}/connect.pem
    print -P "+ Removing %BSERVER%b file configuration..."
    rm -rf ${dirConfig}/ks-upload-server
    print -P "+ Removing %BSERVER PATH%b file configuration..."
    rm -rf ${dirConfig}/ks-upload-dirserver
    print -P "+ Removing %BLOCAL PATH%b file configuration..."
    rm -rf ${dirConfig}/ks-upload-dirlocal
    print "* Removed all configuration"
    rm -rf ${dirConfig}/ks-upload-tool
    rm -rf ${dirConfig}/ks-upload-port 
    print ""
    exit
  else
    print ""
    print "+ Remove configuration canceled"
    print ""
    exit
  fi
fi
# Show configuration file
if [[ "${1}" == "-c" ]] ; then
  showConfig
  # Edit configuration file
elif [[ "${1}" == "-e" ]] ; then
  editConfig
  # Show the version
elif [[ "${1}" == "-v" ]] ; then
  showVersion
  # Generate certificate
elif [[ "${1}" == "-p" ]] ; then
  gen_pem_ssh
  # Show the help
elif [[ "${1}" == "-h" ]] ; then
  showHelp
  # Create config
elif [[ "${1}" == "-g" ]] ; then
  createConfig
  # Init
elif [[ "${1}" == "-i" ]] ; then
  # Start script
  createConfig
  user=$(cat ${dirConfig}/ks-upload-user)
  raw_password=$(cat ${dirConfig}/ks-upload-pass)
  password=$(decrypt_kstools "${raw_password}")
  server=$(cat ${dirConfig}/ks-upload-server)
  dirServer=$(cat ${dirConfig}/ks-upload-dirserver)
  dirLocal=$(cat ${dirConfig}/ks-upload-dirlocal)
  # Call the functions to perform the whole process.
  print -P -n "* Scanning %U${dirLocal}%u "
  print ""
  if [[ -d ${dirLocal} ]] ; then
    listArchives "${dirLocal}"
    totalFiles=$(countArchives)
    count=1
    print "+ ${totalFiles} video file(s) found!"
    print ""
    current_tool=$(cat ${dirConfig}/ks-upload-tool)
    if [[ "${current_tool}" == "scp" ]] ; then
      print "* NOTE: You are using 'scp' to upload files and no progress will be shown."
      print "* IMPORTANT: It's possible switch to 'rsync' or 'scp-e' if you wish (Command: ks-upv -e)"
      print ""
    fi
    if [[ "${current_tool}" == "scp-rsa" ]] ; then
      print "* NOTE: You are using 'scp-rsa' to upload files and no progress will be shown."
      print "* IMPORTANT: It's possible switch to 'rsync-rsa' if you wish (Command: ks-upv -e)"
      print ""
    fi
    while (( count <= totalFiles )) ; do
      fullNameFile=$(showFile ${count})
      fullPathFile=$(showPathFile ${count})
      print -P "%BUploading%b %U${fullNameFile}%u "
      sendFile ${password} ${fullPathFile} ${user} ${server} ${dirServer} ${fullNameFile}
      if [[ "${current_tool}" == "scp-e" ]] ; then
        print > /dev/null
      elif [[ "${current_tool}" == "rsync-e" ]] ; then
        print > /dev/null
      else
        checkChecksum ${password} ${fullPathFile} ${user} ${server} ${dirServer}/${fullNameFile}
      fi
      print ""
      count=$(expr ${count} + 1)
    done
  else
    print "* Directory ${dirLocal} does not exist!"
    print ""
    exit
  fi
  # Show help
else
  showHelp
fi
